[package]
name = "cosmolkit-depict"
description = "Molecular depiction algorithms over detached model values"
keywords = ["cheminformatics", "depiction", "svg", "molecules"]
categories = ["science", "rendering"]
repository.workspace = true
homepage.workspace = true
license.workspace = true
version.workspace = true
edition.workspace = true
readme = "../cosmolkit/README.md"
documentation = "https://docs.rs/cosmolkit"

[dependencies]
cosmolkit-core = { version = "0.5.0-rc.5", path = "../cosmolkit-core" }
cosmolkit-model = { version = "0.5.0-rc.5", path = "../cosmolkit-model" }
cosmolkit-search = { version = "0.5.0-rc.5", path = "../cosmolkit-search" }
