[package]
name = "cosmolkit-conformer"
description = "Conformer generation and distance geometry over detached model values"
keywords = ["cheminformatics", "conformer", "distance-geometry"]
categories = ["science", "algorithms"]
repository.workspace = true
homepage.workspace = true
license.workspace = true
version.workspace = true
edition.workspace = true
readme = "../cosmolkit/README.md"
documentation = "https://docs.rs/cosmolkit"

[dependencies]
cosmolkit-model = { version = "0.5.0-rc.13", path = "../cosmolkit-model" }
thiserror = "2.0"
serde_json = "1.0"
cosmolkit-core = { version = "0.5.0-rc.13", path = "../cosmolkit-core", default-features = false }
libc = "0.2"

cosmolkit-forcefields = { version = "0.5.0-rc.13", path = "../cosmolkit-forcefields" }

cosmolkit-alignment = { version = "0.5.0-rc.13", path = "../cosmolkit-alignment" }

cosmolkit-search = { version = "0.5.0-rc.13", path = "../cosmolkit-search" }

[dev-dependencies]
cosmolkit-smiles = { version = "0.5.0-rc.13", path = "../cosmolkit-smiles" }

cosmolkit-io = { version = "0.5.0-rc.13", path = "../cosmolkit-io", default-features = false, features = ["molecule"] }
