use std::{
    env, fs,
    path::{Path, PathBuf},
    process::Command,
};

const PAGES: &[&str] = &[
    "installation",
    "quickstart",
    "confseq",
    "molecule",
    "batch",
    "fingerprints",
    "descriptors",
    "protein",
    "io",
    "api",
    "search",
    "genindex",
    "py-modindex",
];

fn main() {
    println!("cargo:rerun-if-changed=../python/docs/source");
    println!("cargo:rerun-if-changed=../python/docs/build/html");

    let manifest_dir =
        PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").expect("manifest directory"));
    let repository_root = manifest_dir.parent().expect("repository root");
    let docs_source = repository_root.join("python/docs/source");
    let docs_output = repository_root.join("python/docs/build/html");

    if !docs_output.join("index.html").is_file() {
        build_sphinx(&repository_root, &docs_source, &docs_output);
    }

    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR"));
    let generated = generate_document_module(&docs_output);
    fs::write(out_dir.join("sphinx_docs.rs"), generated).expect("write generated Sphinx module");
}

fn build_sphinx(repository_root: &Path, source: &Path, output: &Path) {
    let python = env::var_os("COSMOLKIT_DOCS_PYTHON")
        .map(PathBuf::from)
        .filter(|path| path.is_file())
        .or_else(|| {
            let path = repository_root.join(".venv/bin/python");
            path.is_file().then_some(path)
        })
        .unwrap_or_else(|| PathBuf::from("python3"));

    let status = Command::new(&python)
        .args(["-m", "sphinx", "-W", "--keep-going", "-E", "-b", "html"])
        .arg(source)
        .arg(output)
        .current_dir(repository_root)
        .status()
        .unwrap_or_else(|error| panic!("failed to run Sphinx with {}: {error}", python.display()));
    assert!(
        status.success(),
        "Sphinx documentation build failed with status {status}"
    );
}

fn generate_document_module(output: &Path) -> String {
    let mut module = String::from("// Generated by docs-web/build.rs; do not edit.\n");
    for page in PAGES {
        let path = output.join(format!("{page}.html"));
        let html = fs::read_to_string(&path).unwrap_or_else(|error| {
            panic!("read compiled Sphinx page {}: {error}", path.display())
        });
        let body = extract_article(&html, &path);
        module.push_str(&format!(
            "pub const {}: &str = {};\n",
            constant_name(page),
            rust_literal(body)
        ));
    }

    let mut stylesheet = String::new();
    for relative in ["_static/pygments.css", "_static/cosmolkit.css"] {
        let path = output.join(relative);
        if let Ok(css) = fs::read_to_string(&path) {
            stylesheet.push_str(&css);
            stylesheet.push('\n');
        }
    }
    module.push_str(&format!(
        "pub const STYLESHEET: &str = {};\n",
        rust_literal(&stylesheet)
    ));
    module
}

fn constant_name(page: &str) -> String {
    page.replace('-', "_").to_ascii_uppercase()
}

fn extract_article<'a>(html: &'a str, path: &Path) -> &'a str {
    let start_marker = "<article role=\"main\" id=\"furo-main-content\">";
    let start = html
        .find(start_marker)
        .unwrap_or_else(|| panic!("compiled Sphinx page {} has no article", path.display()));
    let content_start = start + start_marker.len();
    let end = html[content_start..]
        .find("</article>")
        .map(|offset| content_start + offset)
        .unwrap_or_else(|| panic!("compiled Sphinx page {} has no article end", path.display()));
    &html[content_start..end]
}

fn rust_literal(value: &str) -> String {
    let mut hashes = 1usize;
    while value.contains(&format!("\"{}", "#".repeat(hashes))) {
        hashes += 1;
    }
    let marker = "#".repeat(hashes);
    format!("r{marker}\"{value}\"{marker}")
}
