[package]
name = "cosmolkit-core-old"
description = "Frozen pre-redesign COSMolKit core kept only as a reference implementation"
keywords = ["cheminformatics", "molecule", "smiles", "sdf", "bioinformatics"]
categories = ["science", "parser-implementations", "data-structures"]
repository = "https://github.com/cosmol-studio/COSMolKit"
homepage = "https://github.com/cosmol-studio/COSMolKit"
documentation = "https://docs.rs/cosmolkit"
readme = "../../README.md"
license = "MIT OR Apache-2.0"
version.workspace = true
edition.workspace = true

[lib]
name = "cosmolkit_core_old"
path = "src/lib.rs"

[features]
topology-contract-tests = []

[dependencies]
console = "0.16"
cosmolkit-macros = { path = "../cosmolkit-macros", version = "0.2.0" }
glam = "0.32.1"
indicatif = "0.18"
rayon = "1.12.0"
resvg = "0.47.0"
thiserror = "2.0.18"
tiny-skia = "0.12.0"
usvg = "0.47"

[dev-dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
