[package]
name = "cosmolkit-search"
description = "SMARTS, query planning, matching, and MCS over COSMolKit model values"
keywords = ["cheminformatics", "smarts", "substructure", "search"]
categories = ["science", "algorithms"]
repository.workspace = true
homepage.workspace = true
license.workspace = true
version.workspace = true
edition.workspace = true
readme = "../cosmolkit/README.md"
documentation = "https://docs.rs/cosmolkit"

[dependencies]
cosmolkit-cx = { version = "0.5.0-rc.1", path = "../cosmolkit-cx" }
cosmolkit-model = { version = "0.5.0-rc.1", path = "../cosmolkit-model" }
cosmolkit-types = { version = "0.5.0-rc.1", path = "../cosmolkit-types" }
