//! Canonical embedding owner integration with complete report and failure semantics.
use crate::{EmbedParams, Molecule};
#[test]
fn conformer_reexports_all_operations_reports_and_atomic_failures() {
    let mut p = EmbedParams::dg();
    p.random_seed = 42;
    p.track_failures = true;
    let m = Molecule::from_smiles("C").unwrap();
    let out = m.with_3d_conformer().unwrap();
    assert_eq!(out.num_3d_conformers(), 1);
    assert_eq!(m.num_3d_conformers(), 0);
    let m = Molecule::from_smiles("C").unwrap();
    let out = m.with_3d_conformer_with_params(&p).unwrap();
    assert_eq!(out.num_3d_conformers(), 1);
    assert_eq!(m.num_3d_conformers(), 0);
    let m = Molecule::from_smiles("C").unwrap();
    let out = m.embed_3d_conformer_().unwrap();
    assert_eq!(m.num_3d_conformers(), 1);
    let m = Molecule::from_smiles("C").unwrap();
    let out = m.embed_3d_conformer_with_params_(&p).unwrap();
    assert_eq!(m.num_3d_conformers(), 1);
    let m = Molecule::from_smiles("C").unwrap();
    let out = m.with_3d_conformer_result().unwrap();
    assert_eq!(out.molecule().num_3d_conformers(), 1);
    assert_eq!(out.conf_id(), 0);
    assert!(out.ok());
    assert_eq!(m.num_3d_conformers(), 0);
    let m = Molecule::from_smiles("C").unwrap();
    let out = m.with_3d_conformer_result_with_params(&p).unwrap();
    assert_eq!(out.molecule().num_3d_conformers(), 1);
    assert_eq!(out.params().failures().len(), 12);
    assert_eq!(out.conf_id(), 0);
    assert!(out.ok());
    assert_eq!(m.num_3d_conformers(), 0);
    let m = Molecule::from_smiles("C").unwrap();
    let out = m.embed_3d_conformer_result_().unwrap();
    assert_eq!(out.molecule().num_3d_conformers(), 1);
    assert_eq!(out.conf_id(), 0);
    assert!(out.ok());
    assert_eq!(m.num_3d_conformers(), 1);
    let m = Molecule::from_smiles("C").unwrap();
    let out = m.embed_3d_conformer_result_with_params_(&p).unwrap();
    assert_eq!(out.molecule().num_3d_conformers(), 1);
    assert_eq!(out.params().failures().len(), 12);
    assert_eq!(out.conf_id(), 0);
    assert!(out.ok());
    assert_eq!(m.num_3d_conformers(), 1);
    let m = Molecule::from_smiles("C").unwrap();
    let out = m.with_3d_conformers(2).unwrap();
    assert_eq!(out.num_3d_conformers(), 2);
    assert_eq!(m.num_3d_conformers(), 0);
    let m = Molecule::from_smiles("C").unwrap();
    let out = m.with_3d_conformers_with_params(2, &p).unwrap();
    assert_eq!(out.num_3d_conformers(), 2);
    assert_eq!(m.num_3d_conformers(), 0);
    let m = Molecule::from_smiles("C").unwrap();
    let out = m.embed_3d_conformers_(2).unwrap();
    assert_eq!(m.num_3d_conformers(), 2);
    let m = Molecule::from_smiles("C").unwrap();
    let out = m.embed_3d_conformers_with_params_(2, &p).unwrap();
    assert_eq!(m.num_3d_conformers(), 2);
    let m = Molecule::from_smiles("C").unwrap();
    let out = m.with_3d_conformers_result(2).unwrap();
    assert_eq!(out.molecule().num_3d_conformers(), 2);
    assert_eq!(out.conf_ids(), [0, 1]);
    assert_eq!(out.requested_num_confs(), 2);
    assert_eq!(out.generated_count(), 2);
    assert_eq!(m.num_3d_conformers(), 0);
    let m = Molecule::from_smiles("C").unwrap();
    let out = m.with_3d_conformers_result_with_params(2, &p).unwrap();
    assert_eq!(out.molecule().num_3d_conformers(), 2);
    assert_eq!(out.params().failures().len(), 12);
    assert_eq!(out.conf_ids(), [0, 1]);
    assert_eq!(out.requested_num_confs(), 2);
    assert_eq!(out.generated_count(), 2);
    assert_eq!(m.num_3d_conformers(), 0);
    let m = Molecule::from_smiles("C").unwrap();
    let out = m.embed_3d_conformers_result_(2).unwrap();
    assert_eq!(out.molecule().num_3d_conformers(), 2);
    assert_eq!(out.conf_ids(), [0, 1]);
    assert_eq!(out.requested_num_confs(), 2);
    assert_eq!(out.generated_count(), 2);
    assert_eq!(m.num_3d_conformers(), 2);
    let m = Molecule::from_smiles("C").unwrap();
    let out = m.embed_3d_conformers_result_with_params_(2, &p).unwrap();
    assert_eq!(out.molecule().num_3d_conformers(), 2);
    assert_eq!(out.params().failures().len(), 12);
    assert_eq!(out.conf_ids(), [0, 1]);
    assert_eq!(out.requested_num_confs(), 2);
    assert_eq!(out.generated_count(), 2);
    assert_eq!(m.num_3d_conformers(), 2);
    assert!(p.failures().is_empty());
    let m = Molecule::from_smiles("CC").unwrap();
    let matrix = m.dg_bounds_matrix().unwrap();
    assert_eq!(matrix.len(), 2);
    assert!(matrix[0][1] > matrix[1][0]);
    assert_eq!(m.num_3d_conformers(), 0);
    let empty = Molecule::new();
    assert!(empty.embed_3d_conformer_with_params_(&p).is_err());
    assert_eq!(empty.num_3d_conformers(), 0);
}
