[package]
name = "cosmolkit-stereo"
description = "Stereo enumeration and high-level stereochemistry algorithms"
keywords = ["cheminformatics", "stereochemistry", "isomers"]
categories = ["science", "algorithms"]
repository.workspace = true
homepage.workspace = true
license.workspace = true
version.workspace = true
edition.workspace = true
readme = "../cosmolkit/README.md"
documentation = "https://docs.rs/cosmolkit"

[features]
default = ["enumeration"]
enumeration = ["dep:cosmolkit-smiles", "dep:cosmolkit-conformer", "dep:num-bigint"]

[dependencies]
cosmolkit-core = { version = "0.5.0", path = "../cosmolkit-core" }
cosmolkit-model = { version = "0.5.0", path = "../cosmolkit-model" }
cosmolkit-types = { version = "0.5.0", path = "../cosmolkit-types" }
thiserror = "2.0.18"
cosmolkit-smiles = { version = "0.5.0", path = "../cosmolkit-smiles", optional = true }
cosmolkit-conformer = { version = "0.5.0", path = "../cosmolkit-conformer", optional = true }
num-bigint = { version = "0.4.8", optional = true }
