[package]
name = "cosmolkit-stereo"
description = "Stereo enumeration and high-level stereochemistry algorithms"
keywords = ["cheminformatics", "stereochemistry", "isomers"]
categories = ["science", "algorithms"]
repository.workspace = true
homepage.workspace = true
license.workspace = true
version.workspace = true
edition.workspace = true
readme = "../cosmolkit/README.md"
documentation = "https://docs.rs/cosmolkit"

[dependencies]
cosmolkit-core = { version = "0.5.0-rc.4", path = "../cosmolkit-core" }
cosmolkit-model = { version = "0.5.0-rc.4", path = "../cosmolkit-model" }
cosmolkit-types = { version = "0.5.0-rc.4", path = "../cosmolkit-types" }
thiserror = "2.0.18"
