[package]
name = "cosmolkit-descriptors"
description = "Molecular descriptors over COSMolKit detached model values"
keywords = ["cheminformatics", "descriptors", "molecular-properties"]
categories = ["science", "data-structures"]
repository.workspace = true
homepage.workspace = true
license.workspace = true
version.workspace = true
edition.workspace = true
readme = "../cosmolkit/README.md"
documentation = "https://docs.rs/cosmolkit"

[dependencies]
cosmolkit-model = { version = "0.5.0-rc.1", path = "../cosmolkit-model" }
thiserror = "2.0.18"
