[package]
name = "cosmolkit"
description = "Rust-native cheminformatics and structural biology toolkit for molecules, SMILES, SDF, molecular graphs, conformers, and AI-ready workflows"
keywords = ["cheminformatics", "molecule", "smiles", "sdf", "bioinformatics"]
categories = ["science", "parser-implementations", "data-structures"]
repository = "https://github.com/cosmol-studio/COSMolKit"
homepage = "https://tools.cosmol.org/"
documentation = "https://docs.rs/cosmolkit"
readme = "./README.md"
license.workspace = true
version.workspace = true
edition.workspace = true
autoexamples = false

[lib]
name = "cosmolkit"
path = "src/lib.rs"

[package.metadata.docs.rs]
features = ["full"]
no-default-features = true

[features]
default = []
full = []
batch = []
hydrogens = []
confseq = []
depict = []
descriptors = ["dep:cosmolkit-descriptors"]
fingerprints = []
hashing = []
inchi = []
io = []
serialization = []
stereoisomers = []

[dependencies]
cosmolkit-model = { version = "0.5.0-rc.1", path = "../cosmolkit-model" }
cosmolkit-macros = { version = "0.5.0-rc.1", path = "../cosmolkit-macros" }
cosmolkit-descriptors = { version = "0.5.0-rc.1", path = "../cosmolkit-descriptors", optional = true }
