[package]
name = "cosmolkit-reaction"
description = "Detached source-backed reaction templates and execution"
repository.workspace = true
homepage.workspace = true
license.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
cosmolkit-types = { version = "0.5.0-rc.20", path = "../cosmolkit-types" }
cosmolkit-model = { version = "0.5.0-rc.20", path = "../cosmolkit-model" }
cosmolkit-core = { version = "0.5.0-rc.20", path = "../cosmolkit-core" }
cosmolkit-search = { version = "0.5.0-rc.20", path = "../cosmolkit-search" }
cosmolkit-smiles = { version = "0.5.0-rc.20", path = "../cosmolkit-smiles" }
cosmolkit-cx = { version = "0.5.0-rc.20", path = "../cosmolkit-cx" }
thiserror = "2"
