[package]
name = "cosmolkit-model"
description = "Shared concrete molecular value model for COSMolKit algorithms"
keywords = ["chemistry", "molecule", "graph", "cheminformatics"]
categories = ["science", "data-structures"]
repository.workspace = true
homepage.workspace = true
license.workspace = true
version.workspace = true
edition.workspace = true
readme = "../cosmolkit/README.md"
documentation = "https://docs.rs/cosmolkit"

[dependencies]
cosmolkit-types = { version = "0.5.0-rc.1", path = "../cosmolkit-types" }
thiserror = "2.0.18"
