[package]
name = "cosmolkit-wasm"
description = "Binding-facing WASM API for COSMolKit"
keywords = ["cheminformatics", "wasm", "webassembly", "molecule"]
categories = ["science", "wasm"]
repository = "https://github.com/cosmol-studio/COSMolKit"
homepage = "https://tools.cosmol.org/"
documentation = "https://docs.rs/cosmolkit-wasm"
license.workspace = true
version = "0.5.0-rc.13"
edition.workspace = true
publish = false

[lib]
name = "cosmolkit_wasm"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[features]
default = ["full"]
full = [
    "aromaticity",
    "depict",
    "descriptors",
    "hydrogens",
    "io",
    "kekulize",
    "radicals",
    "rings",
    "sanitize",
    "smiles",
    "valence",
]
aromaticity = ["cosmolkit/cap-aromaticity"]
depict = ["cosmolkit/cap-depict"]
descriptors = ["cosmolkit/cap-descriptors"]
hydrogens = ["cosmolkit/cap-hydrogens"]
io = ["cosmolkit/cap-io"]
kekulize = ["cosmolkit/cap-kekulize"]
radicals = ["cosmolkit/cap-radicals"]
rings = ["cosmolkit/cap-rings"]
sanitize = ["cosmolkit/cap-sanitize"]
smiles = ["cosmolkit/cap-smiles"]
valence = ["cosmolkit/cap-valence"]

[dependencies]
cosmolkit = { version = "0.5.0-rc.13", path = "../crates/cosmolkit", default-features = false }
