[package]
name = "cosmolkit-wasm"
description = "Binding-facing WASM API for COSMolKit"
keywords = ["cheminformatics", "wasm", "webassembly", "molecule"]
categories = ["science", "wasm"]
repository = "https://github.com/cosmol-studio/COSMolKit"
homepage = "https://tools.cosmol.org/"
documentation = "https://docs.rs/cosmolkit-wasm"
license.workspace = true
version = "0.5.0-rc.15"
edition.workspace = true
publish = false

[lib]
name = "cosmolkit_wasm"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[features]
default = ["full"]
full = [
    "cosmolkit/full",
    "alignment",
    "batch",
    "bio",
    "conformer",
    "fingerprints",
    "forcefields",
    "hashing",
    "aromaticity",
    "depict",
    "descriptors",
    "hydrogens",
    "io",
    "kekulize",
    "matrices",
    "radicals",
    "reaction",
    "rings",
    "sanitize",
    "search",
    "serialization",
    "smiles",
    "valence",
    "core",
    "inchi",
]
core = ["cosmolkit/core", "smiles", "hydrogens", "valence", "radicals", "rings", "matrices", "stereo", "kekulize", "aromaticity", "sanitize", "io", "depict"]
alignment = ["cosmolkit/cap-alignment", "search"]
batch = ["cosmolkit/batch", "io"]
bio = ["cosmolkit/cap-bio"]
conformer = ["cosmolkit/conformer", "forcefields", "alignment", "io"]
fingerprints = ["cosmolkit/fingerprints", "hashing", "io", "search", "stereo"]
forcefields = ["cosmolkit/forcefields", "search"]
hashing = ["cosmolkit/cap-hashing", "search", "stereo"]
aromaticity = ["cosmolkit/cap-aromaticity"]
depict = ["cosmolkit/depict", "search"]
descriptors = ["cosmolkit/descriptors", "search"]
hydrogens = ["cosmolkit/cap-hydrogens"]
io = ["cosmolkit/cap-io", "search", "depict"]
inchi = ["cosmolkit/inchi"]
kekulize = ["cosmolkit/cap-kekulize"]
matrices = ["cosmolkit/cap-matrices"]
radicals = ["cosmolkit/cap-radicals"]
reaction = ["cosmolkit/reaction", "search"]
rings = ["cosmolkit/cap-rings"]
sanitize = ["cosmolkit/cap-sanitize"]
search = ["cosmolkit/search", "smiles"]
serialization = ["cosmolkit/serialization", "io"]
smiles = ["cosmolkit/cap-smiles"]
stereo = ["cosmolkit/cap-stereo"]
valence = ["cosmolkit/cap-valence"]

[dependencies]
cosmolkit = { version = "0.5.0-rc.15", path = "../crates/cosmolkit", default-features = false }
