[package]
name = "cosmolkit-core"
description = "Detached source-backed chemistry algorithms for the COSMolKit migration"
keywords = ["cheminformatics", "molecule", "chemistry"]
categories = ["science", "data-structures"]
repository.workspace = true
homepage.workspace = true
license.workspace = true
version.workspace = true
edition.workspace = true
readme = "../cosmolkit/README.md"
documentation = "https://docs.rs/cosmolkit"

[lib]
name = "cosmolkit_core"
path = "src/lib.rs"

[dependencies]
cosmolkit-model = { version = "0.5.0-rc.1", path = "../cosmolkit-model" }
