import { Molecule, AlignmentParameters, BestAlignmentParameters, CoordinateRmsdParameters, AllConformerRmsdParameters, ConformerAlignmentParameters, AlignmentResult, AlignmentTransform, ConformerRmsd, ConformerAlignmentReport, AlignmentError } from "cosmolkit-generated";
declare const probe: Molecule;
declare const reference: Molecule;
const params = new AlignmentParameters();
const best = new BestAlignmentParameters();
const coordinate = new CoordinateRmsdParameters();
const all = new AllConformerRmsdParameters();
const conformers = new ConformerAlignmentParameters();
const a: AlignmentResult = probe.alignmentTransformTo(reference);
const b: AlignmentResult = probe.alignmentTransformToWithParams(reference, params);
const c: AlignmentResult = probe.bestAlignmentTo(reference);
const d: AlignmentResult = probe.bestAlignmentToWithParams(reference, best);
const e: number = probe.bestRmsdTo(reference);
const f: number = probe.bestRmsdToWithParams(reference, best);
const g: number = probe.coordinateRmsdTo(reference);
const h: number = probe.coordinateRmsdToWithParams(reference, coordinate);
const i: ConformerRmsd[] = probe.allConformerBestRmsds();
const j: ConformerRmsd[] = probe.allConformerBestRmsdsWithParams(all);
const k: [Molecule, AlignmentResult] = probe.withAlignmentTo(reference);
const l: [Molecule, AlignmentResult] = probe.withAlignmentToWithParams(reference, params);
const m: AlignmentResult = probe.alignTo(reference);
const n: AlignmentResult = probe.alignToWithParams(reference, params);
const o: [Molecule, ConformerAlignmentReport] = probe.withAlignedConformers();
const p: [Molecule, ConformerAlignmentReport] = probe.withAlignedConformersWithParams(conformers);
const q: ConformerAlignmentReport = probe.alignConformers();
const r: ConformerAlignmentReport = probe.alignConformersWithParams(conformers);
const transform: AlignmentTransform = a.transform();
const matrix: number[][] = transform.matrix();
const rmsds: Float64Array = q.rmsds();
declare const error: AlignmentError;
const domain: string = error.domain;
const kind: string = error.kind;
void [b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,r,matrix,rmsds,domain,kind];
