import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import test from 'node:test';import {pathToFileURL} from 'node:url';
const b=await import(pathToFileURL(process.env.COSMOLKIT_WASM_MODULE).href);b.initSync({module:readFileSync(process.env.COSMOLKIT_WASM_BINARY)});
const families=[['atomPairFingerprint','Fingerprint','onBits'],['atomPairSparseFingerprint','SparseBitFingerprint','onBits'],['atomPairCountFingerprint','SparseCountFingerprint32','nonzeroElements'],['atomPairSparseCountFingerprint','SparseCountFingerprint','nonzeroElements']];
const fields=['atomCounts','atomToBits','bitInfoMap','bitPaths','atomsPerBit'];
function allocated(){const out=b.FingerprintAdditionalOutput.new();for(const name of fields)out['allocate'+name[0].toUpperCase()+name.slice(1)]();return out;}
function snapshot(out){return fields.map(k=>out[k]());}
test('All scalar AtomPair calls match batch source outputs with defaults and explicit parameters',()=>{
 for(const text of ['CCO','c1ccncc1','F[C@](Cl)(Br)I']){const m=b.Molecule.fromSmiles(text),p=new b.AtomPairFingerprintParams(),batch=b.MoleculeBatch.fromSmilesList([text]),before=m.toSmiles();for(const [name,Class,read] of families){const f=m[name](),explicit=m[name+'WithParams'](p,null);assert.ok(f instanceof b[Class]);assert.deepEqual(f[read](),explicit[read]());const batchName={atomPairFingerprint:'fingerprintAtomPairList',atomPairSparseFingerprint:'fingerprintAtomPairSparseBitsList',atomPairCountFingerprint:'fingerprintAtomPairCountList',atomPairSparseCountFingerprint:'fingerprintAtomPairSparseCountList'}[name];assert.deepEqual(f[read](),batch[batchName]()[0][read]());}assert.equal(m.toSmiles(),before);assert.equal(p.generator.fpSize,2048);}
});
test('All twelve additional-output methods preserve allocation states, mutable reuse and detached exact-width snapshots',()=>{
 for(const out of [new b.FingerprintAdditionalOutput(),b.FingerprintAdditionalOutput.new(),b.FingerprintAdditionalOutput.default()]){assert.deepEqual(snapshot(out),[null,null,null,null,null]);for(const name of fields){out['allocate'+name[0].toUpperCase()+name.slice(1)]();const v=out[name]();if(name==='atomCounts'||name==='atomToBits')assert.deepEqual(v,[]);else assert.deepEqual(v,new Map());}}
 const m=b.Molecule.fromSmiles('CCO'),p=new b.AtomPairFingerprintParams(),out=allocated();for(const [name,Class] of families){assert.ok(m[name+'WithParams'](p,out) instanceof b[Class]);assert.equal(out.atomCounts().length,3);assert.equal(out.atomToBits().length,3);assert.ok(out.bitInfoMap() instanceof Map);assert.ok(out.bitPaths() instanceof Map);assert.ok(out.atomsPerBit() instanceof Map);for(const key of out.bitInfoMap().keys())assert.equal(typeof key,'bigint');for(const key of out.atomToBits().flat())assert.equal(typeof key,'bigint');}
 const before=snapshot(out),a=out.atomCounts(),rows=out.atomToBits(),info=out.bitInfoMap();a[0]=999;rows[0].push(999n);info.set(999n,[[99,99]]);assert.deepEqual(snapshot(out),before);out.allocateAtomCounts();assert.deepEqual(out.atomCounts(),[]);const sparse=m.atomPairSparseCountFingerprintWithParams(p,out);const entries=sparse.nonzeroElements();out.free();p.free();m.free();assert.ok(entries instanceof Map);assert.equal(a[0],999);
});
test('AtomPair selected atoms, ignored atoms, custom invariants and failure chains reach the canonical owner',()=>{
 const m=b.Molecule.fromSmiles('CCO');const empty=new b.AtomPairFingerprintParams(null,[]);assert.equal(m.atomPairFingerprintWithParams(empty,null).onBits().length,0);const selected=new b.AtomPairFingerprintParams(null,[0],null,[33,34,35]);assert.ok(m.atomPairSparseCountFingerprintWithParams(selected,null).nonzeroElements().size>0);const ignored=new b.AtomPairFingerprintParams(null,null,[0,1,2]);assert.equal(m.atomPairSparseCountFingerprintWithParams(ignored,null).nonzeroElements().size,0);
 for(const [name] of families){assert.throws(()=>m[name+'WithParams'](new b.AtomPairFingerprintParams(),undefined),TypeError);assert.throws(()=>m[name+'WithParams'](new b.AtomPairFingerprintParams(),{}),TypeError);const raw=b.Molecule.fromSmilesWithParams('CC',new b.SmilesParseParams(false,undefined,undefined,undefined,false));assert.throws(()=>raw[name](),e=>{assert.equal(e.name,'AtomPairReadError');assert.equal(e.kind,'Preparation');assert.ok(e.detail instanceof b.AtomPairReadError);assert.equal(e.cause.kind,'MissingPreparedValence');assert.ok(e.cause.detail instanceof b.FingerprintPreparationError);return true;});}
 const zero=new b.AtomPairFingerprintParams(new b.AtomPairParams(undefined,undefined,undefined,undefined,undefined,0));assert.throws(()=>m.atomPairFingerprintWithParams(zero,null),e=>e.kind==='Generator'&&e.cause.cause.kind==='InvalidArguments'&&e.cause.cause.reason==='Count bounds size is >= fingerprint size');const invalid=new b.AtomPairFingerprintParams(null,[99]);assert.deepEqual(m.atomPairFingerprintWithParams(invalid,null).onBits(),[]);assert.equal(m.toSmiles(),'CCO');
});
