import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import { pathToFileURL } from "node:url";
const b = await import(pathToFileURL(process.env.COSMOLKIT_WASM_MODULE).href);
b.initSync({ module: readFileSync(process.env.COSMOLKIT_WASM_BINARY) });

test("complete SMILES parser fields remain frozen and string maps are copied", () => {
    const defaults = new b.SmilesParseParams();
    for (const field of ["sanitize","allowCxsmiles","strictCxsmiles","parseName","removeHs"]) assert.equal(defaults[field],true);
    assert.equal(defaults.skipCleanup,false);assert.equal(defaults.debugParse,false);
    assert.deepEqual([...defaults.replacements],[]);
    const replacements = new Map([["{R}","C"],["__proto__","N"]]);
    const params = new b.SmilesParseParams(true,true,true,true,false,false,false,replacements);
    replacements.set("{R}","O");assert.equal(params.replacements.get("{R}"),"C");
    const copy = params.replacements;copy.set("{R}","N");assert.equal(params.replacements.get("{R}"),"C");
    assert.equal(params.replacements.get("__proto__"),"N");
    assert.throws(() => { params.sanitize = false; },TypeError);
    const value = b.Molecule.fromSmilesWithParams("{R}",params);assert.equal(value.toSmiles(),"C");
    assert.equal(b.Molecule.fromSmiles("CCO").toSmiles(),"CCO");
    assert.throws(() => b.Molecule.fromSmiles("["),e => e instanceof Error && e.domain === "smiles" && e.kind === "Parse" && e.detail instanceof b.SmilesError);
    assert.throws(() => new b.SmilesParseParams("true"),TypeError);
    assert.throws(() => new b.SmilesParseParams(undefined,undefined,undefined,undefined,undefined,undefined,undefined,{x:7}),TypeError);
    value.free();params.free();defaults.free();
});

test("all batch foundation operations retain ordered rows, nulls and configuration value semantics", () => {
    const parse = new b.SmilesParseParams(), params = new b.BatchParams(b.BatchErrorMode.KeepErrors);
    assert.equal(new b.BatchParams().errors,null);
    assert.equal(params.nJobs,null);assert.equal(params.progressBar,null);
    assert.throws(() => { params.nJobs = 3; },TypeError);
    const batch = b.MoleculeBatch.fromSmilesListWithParams(["CCO","[","O","C("],parse,params);
    const oneWorkerParams=new b.BatchParams(b.BatchErrorMode.KeepErrors,1);
    const oneWorkerBatch=b.MoleculeBatch.fromSmilesListWithParams(["CCO","[","O","C("],parse,oneWorkerParams);
    assert.deepEqual(oneWorkerBatch.validMask(),batch.validMask());
    oneWorkerBatch.free();oneWorkerParams.free();
    assert.equal(batch.len(),4);assert.equal(batch.isEmpty(),false);
    assert.deepEqual(batch.validMask(),[true,false,true,false]);assert.deepEqual(batch.invalidMask(),[false,true,false,true]);
    assert.equal(batch.validCount(),2);assert.equal(batch.invalidCount(),2);
    const errors = batch.errors();assert.deepEqual(errors.map(e => e.index()),[1,3]);
    assert.ok(errors[0].message().length > 0);assert.equal(errors[0].operation(),"batch.from_smiles_list");
    const details=errors[0].asDict();
    assert.deepEqual(details,{index:1,operation:errors[0].operation(),message:errors[0].message()});
    assert.equal(typeof details.index,"number");assert.equal(Array.isArray(details),false);
    assert.deepEqual(JSON.parse(JSON.stringify(details)),details);
    details.index=-1;details.message="changed";
    assert.deepEqual(errors[0].asDict(),{index:1,operation:errors[0].operation(),message:errors[0].message()});
    assert.equal(errors[0].cause().domain,"smiles");assert.equal(errors[0].cause().kind,"Parse");
    const values = batch.toList();assert.deepEqual(values.map(v => v === null),[false,true,false,true]);assert.equal(values[0].numAtoms(),3);
    assert.equal(batch.parallelJobs(),null);assert.equal(batch.progressBar(),null);
    const configured = batch.withParallelJobs(2).withProgressBar(false);
    assert.equal(configured.parallelJobs(),2);assert.equal(configured.progressBar(),false);
    assert.equal(batch.parallelJobs(),null);assert.equal(batch.progressBar(),null);
    assert.equal(configured.withParallelJobs(null).parallelJobs(),null);
    assert.equal(configured.withProgressBar(null).progressBar(),null);
    assert.equal(batch.withValidRecords().len(),2);
    assert.throws(() => batch.withParallelJobs(0),e => e instanceof Error && e.domain === "batch" && e.recordErrors[0].operation() === "n_jobs");
    for (const n of [-1,1.5,4294967296,NaN,Infinity]) assert.throws(() => batch.withParallelJobs(n),RangeError);
    assert.throws(() => batch.withProgressBar("false"),TypeError);
    assert.throws(() => b.MoleculeBatch.fromSmilesList(["CCO","[","O","C("]),e => {
        assert.equal(e.name,"BatchValidationError");assert.equal(e.domain,"batch");assert.equal(e.errors,2);assert.equal(e.reason,null);
        assert.deepEqual(e.recordErrors.map(row => row.index()),[1,3]);assert.ok(e.detail instanceof b.BatchValidationError);
        assert.equal(e.cause.index,1);assert.equal(e.cause.cause.domain,"smiles");assert.equal(e.cause.cause.kind,"Parse");return true;
    });
    assert.equal(b.MoleculeBatch.fromSmilesList([]).isEmpty(),true);
    assert.throws(() => b.MoleculeBatch.fromSmilesList(["C",77]),TypeError);
});

test("fromRecords borrows classes and returns independent Molecule values", () => {
    const parse = new b.SmilesParseParams(), params = new b.BatchParams(b.BatchErrorMode.KeepErrors);
    const error = b.MoleculeBatch.fromSmilesListWithParams(["["],parse,params).errors()[0];
    const source = b.Molecule.fromSmilesWithSanitize("C1=CC=CC=C1",false);
    const record = b.BatchRecord.molecule(source), failed = b.BatchRecord.error(error);
    assert.equal(record.errorValue(),null);assert.equal(failed.moleculeValue(),null);
    const batch = b.MoleculeBatch.fromRecords([record,failed],b.BatchErrorMode.KeepErrors);
    assert.equal(source.numAtoms(),6);assert.equal(record.moleculeValue().numAtoms(),6);assert.equal(failed.errorValue().index(),0);
    source.assignAromaticity();assert.equal(source.toSmiles(),"c1ccccc1");
    assert.equal(record.moleculeValue().toSmiles(),"C1=CC=CC=C1");
    const extracted = batch.toList()[0];extracted.assignAromaticity();assert.equal(extracted.toSmiles(),"c1ccccc1");
    assert.equal(batch.toList()[0].toSmiles(),"C1=CC=CC=C1");assert.deepEqual(batch.validMask(),[true,false]);
    assert.throws(() => b.MoleculeBatch.fromRecords([failed],b.BatchErrorMode.Strict),e => e.errors === 1);
    assert.equal(failed.errorValue().index(),0);
    assert.throws(() => b.MoleculeBatch.fromRecords([{}],b.BatchErrorMode.Strict));
    const freed = b.BatchRecord.molecule(source);freed.free();
    assert.throws(() => b.MoleculeBatch.fromRecords([freed],b.BatchErrorMode.Strict));
    assert.equal(b.MoleculeBatch.fromRecords([],b.BatchErrorMode.Strict).isEmpty(),true);
});
