import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import test from 'node:test';import {pathToFileURL} from 'node:url';
const b=await import(pathToFileURL(process.env.COSMOLKIT_WASM_MODULE).href);b.initSync({module:readFileSync(process.env.COSMOLKIT_WASM_BINARY)});
const batch=()=>b.MoleculeBatch.fromSmilesListWithParams(['CCO','[','O'],new b.SmilesParseParams(),new b.BatchParams(b.BatchErrorMode.KeepErrors));
const causes=e=>{const values=[];while(e){values.push(e);e=e.cause;}return values;};
test('Morgan full generator and call parameter fields preserve source defaults and detached immutable values',()=>{
 const fields=['radius','includeChirality','useBondTypes','includeRingMembership','onlyNonzeroInvariants','includeRedundantEnvironments','fpSize','countSimulation','bitsPerFeature'],defaults=new b.MorganParams();assert.deepEqual(fields.map(k=>defaults[k]),[3,false,true,true,false,false,2048,false,1]);assert.deepEqual(defaults.countBounds,[1,2,4,8]);
 const bounds=[1,3],custom=new b.MorganParams(2,true,false,false,true,true,128,true,bounds,2);bounds.push(8);assert.deepEqual(fields.map(k=>custom[k]),[2,true,false,false,true,true,128,true,2]);assert.deepEqual(custom.countBounds,[1,3]);assert.deepEqual(new b.MorganParams(undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,[]).countBounds,[]);assert.equal(custom.withJson(custom.toJson()).toJson(),custom.toJson());assert.equal(typeof custom.infoString(),'string');assert.throws(()=>defaults.withJson('{'),e=>e.kind==='Parse'&&e.detail instanceof b.FingerprintJsonError);
 const roots=[0,2],selection=b.MorganInvariants.features(),options=new b.MorganFingerprintParams(custom,roots,[],[6,6,8],[],7,selection);roots.push(1);assert.deepEqual(options.fromAtoms,[0,2]);assert.deepEqual(options.ignoreAtoms,[]);assert.deepEqual(options.customAtomInvariants,[6,6,8]);assert.deepEqual(options.customBondInvariants,[]);assert.equal(options.conformerId,7);assert.equal(options.generator.radius,2);assert.ok(options.invariants instanceof b.MorganInvariants);assert.equal(custom.radius,2);assert.ok(selection instanceof b.MorganInvariants);
 const call=b.MorganCallParams.new([0],[],[1,2,3],[4,5],-2);assert.deepEqual([call.fromAtoms,call.ignoreAtoms,call.customAtomInvariants,call.customBondInvariants,call.conformerId],[[0],[],[1,2,3],[4,5],-2]);const implicit=new b.MorganCallParams();assert.deepEqual([implicit.fromAtoms,implicit.ignoreAtoms,implicit.customAtomInvariants,implicit.customBondInvariants,implicit.conformerId],[null,null,null,null,-1]);
 const p=new b.MorganFingerprintParams();assert.deepEqual([p.fromAtoms,p.ignoreAtoms,p.customAtomInvariants,p.customBondInvariants,p.conformerId],[null,null,null,null,-1]);assert.equal(p.generator.radius,3);
 assert.throws(()=>{custom.radius=0;},TypeError);assert.throws(()=>new b.MorganParams(-1),RangeError);assert.throws(()=>new b.MorganParams(undefined,'false'),TypeError);assert.throws(()=>new b.MorganFingerprintParams({}),TypeError);assert.throws(()=>new b.MorganCallParams(null,null,null,null,2147483648),RangeError);
});
test('all six batch Morgan calls preserve radius-two defaults, null rows, provenance and missing output errors',()=>{
 const value=batch(),generator=new b.MorganParams(2),options=new b.MorganFingerprintParams(generator),query=new b.BatchQueryParams(),call=new b.MorganCallParams(),dense=value.fingerprintMorganList(),explicit=value.fingerprintMorganListWithParams(options,query),generated=value.fingerprintMorganListWithGeneratorParams(generator,null,null,call,query);assert.equal(dense.length,3);assert.equal(dense[1],null);assert.ok(dense[0] instanceof b.Fingerprint);assert.deepEqual(dense.map(v=>v?.onBits()??null),explicit.map(v=>v?.onBits()??null));assert.deepEqual(dense.map(v=>v?.onBits()??null),generated.map(v=>v?.onBits()??null));
 const outputs=[value.fingerprintMorganWithOutputList(),value.fingerprintMorganWithOutputListWithParams(options,true,query),value.fingerprintMorganWithOutputListWithGeneratorParams(generator,null,null,call,true,query)];for(const output of outputs){assert.equal(output[1],null);assert.ok(output[0] instanceof b.BatchFingerprintOutput);assert.deepEqual(output[0].fingerprint().onBits(),dense[0].onBits());const extra=output[0].additionalOutput();assert.equal(extra.atomCounts().length,3);assert.equal(extra.atomToBits().length,3);assert.ok(extra.bitInfoMap() instanceof Map);assert.equal(extra.bitPaths(),null);assert.ok(extra.atomsPerBit() instanceof Map);const counts=extra.atomCounts();counts[0]=999;assert.notEqual(extra.atomCounts()[0],999);}
 for(const result of [value.fingerprintMorganWithOutputListWithParams(options,false,query)[0],value.fingerprintMorganWithOutputListWithGeneratorParams(generator,null,null,call,false,query)[0]])assert.throws(()=>result.additionalOutput(),e=>e.kind==='MissingAdditionalOutput'&&e.fingerprintKind==='Morgan'&&e.detail instanceof b.BatchFingerprintOutputError);
 assert.deepEqual(b.MoleculeBatch.fromSmilesList([]).fingerprintMorganList(),[]);assert.deepEqual(value.validMask(),[true,false,true]);
});
test('Morgan provider alternatives retain copied query patterns and borrowed provider lifetime',()=>{
 const value=b.MoleculeBatch.fromSmilesList(['CCO']),options=new b.MorganParams(0),call=new b.MorganCallParams(),query=new b.BatchQueryParams(),pattern=b.QueryGraph.fromSmarts('[#8]'),patterns=[pattern],provider=b.MorganAtomInvariantsGenerator.features(patterns);patterns.length=0;pattern.free();
 const bond=b.MorganBondInvariantsGenerator.new(false,true);assert.equal(bond.useBondTypes(),false);assert.equal(bond.includeChirality(),true);assert.equal(new b.MorganBondInvariantsGenerator().useBondTypes(),true);
 for(const atom of [provider,b.MorganAtomInvariantsGenerator.features(),b.MorganAtomInvariantsGenerator.features([]),b.MorganAtomInvariantsGenerator.connectivity(),b.MorganAtomInvariantsGenerator.atomPair(new b.AtomPairAtomInvariantsGenerator())]){const first=value.fingerprintMorganListWithGeneratorParams(options,atom,bond,call,query)[0];assert.ok(first instanceof b.Fingerprint);assert.deepEqual(value.fingerprintMorganListWithGeneratorParams(options,atom,bond,call,query)[0].onBits(),first.onBits());}
 assert.deepEqual(value.fingerprintMorganListWithGeneratorParams(options,null,null,new b.MorganCallParams([]),query)[0].onBits(),[]);assert.throws(()=>b.MorganAtomInvariantsGenerator.features([{}]),TypeError);assert.throws(()=>value.fingerprintMorganListWithGeneratorParams(options,{},null,call,query),TypeError);
});
test('Morgan batch failure rows, causal categories and callback identity preserve canonical execution',()=>{
 const value=batch(),options=new b.MorganFingerprintParams();let ticks=0;const query=new b.BatchQueryParams(null,false,()=>{ticks++;});value.fingerprintMorganListWithParams(options,query);assert.equal(ticks,3);const thrown=Symbol('callback');assert.throws(()=>value.fingerprintMorganListWithParams(options,new b.BatchQueryParams(null,false,()=>{throw thrown;})),e=>e===thrown);
 const zero=new b.MorganFingerprintParams(new b.MorganParams(undefined,undefined,undefined,undefined,undefined,undefined,0));ticks=0;assert.throws(()=>value.fingerprintMorganListWithParams(zero,query),e=>{assert.deepEqual(e.recordErrors.map(r=>r.index()),[0,2]);assert.ok(causes(e).some(c=>c.detail instanceof b.MorganReadError&&c.kind==='Generator'));assert.ok(causes(e).some(c=>c.kind==='EmptyFingerprint'));return true;});assert.equal(ticks,3);
 // Disable hydrogen removal as well as sanitization to create the raw-cache
 // fixture. The default hydrogen-removal path may prepare valence itself.
 const raw=b.MoleculeBatch.fromRecords([b.BatchRecord.molecule(b.Molecule.fromSmilesWithParams('CC',new b.SmilesParseParams(false,undefined,undefined,undefined,false)))],b.BatchErrorMode.Strict);assert.throws(()=>raw.fingerprintMorganList(),e=>causes(e).some(c=>c.detail instanceof b.MorganReadError&&c.kind==='Preparation')&&causes(e).some(c=>c.kind==='MissingPreparedValence'));
 assert.throws(()=>value.fingerprintMorganWithOutputListWithParams(options,'false',query),TypeError);
});
