import { Molecule } from "cosmolkit-generated";

declare const molecule: Molecule;

const constructor: (smiles: string) => Molecule = Molecule.fromSmiles;
const fromSmilesWithSanitize: (smiles: string, sanitize: boolean) => Molecule =
    Molecule.fromSmilesWithSanitize;
const fromSdf: (text: string) => Molecule = Molecule.fromSdf;
const numAtoms: () => number = molecule.numAtoms;
const numBonds: () => number = molecule.numBonds;
const atomicNumbers: () => Uint8Array = molecule.atomicNumbers;
const nameOrEmpty: () => string = molecule.nameOrEmpty;
const withName: (name: string) => Molecule = molecule.withName;
const withProperty: (key: string, value: string) => Molecule = molecule.withProperty;
const withSdfDataField: (key: string, value: string) => Molecule = molecule.withSdfDataField;
const propertyOrEmpty: (key: string) => string = molecule.propertyOrEmpty;
const propertyKeys: () => string[] = molecule.propertyKeys;
const sdfDataFieldNames: () => string[] = molecule.sdfDataFieldNames;
const sdfDataFieldOrEmpty: (name: string) => string = molecule.sdfDataFieldOrEmpty;
const coordinates2d: () => Float64Array = molecule.coordinates2d;
const numConformers3d: () => number = molecule.numConformers3d;
const coordinates3d: (conformerId: number) => Float64Array = molecule.coordinates3d;
const molecularWeight: () => number = molecule.molecularWeight;
const exactMolecularWeight: () => number = molecule.exactMolecularWeight;
const molecularFormula: () => string = molecule.molecularFormula;
const withHydrogens: () => Molecule = molecule.withHydrogens;
const withoutHydrogens: () => Molecule = molecule.withoutHydrogens;
const withKekulizedBonds: () => Molecule = molecule.withKekulizedBonds;
const sanitize: () => Molecule = molecule.sanitize;
const withAssignedValence: () => Molecule = molecule.withAssignedValence;
const withAssignedRings: () => Molecule = molecule.withAssignedRings;
const withAssignedRingFamilies: () => Molecule = molecule.withAssignedRingFamilies;
const withAssignedAromaticity: () => Molecule = molecule.withAssignedAromaticity;
const withAssignedRadicals: () => Molecule = molecule.withAssignedRadicals;
const with2dCoordinates: () => Molecule = molecule.with2dCoordinates;

void constructor;
void fromSmilesWithSanitize;
void fromSdf;
void numAtoms;
void numBonds;
void atomicNumbers;
void nameOrEmpty;
void withName;
void withProperty;
void withSdfDataField;
void propertyOrEmpty;
void propertyKeys;
void sdfDataFieldNames;
void sdfDataFieldOrEmpty;
void coordinates2d;
void numConformers3d;
void coordinates3d;
void molecularWeight;
void exactMolecularWeight;
void molecularFormula;
void withHydrogens;
void withoutHydrogens;
void withKekulizedBonds;
void sanitize;
void withAssignedValence;
void withAssignedRings;
void withAssignedRingFamilies;
void withAssignedAromaticity;
void withAssignedRadicals;
void with2dCoordinates;
