import { Molecule } from "cosmolkit-generated";

declare const molecule: Molecule;

const constructor: (smiles: string) => Molecule = Molecule.fromSmiles;
const toSmiles: () => string = molecule.toSmiles;
const numAtoms: () => number = molecule.numAtoms;
const numBonds: () => number = molecule.numBonds;
const toSvg: (width: number, height: number) => string = molecule.toSvg;
const molecularWeight: () => number = molecule.molecularWeight;
const exactMolecularWeight: () => number = molecule.exactMolecularWeight;
const crippenLogP: () => number = molecule.crippenLogP;
const crippenMolarRefractivity: () => number = molecule.crippenMolarRefractivity;
const tpsa: () => number = molecule.tpsa;
const hBondAcceptors: () => number = molecule.hBondAcceptors;
const hBondDonors: () => number = molecule.hBondDonors;
const formula: () => string = molecule.formula;
const numHeavyAtoms: () => number = molecule.numHeavyAtoms;
const numRings: () => number = molecule.numRings;
const numAromaticRings: () => number = molecule.numAromaticRings;
const numRotatableBonds: () => number = molecule.numRotatableBonds;
const qed: () => number = molecule.qed;
const hallKierAlpha: () => number = molecule.hallKierAlpha;
const kappa1: () => number = molecule.kappa1;
const kappa2: () => number = molecule.kappa2;
const kappa3: () => number = molecule.kappa3;
const chi: (order: number, pathType: boolean, force: boolean) => number = molecule.chi;
const chi0: () => number = molecule.chi0;
const chi1: () => number = molecule.chi1;
const phi: () => number = molecule.phi;
const labuteAsa: (includeHydrogens: boolean, force: boolean) => number = molecule.labuteAsa;
const nameOrEmpty: () => string = molecule.nameOrEmpty;
const withName: (name: string) => Molecule = molecule.withName;
const withProperty: (key: string, value: string) => Molecule = molecule.withProperty;
const withSdfDataField: (key: string, value: string) => Molecule = molecule.withSdfDataField;
const propertyOrEmpty: (key: string) => string = molecule.propertyOrEmpty;
const propertyKeys: () => string[] = molecule.propertyKeys;
const sdfDataFieldNames: () => string[] = molecule.sdfDataFieldNames;
const sdfDataFieldOrEmpty: (name: string) => string = molecule.sdfDataFieldOrEmpty;
const sourceCoordinateDimensionOrEmpty: () => string = molecule.sourceCoordinateDimensionOrEmpty;
const atomicNumbers: () => Uint8Array = molecule.atomicNumbers;
const patternFingerprint: () => Uint32Array = molecule.patternFingerprint;
const morganFingerprint: () => Uint32Array = molecule.morganFingerprint;
const atomPairFingerprint: () => Uint32Array = molecule.atomPairFingerprint;
const layeredFingerprint: () => Uint32Array = molecule.layeredFingerprint;
const topologicalFingerprint: () => Uint32Array = molecule.topologicalFingerprint;
const maccsFingerprint: () => Uint32Array = molecule.maccsFingerprint;
const avalonFingerprint: () => Uint32Array = molecule.avalonFingerprint;
const topologicalTorsionFingerprint: () => Uint32Array = molecule.topologicalTorsionFingerprint;
const withHydrogens: () => Molecule = molecule.withHydrogens;
const withoutHydrogens: () => Molecule = molecule.withoutHydrogens;
const with2dCoordinates: () => Molecule = molecule.with2dCoordinates;
const coordinates2d: () => Float64Array = molecule.coordinates2d;
const with3dConformer: () => Molecule = molecule.with3dConformer;
const numConformers3d: () => number = molecule.numConformers3d;
const stereoisomerCount: () => string = molecule.stereoisomerCount;
const hasSubstructMatch: (smarts: string) => boolean = molecule.hasSubstructMatch;
const toBinary: () => Uint8Array = molecule.toBinary;
const fromBinary: (data: Uint8Array) => Molecule = Molecule.fromBinary;

void constructor;
void toSmiles;
void numAtoms;
void numBonds;
void toSvg;
void molecularWeight;
void exactMolecularWeight;
void crippenLogP;
void crippenMolarRefractivity;
void tpsa;
void hBondAcceptors;
void hBondDonors;
void formula;
void numHeavyAtoms;
void numRings;
void numAromaticRings;
void numRotatableBonds;
void qed;
void hallKierAlpha;
void kappa1;
void kappa2;
void kappa3;
void chi;
void chi0;
void chi1;
void phi;
void labuteAsa;
void nameOrEmpty;
void withName;
void withProperty;
void withSdfDataField;
void propertyOrEmpty;
void propertyKeys;
void sdfDataFieldNames;
void sdfDataFieldOrEmpty;
void sourceCoordinateDimensionOrEmpty;
void atomicNumbers;
void patternFingerprint;
void morganFingerprint;
void atomPairFingerprint;
void layeredFingerprint;
void topologicalFingerprint;
void maccsFingerprint;
void avalonFingerprint;
void topologicalTorsionFingerprint;
void withHydrogens;
void withoutHydrogens;
void with2dCoordinates;
void coordinates2d;
void with3dConformer;
void numConformers3d;
void stereoisomerCount;
void hasSubstructMatch;
void toBinary;
void fromBinary;
