import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import test from 'node:test';import {pathToFileURL} from 'node:url';
const b=await import(pathToFileURL(process.env.COSMOLKIT_WASM_MODULE).href);b.initSync({module:readFileSync(process.env.COSMOLKIT_WASM_BINARY)});
const pdb='REMARK   1 PRESERVED\nATOM      1  CA  ALA A   1       1.000   2.000   3.000  1.00 20.00           C  \nHETATM    2  O   HOH B   2       4.000   5.000   6.000  1.00 20.00           O  \nEND\n';
test('BIO CID construction and serialization preserve selection matches, input order and missing-match behavior',()=>{
 const s=b.BioStructure.fromPdb(pdb),select=b.BioSelection.fromCid('/1/A/1'),all=b.BioSelection.fromCid('/'),none=b.BioSelection.fromCid('/1/Z/99');assert.deepEqual([...s.selectedAtomIds(select)],[0]);assert.deepEqual([...s.selectedAtomIds(all)],[0,1]);assert.deepEqual([...s.selectedAtomIds(none)],[]);const serialized=select.toCid();assert.equal(typeof serialized,'string');assert.deepEqual([...s.selectedAtomIds(b.BioSelection.fromCid(serialized))],[0]);assert.equal(select.toCid(),serialized);assert.equal(s.numAtoms(),2);
 const value=s.withSelection(select);assert.equal(value.numAtoms(),1);assert.equal(value.atoms()[0].source().serial(),1);assert.deepEqual(value.atomPosition(0),[1,2,3]);assert.deepEqual(value.sourceState().rawRemarks,['REMARK   1 PRESERVED']);assert.equal(s.numAtoms(),2);const empty=s.withSelection(none);assert.equal(empty.numAtoms(),0);assert.deepEqual(empty.atoms(),[]);assert.equal(empty.validate(),undefined);
 const row=s.atoms()[1],coordinates=s.coordinates();assert.equal(s.retainSelection_(select),undefined);assert.equal(s.numAtoms(),1);assert.equal(row.source().serial(),2);assert.deepEqual(row.position(),[4,5,6]);assert.deepEqual(coordinates.positions,[[1,2,3],[4,5,6]]);assert.deepEqual([...s.selectedAtomIds(select)],[0]);assert.equal(select.toCid(),serialized);
});
test('BIO value and in-place translation retain snapshots, shape checks, source metadata and non-finite scalar behavior',()=>{
 const s=b.BioStructure.fromPdb(pdb),old=s.atoms()[0],coordinates=s.coordinates(),source=s.sourceState();const changed=s.withTranslatedCoordinates(new Float64Array([1,2,3]));assert.deepEqual(s.atomPosition(0),[1,2,3]);assert.deepEqual(changed.atomPosition(0),[2,4,6]);assert.deepEqual(changed.sourceState().rawRemarks,source.rawRemarks);assert.equal(s.translate_([3,0,-1]),undefined);assert.deepEqual(s.atomPosition(0),[4,2,2]);assert.deepEqual(old.position(),[1,2,3]);assert.deepEqual(coordinates.positions[0],[1,2,3]);const before=s.coordinates().positions;for(const offset of [[],[1,2],[1,2,3,4]])assert.throws(()=>s.translate_(offset),RangeError);for(const offset of ['1,2,3',[1,'2',3],[true,2,3]])assert.throws(()=>s.translate_(offset),TypeError);assert.deepEqual(s.coordinates().positions,before);const exceptional=s.withTranslatedCoordinates([NaN,Infinity,-Infinity]).atomPosition(0);assert.ok(Number.isNaN(exceptional[0]));assert.equal(exceptional[1],Infinity);assert.equal(exceptional[2],-Infinity);s.free();assert.deepEqual(old.position(),[1,2,3]);
});
test('BIO malformed CID errors preserve exact syntax context and never fabricate an offset for range errors',()=>{
 for(const [cid,info] of [['/1x/A',' (at model number)'],['A(B/1',' (at residue)'],['CA[C'," (no matching ']')"],[';ligand',' at ligand']])assert.throws(()=>b.BioSelection.fromCid(cid),e=>{assert.equal(e.domain,'bio');assert.equal(e.kind,'Parse');assert.ok(e.detail instanceof b.BioSelectionParseError);assert.equal(e.detail.variant,'Syntax');assert.equal(e.detail.cid,cid);assert.equal(e.detail.info,info);assert.equal(typeof e.detail.pos,'number');assert.equal(e.detail.cause,null);assert.equal(e.cause,undefined);assert.ok(e.message.includes(cid));return true;});
 assert.throws(()=>b.BioSelection.fromCid('5000000000-1'),e=>{assert.equal(e.kind,'Parse');assert.equal(e.detail.variant,'SeqidRange');assert.equal(e.detail.pos,null);assert.equal(e.detail.info,null);assert.ok(e.message.includes('5000000000'));return true;});
});
test('BIO transform approx forwards exact source comparison and epsilon behavior',()=>{const a=b.BioStructure.fromPdb(pdb).origx(),c=b.BioStructure.fromPdb(pdb).origx();assert.equal(a.approx(c,0),true);assert.equal(a.approx(c,-1),false);assert.equal(a.approx(c,NaN),false);assert.throws(()=>a.approx(c,'0'),TypeError);assert.deepEqual(a.matrix,[[1,0,0],[0,1,0],[0,0,1]]);});
