import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import test from 'node:test';import {pathToFileURL} from 'node:url';
const b=await import(pathToFileURL(process.env.COSMOLKIT_WASM_MODULE).href);b.initSync({module:readFileSync(process.env.COSMOLKIT_WASM_BINARY)});
const pdb="ATOM      1  CA AALA A   1       1.000   2.000   3.000  1.00 20.00           C  \nHETATM    2  SE  MSE B   2       4.000   5.000   6.000  1.00 20.00          SE  \nHETATM    3  O   HOH C   3       7.000   8.000   9.000  1.00 20.00           O  \nEND\n",cif="data_hierarchy\n_entity.id e1\n_entity.type polymer\n_entity_poly.entity_id e1\n_entity_poly.type \"polypeptide(L)\"\n_struct_asym.id X\n_struct_asym.entity_id e1\nloop_\n_entity_poly_seq.entity_id\n_entity_poly_seq.num\n_entity_poly_seq.mon_id\ne1 1 ALA\ne1 2 GLY\nloop_\n_atom_site.group_PDB\n_atom_site.id\n_atom_site.type_symbol\n_atom_site.label_atom_id\n_atom_site.label_comp_id\n_atom_site.label_alt_id\n_atom_site.label_asym_id\n_atom_site.label_entity_id\n_atom_site.label_seq_id\n_atom_site.auth_asym_id\n_atom_site.auth_seq_id\n_atom_site.Cartn_x\n_atom_site.Cartn_y\n_atom_site.Cartn_z\n_atom_site.occupancy\n_atom_site.B_iso_or_equiv\nATOM 19 C CA ALA . X e1 1 A -4 1 2 3 1 20\n";

test('Protein all text construction routes and projection retain source format, amino-acid rows and source receiver',()=>{
 const p=new b.BioPdbReadParams(),read=new b.BioReadParams(b.BioCoordinateFormat.Pdb,'protein.pdb'),source=b.BioStructure.fromPdb(pdb),values=[b.Protein.fromPdb(pdb),b.Protein.fromPdbWithParams(pdb,p),b.Protein.fromText(pdb),b.Protein.fromTextWithParams(pdb,read),source.protein()];for(const v of values){assert.ok(v instanceof b.Protein);assert.deepEqual([v.numModels(),v.numChains(),v.numResidues(),v.numAtoms(),v.len()],[1,2,2,2,2]);assert.equal(v.inputFormat(),b.BioCoordinateFormat.Pdb);const summary=v.selectionSummary();assert.deepEqual([summary.chains,summary.residues,summary.atoms],[2,2,2]);assert.throws(()=>{summary.atoms=0},TypeError);const borrowed=v.asBioStructure(),owned=v.intoBioStructure();assert.equal(borrowed.numAtoms(),2);assert.equal(owned.numAtoms(),2);assert.equal(v.numAtoms(),2);assert.deepEqual(borrowed.atoms().map(a=>a.source().serial()),[1,2]);assert.equal(v.chain(2),null);assert.throws(()=>v.chain(-1),RangeError);assert.throws(()=>v.chain('0'),TypeError);}assert.equal(source.numAtoms(),3);assert.equal(p.ignoreTer,false);assert.equal(read.sourceName,'protein.pdb');const mm=b.Protein.fromMmcif(cif);assert.equal(mm.inputFormat(),b.BioCoordinateFormat.Mmcif);assert.equal(mm.numAtoms(),1);assert.equal(b.Protein.fromTextWithParams(cif,new b.BioReadParams(b.BioCoordinateFormat.Mmcif)).numAtoms(),1);
 const empty=b.Protein.fromPdb('END\n');assert.deepEqual([empty.numChains(),empty.numResidues(),empty.numAtoms()],[0,0,0]);assert.deepEqual([...empty.chains()],[]);assert.equal(empty.chain(0),null);
});
test('Protein canonical iterators preserve ordered scopes, fused exhaustion and remaining lengths',()=>{
 const p=b.Protein.fromPdb(pdb),it=p.chains();assert.ok(it instanceof b.ProteinChainIter);assert.equal(it[Symbol.iterator](),it);assert.equal(it.len(),2);const first=it.next();assert.equal(first.done,false);assert.equal(first.value.id(),0);assert.equal(it.len(),1);assert.deepEqual([...it].map(v=>v.id()),[1]);assert.equal(it.len(),0);for(let i=0;i<2;i++)assert.deepEqual(it.next(),{done:true,value:undefined});
 const chains=[...p.chains()],residues=[...p.residues()],atoms=[...p.atoms()];assert.ok(p.residues() instanceof b.ProteinResidueIter);assert.ok(p.atoms() instanceof b.ProteinAtomIter);assert.deepEqual(chains.map(v=>v.id()),[0,1]);assert.deepEqual(residues.map(v=>v.id()),[0,1]);assert.deepEqual(atoms.map(v=>v.id()),[0,1]);assert.deepEqual([...chains[1].residues()].map(v=>v.id()),[1]);assert.deepEqual([...chains[1].atoms()].map(v=>v.id()),[1]);assert.deepEqual([...residues[1].atoms()].map(v=>v.id()),[1]);assert.equal(chains[0].len(),1);assert.equal(residues[0].len(),1);
});
test('Protein complete row vocabulary, source references, parent links and positions outlive parents',()=>{
 const p=b.Protein.fromPdb(pdb),chain=p.chain(0),residue=[...chain.residues()][0],modified=[...p.residues()][1],atom=[...residue.atoms()][0],savedIter=p.atoms();assert.equal(chain.kind(),b.ChainKind.Protein);assert.equal(chain.source().authChainId(),'A');assert.equal(chain.row().id(),0);assert.equal(residue.row().name(),'ALA');assert.equal(residue.chain().id(),0);assert.equal(residue.kind(),b.ResidueKind.AminoAcid);assert.equal(residue.name(),'ALA');assert.equal(residue.code(),b.ResidueCode.ALA);assert.equal(residue.oneLetterCode(),'A');assert.equal(residue.fastaCode(),'A');assert.equal(residue.canonicalOneLetterCode(),'A');assert.equal(residue.info().canonicalOneLetterCode(),'A');assert.equal(residue.isStandard(),true);assert.equal(residue.isModifiedAminoAcid(),false);assert.equal(modified.code(),b.ResidueCode.MSE);assert.equal(modified.isModifiedAminoAcid(),true);assert.equal(modified.parentStandardCode(),b.ResidueCode.MET);assert.equal(modified.canonicalOneLetterCode(),'M');assert.equal(atom.name(),'CA');assert.equal(atom.altloc(),'A');assert.equal(atom.residue().id(),0);assert.equal(atom.row().source().serial(),1);assert.equal(atom.element().symbol(),'C');assert.equal(atom.elementSymbol(),'C');assert.equal(atom.atomicNumber(),6);assert.deepEqual(atom.position(),[1,2,3]);const position=atom.position();position[0]=99;assert.equal(atom.position()[0],1);p.free();assert.deepEqual(atom.position(),[1,2,3]);assert.equal(modified.name(),'MSE');assert.equal(chain.source().authChainId(),'A');assert.deepEqual([...savedIter].map(v=>v.position()),[[1,2,3],[4,5,6]]);
});
test('Protein value and COW in-place transforms preserve old rows, iterators and original structures',()=>{
 const p=b.Protein.fromPdb(pdb),old=p.chain(0),atom=[...p.atoms()][0],iterator=p.atoms(),original=p.asBioStructure(),selection=b.BioSelection.fromCid('/1/A/1');assert.deepEqual([...p.selectedAtomIds(selection)],[0]);const value=p.withSelection(selection);assert.equal(value.numAtoms(),1);assert.equal(p.numAtoms(),2);const moved=p.withTranslatedCoordinates(new Float64Array([1,0,0]));assert.deepEqual([...moved.atoms()][0].position(),[2,2,3]);assert.deepEqual(atom.position(),[1,2,3]);assert.equal(p.translate_([3,2,1]),undefined);assert.deepEqual([...p.atoms()][0].position(),[4,4,4]);assert.deepEqual([...iterator][0].position(),[1,2,3]);assert.deepEqual(original.atomPosition(0),[1,2,3]);const before=[...p.atoms()].map(v=>v.position());for(const bad of [[1,2],[],[1,2,3,4]])assert.throws(()=>p.translate_(bad),RangeError);assert.throws(()=>p.translate_([1,'2',3]),TypeError);assert.deepEqual([...p.atoms()].map(v=>v.position()),before);assert.equal(p.retainSelection_(selection),undefined);assert.equal(p.numAtoms(),1);assert.equal(old.source().authChainId(),'A');assert.equal(old.len(),1);assert.deepEqual(atom.position(),[1,2,3]);assert.equal(selection.toCid().includes('A'),true);assert.equal(p.withSelection(b.BioSelection.fromCid('/1/Z')).numAtoms(),0);
});
test('Protein read errors preserve every available phase through canonical nested causes and WASM filesystem errors',()=>{
 assert.throws(()=>b.Protein.fromPdb('ATOM  \n'),e=>{assert.equal(e.kind,'Pdb');assert.ok(e.detail instanceof b.ProteinReadError);assert.ok(e.cause.detail instanceof b.BioPdbReadError);assert.equal(e.cause.detail.lineNumber(),1);assert.equal(e.detail.cause.kind,'Pdb');return true;});assert.throws(()=>b.Protein.fromMmcif('not a cif'),e=>e.kind==='Mmcif'&&e.cause.detail instanceof b.BioMmcifReadError&&e.cause.detail.stage()===b.BioMmcifReadStage.CifDocument);assert.throws(()=>b.Protein.fromTextWithParams('ATOM  \n',new b.BioReadParams(b.BioCoordinateFormat.Pdb)),e=>e.kind==='Structure'&&e.cause.detail instanceof b.BioReadError&&e.cause.cause.detail instanceof b.BioPdbReadError);for(const call of [()=>b.Protein.read('/protein.pdb'),()=>b.Protein.readWithFormat('/protein.pdb',b.BioCoordinateFormat.Pdb)])assert.throws(call,e=>e.kind==='Structure'&&e.cause.kind==='Io'&&e.cause.path==='/protein.pdb'&&e.cause.cause.kind==='Unsupported');assert.throws(()=>b.Protein.readWithFormat('/protein.pdb',6),RangeError);
});
