import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import test from 'node:test';import {pathToFileURL} from 'node:url';
const b=await import(pathToFileURL(process.env.COSMOLKIT_WASM_MODULE).href);b.initSync({module:readFileSync(process.env.COSMOLKIT_WASM_BINARY)});
const pdb="ATOM      7  CA  ALA A   1       1.000   2.000   3.000  1.00 20.00           C  \nEND\n",cif="data_hierarchy\n_entity.id e1\n_entity.type polymer\n_entity_poly.entity_id e1\n_entity_poly.type \"polypeptide(L)\"\n_struct_asym.id X\n_struct_asym.entity_id e1\nloop_\n_entity_poly_seq.entity_id\n_entity_poly_seq.num\n_entity_poly_seq.mon_id\ne1 1 ALA\ne1 2 GLY\nloop_\n_atom_site.group_PDB\n_atom_site.id\n_atom_site.type_symbol\n_atom_site.label_atom_id\n_atom_site.label_comp_id\n_atom_site.label_alt_id\n_atom_site.label_asym_id\n_atom_site.label_entity_id\n_atom_site.label_seq_id\n_atom_site.auth_asym_id\n_atom_site.auth_seq_id\n_atom_site.Cartn_x\n_atom_site.Cartn_y\n_atom_site.Cartn_z\n_atom_site.occupancy\n_atom_site.B_iso_or_equiv\nATOM 19 C CA ALA . X e1 1 A -4 1 2 3 1 20\n",groups=["atoms", "blockName", "entry", "databaseStatus", "author", "cell", "symmetry", "entity", "entityPoly", "structRef", "chemComp", "exptl", "diffrn", "reflns", "refine", "titleKeywords", "ncs", "structAsym", "origx", "structConf", "structSheet", "structBiol", "assembly", "conn", "cis", "modres", "scale", "atomType", "entityPolySeq", "tls", "software", "groupPdb"],bools=["atoms", "blockName", "entry", "databaseStatus", "author", "cell", "symmetry", "entity", "entityPoly", "structRef", "chemComp", "exptl", "diffrn", "reflns", "refine", "titleKeywords", "ncs", "structAsym", "origx", "structConf", "structSheet", "structBiol", "assembly", "conn", "cis", "modres", "scale", "atomType", "entityPolySeq", "tls", "software", "groupPdb", "authAll", "preferPairs", "compact", "misuseHash"];

test('BIO PDB all mutable write parameters, defaults, constructor and borrowed reuse',()=>{
 const p=new b.BioPdbWriteParams(),names=['terRecords','numberedTer','terIgnoresType','preserveSerial','endRecord'];assert.deepEqual(names.map(n=>p[n]),[true,true,false,false,true]);const positional=new b.BioPdbWriteParams(false,false,true,true,false);assert.deepEqual(names.map(n=>positional[n]),[false,false,true,true,false]);for(const name of names){const old=p[name];p[name]=!old;assert.equal(p[name],!old);p[name]=old;assert.throws(()=>{p[name]=1},TypeError);assert.equal(p[name],old);}assert.throws(()=>new b.BioPdbWriteParams('false'),TypeError);
 const s=b.BioStructure.fromPdb(pdb),standard=s.toPdb();assert.equal(s.toPdbWithParams(p),standard);assert.equal(s.toPdbWithParams(p),standard);assert.ok(standard.split('\n').some(x=>x.startsWith('END')));assert.equal(b.BioStructure.fromPdb(standard).numAtoms(),1);assert.deepEqual(s.atomPosition(0),[1,2,3]);p.preserveSerial=true;p.endRecord=false;p.terRecords=false;const text=s.toPdbWithParams(p);assert.equal(text.slice(6,11).trim(),'7');assert.ok(!text.split('\n').some(x=>x.startsWith('END')));assert.equal(p.preserveSerial,true);assert.equal(s.atoms()[0].source().serial(),7);
});
test('BIO mmCIF complete category inheritance and scalar widths retain mutable atomic setters',()=>{
 const p=new b.BioMmcifWriteParams();for(const name of groups)assert.equal(p[name],true);for(const name of ['authAll','preferPairs','compact','misuseHash'])assert.equal(p[name],false);assert.equal(p.alignPairs,0);assert.equal(p.alignLoops,0);
 const empty=new b.BioMmcifWriteParams(false);for(const name of groups)assert.equal(empty[name],false);const mixed=new b.BioMmcifWriteParams(false,true,null,true);assert.equal(mixed.atoms,true);assert.equal(mixed.blockName,false);assert.equal(mixed.entry,true);assert.equal(mixed.authAll,false);assert.throws(()=>new b.BioMmcifWriteParams(null),TypeError);
 for(const name of bools){const old=p[name];p[name]=!old;assert.equal(p[name],!old);assert.throws(()=>{p[name]='false'},TypeError);assert.equal(p[name],!old);p[name]=old;}
 for(const name of ['alignPairs','alignLoops']){p[name]=65535;assert.equal(p[name],65535);for(const v of [-1,65536,1.1,NaN,Infinity])assert.throws(()=>{p[name]=v},RangeError);assert.throws(()=>{p[name]='2'},TypeError);assert.equal(p[name],65535);p[name]=0;}
 const args=Array(39).fill(undefined);args[37]=65536;assert.throws(()=>new b.BioMmcifWriteParams(...args),RangeError);args[37]=12;args[38]=13;const aligned=new b.BioMmcifWriteParams(...args);assert.equal(aligned.alignPairs,12);assert.equal(aligned.alignLoops,13);
});
test('BIO mmCIF text variants preserve hierarchy, category selection and writer layout choices',()=>{
 const s=b.BioStructure.fromMmcif(cif),p=new b.BioMmcifWriteParams();assert.equal(s.toMmcif(),s.toMmcifWithParams(p));const normal=s.toMmcif(),round=b.BioStructure.fromMmcif(normal);assert.equal(round.numAtoms(),1);assert.deepEqual(round.atomPosition(0),[1,2,3]);assert.equal(round.entities()[0].source().sourceEntityId(),'e1');assert.ok(normal.includes('_atom_site.group_PDB'));p.groupPdb=false;const without=s.toMmcifWithParams(p);assert.ok(!without.includes('_atom_site.group_PDB'));p.authAll=true;p.preferPairs=true;p.compact=true;p.misuseHash=true;p.alignPairs=30;p.alignLoops=16;const layout=s.toMmcifWithParams(p);assert.ok(layout.includes('_atom_site.auth_atom_id'));assert.ok(layout.includes('_atom_site.auth_comp_id'));assert.equal(b.BioStructure.fromMmcif(layout).numAtoms(),1);p.atoms=false;assert.ok(!s.toMmcifWithParams(p).includes('_atom_site.'));assert.equal(s.numAtoms(),1);assert.equal(p.alignPairs,30);assert.equal(p.alignLoops,16);
});
test('BIO writer source failures retain numeric contexts and never relabel supported inputs unsupported',()=>{
 const s=b.BioStructure.fromMmcif(cif.replace('ATOM 19','ATOM -1')),p=new b.BioPdbWriteParams();p.preserveSerial=true;assert.equal(s.atoms()[0].source().serial(),-1);assert.throws(()=>s.toPdbWithParams(p),e=>{assert.equal(e.kind,'NegativeSerial');assert.equal(e.serial,-1);assert.ok(e.detail instanceof b.BioPdbWriteError);assert.equal(e.detail.serial,-1);assert.equal(e.detail.chain,null);assert.equal(e.detail.cause,null);return true;});assert.equal(s.numAtoms(),1);assert.equal(p.preserveSerial,true);
 // COSMolKit pinned records::write_pdb_coordinate_text currently maps oversized chains to NegativeBase36Value(length).
 const long=b.BioStructure.fromMmcif(cif.replace('1 A -4','1 LONG -4'));assert.throws(()=>long.toPdb(),e=>e.kind==='NegativeBase36Value'&&e.value===4&&e.detail.value===4);
});
test('BIO filesystem calls preserve original WASM unsupported IO category, paths and borrowed parameters',()=>{
 const s=b.BioStructure.fromPdb(pdb),pdbOptions=new b.BioPdbWriteParams(),cifOptions=new b.BioMmcifWriteParams(),path='/binding-writers/result.pdb';for(const [call,kind,type] of [[()=>s.writePdb(path),'Io',b.BioPdbWriteError],[()=>s.writePdbWithParams(path,pdbOptions),'Io',b.BioPdbWriteError],[()=>s.writeMmcif(path),'FileWrite',b.BioMmcifWriteError],[()=>s.writeMmcifWithParams(path,cifOptions),'FileWrite',b.BioMmcifWriteError]])assert.throws(call,e=>{assert.equal(e.domain,'bio');assert.equal(e.kind,kind);assert.equal(e.path,path);assert.ok(e.detail instanceof type);assert.equal(e.detail.path,path);assert.equal(e.cause.kind,'Unsupported');assert.equal(e.detail.cause.kind,'Unsupported');return true;});assert.equal(s.numAtoms(),1);assert.equal(pdbOptions.endRecord,true);assert.equal(cifOptions.atoms,true);
});
