import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import test from 'node:test';import {pathToFileURL} from 'node:url';
const b=await import(pathToFileURL(process.env.COSMOLKIT_WASM_MODULE).href);b.initSync({module:readFileSync(process.env.COSMOLKIT_WASM_BINARY)});
const pdb="ATOM      1  CA AALA A   1       1.000   2.000   3.000  0.60 20.00           C  \nATOM      2  CA BALA A   1       4.000   5.000   6.000  0.40 30.00           C  \nATOM      3  N   ALA A   1       7.000   8.000   9.000  1.00 10.00           N  \nEND\n",cif="data_hierarchy\n_entity.id e1\n_entity.type polymer\n_entity_poly.entity_id e1\n_entity_poly.type \"polypeptide(L)\"\n_struct_asym.id X\n_struct_asym.entity_id e1\nloop_\n_entity_poly_seq.entity_id\n_entity_poly_seq.num\n_entity_poly_seq.mon_id\ne1 1 ALA\ne1 2 GLY\nloop_\n_atom_site.group_PDB\n_atom_site.id\n_atom_site.type_symbol\n_atom_site.label_atom_id\n_atom_site.label_comp_id\n_atom_site.label_alt_id\n_atom_site.label_asym_id\n_atom_site.label_entity_id\n_atom_site.label_seq_id\n_atom_site.auth_asym_id\n_atom_site.auth_seq_id\n_atom_site.Cartn_x\n_atom_site.Cartn_y\n_atom_site.Cartn_z\n_atom_site.occupancy\n_atom_site.B_iso_or_equiv\nATOM 19 C CA ALA . X e1 1 A -4 1 2 3 1 20\n";
const ascii=s=>new TextEncoder().encode(s);
test('BIO source names, byte identities, row IDs and spans retain exact widths and null semantics',()=>{
 for(const type of [b.AtomName,b.ResidueName,b.PdbChainId]){for(const s of ['', ' CA ', 'A\0B']){const v=type.fromAscii(ascii(s));assert.equal(v.asStr(),s);const bytes=v.asBytes();assert.deepEqual([...bytes],[...ascii(s)]);if(bytes.length)bytes[0]=255;assert.equal(v.asStr(),s);}assert.equal(type.fromAscii(ascii('ABCDE')),null);assert.equal(type.fromAscii([128]),null);assert.throws(()=>type.fromAscii([256]),RangeError);assert.throws(()=>type.fromAscii('CA'),TypeError);}
 for(const type of [b.BioAtomId,b.BioResidueId,b.BioChainId,b.BioEntityId,b.BioModelId,b.BioAssemblyId,b.BioAltLocGroupId]){const id=new type(4294967295);assert.equal(id.value(),4294967295);assert.equal(id.index(),4294967295);for(const value of [-1,1.5,4294967296,NaN])assert.throws(()=>new type(value),RangeError);assert.throws(()=>new type('1'),TypeError);}
 assert.equal(new b.PdbAtomSerial(-2147483648).value(),-2147483648);assert.throws(()=>new b.PdbAtomSerial(2147483648),RangeError);
 for(const value of [0,65,255]){const v=new b.AltLocLabel(value);assert.equal(v.value(),value);b.AltLocRequest.Exact(v);assert.equal(v.value(),value);}assert.throws(()=>new b.AltLocLabel(256),RangeError);assert.throws(()=>b.AltLocRequest.Exact({}),TypeError);
 const span=new b.BioRowSpan(4294967295,0);assert.deepEqual([span.start(),span.len(),span.end(),span.isEmpty()],[4294967295,0,4294967295,true]);assert.throws(()=>new b.BioRowSpan(4294967295,1),e=>e.kind==='RowSpanOverflow'&&e.start===4294967295&&e.len===1&&e.detail instanceof b.BioStructureError&&e.detail.start===4294967295);
});
test('BIO hierarchical row traversal, detached positions and lifetime after parent release',()=>{
 const s=b.BioStructure.fromPdb(pdb),models=s.models(),chains=s.chains(),residues=s.residues(),atoms=s.atoms(),coordinates=s.coordinates();assert.equal(models.length,1);assert.equal(models[0].sourceModelNumber(),1);assert.equal(models[0].len(),1);assert.equal(models[0].chains()[0].id(),0);assert.equal(chains[0].modelId(),0);assert.equal(chains[0].len(),1);assert.deepEqual(chains[0].atoms().map(v=>v.id()),[0,1,2]);assert.equal(chains[0].source().authChainId(),'A');assert.equal(residues[0].chainId(),0);assert.equal(residues[0].name(),'ALA');assert.equal(residues[0].kind(),b.ResidueKind.AminoAcid);assert.equal(residues[0].info().canonicalOneLetterCode(),'A');assert.equal(residues[0].code(),b.ResidueCode.ALA);assert.equal(residues[0].source().seqId().seqNum(),1);assert.equal(residues[0].source().seqId().insCode(),null);assert.equal(residues[0].source().labelSeqId(),null);assert.equal(residues[0].len(),3);
 assert.deepEqual(atoms.map(a=>[a.id(),a.residueId(),a.name(),a.altloc(),a.source().serial()]),[[0,0,'CA','A',1],[1,0,'CA','B',2],[2,0,'N',null,3]]);assert.equal(atoms[0].element().symbol(),'C');assert.equal(atoms[0].elementSymbol(),'C');assert.equal(atoms[0].occupancy(),Math.fround(.6));assert.equal(atoms[1].bIso(),30);assert.equal(atoms[0].formalCharge(),0);assert.deepEqual(atoms[0].position(),[1,2,3]);assert.deepEqual(coordinates.positions,[[1,2,3],[4,5,6],[7,8,9]]);assert.equal(coordinates.len(),3);assert.equal(coordinates.isEmpty(),false);const p=coordinates.positions;p[0][0]=99;assert.equal(coordinates.positions[0][0],1);assert.deepEqual(s.atomPosition(0),[1,2,3]);assert.equal(s.atomPosition(4294967295),null);assert.equal(s.residueAtoms(9),null);assert.deepEqual(s.residueAtoms(0).map(v=>v.id()),[0,1,2]);assert.throws(()=>s.atomPosition(-1),RangeError);
 s.free();assert.deepEqual(atoms[1].position(),[4,5,6]);assert.equal(chains[0].residues()[0].name(),'ALA');assert.equal(models[0].chains()[0].atoms().length,3);assert.equal(coordinates.positions[2][2],9);assert.equal(residues[0].atoms()[0].source().serial(),1);
 const empty=b.BioStructure.fromPdb('END\n');assert.deepEqual(empty.atoms(),[]);assert.deepEqual(empty.coordinates().positions,[]);assert.equal(empty.coordinates().isEmpty(),true);
});
test('BIO atom lookups distinguish wildcard, exact labels, element constraints and structured errors without consuming arguments',()=>{
 const s=b.BioStructure.fromPdb(pdb),name=b.AtomName.fromAscii(ascii(' CA ')),label=new b.AltLocLabel(66),request=b.AltLocRequest.Exact(label),any=b.AltLocRequest.Any,c=b.Element.fromSymbol('C'),n=b.Element.fromSymbol('N');
 for(let i=0;i<2;i++){assert.equal(s.findAtom(0,name,any,c)[0],0);assert.equal(s.findAtom(0,name,request,null)[0],1);assert.equal(s.findAtom(0,name,any,n),null);assert.equal(s.atomByAltloc(0,name,label)[0],1);assert.equal(label.value(),66);assert.equal(c.symbol(),'C');}
 assert.equal(s.findAtom(0,b.AtomName.fromAscii(ascii('CA')),any,null),null);assert.equal(s.findAtom(99,name,any,null),null);assert.throws(()=>s.atomByAltloc(0,name,null),e=>e.kind==='AtomNotFound'&&e.detail instanceof b.BioStructureError);assert.throws(()=>s.atomByAltloc(99,name,label),e=>e.kind==='RowReferenceOutOfBounds'&&e.table==='residues'&&e.index===99&&e.tableLen===1&&e.detail.index===99);assert.throws(()=>s.findAtom(0,name,any,{}),TypeError);assert.throws(()=>s.atomByAltloc(0,name,{}),TypeError);
 const blank=b.AtomName.fromAscii(ascii(' N  '));assert.equal(s.findAtom(0,blank,request,null)[0],2);assert.throws(()=>s.atomByAltloc(0,blank,label),e=>e.kind==='AtomNotFound');
});
test('BIO entity lookups preserve source identifiers, subchains, sequence order and detached arrays',()=>{
 const s=b.BioStructure.fromMmcif(cif),[id,entity]=s.findEntity('e1');assert.equal(id,0);assert.equal(entity.id(),0);assert.equal(entity.source().sourceEntityId(),'e1');assert.equal(entity.kind(),b.EntityKind.Polymer);assert.equal(entity.polymerKind(),b.PolymerKind.PeptideL);assert.deepEqual(entity.fullSequence(),['ALA','GLY']);assert.deepEqual(entity.subchains(),['X']);assert.equal(entity.len(),2);const seq=entity.fullSequence();seq[0]='BAD';assert.equal(entity.fullSequence()[0],'ALA');assert.equal(s.findEntityOfSubchain('X')[0],0);assert.equal(s.findEntity('missing'),null);assert.equal(s.findEntityOfSubchain(''),null);const source=s.residues()[0].source();assert.equal(source.seqId().seqNum(),-4);assert.equal(source.labelSeqId(),1);assert.equal(source.subchainId(),'X');assert.equal(source.labelEntityId(),'e1');assert.equal(s.atoms()[0].source().serial(),19);s.free();assert.equal(entity.source().sourceEntityId(),'e1');assert.equal(source.labelEntityId(),'e1');
});
