import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import test from 'node:test';import {pathToFileURL} from 'node:url';
const b=await import(pathToFileURL(process.env.COSMOLKIT_WASM_MODULE).href);b.initSync({module:readFileSync(process.env.COSMOLKIT_WASM_BINARY)});
const pdb='HEADER    STRUCTURE PARTS TEST                    01-JAN-00   1ABC\nREMARK   1 DETACHED SOURCE RETENTION\nATOM      1  CA  ALA A   1       1.000   2.000   3.000  1.00 20.00           C  \nEND\n';
test('BIO parts conversion retains source receiver, read-only format, hierarchy and coordinates',()=>{
 const s=b.BioStructure.fromPdb(pdb),atom=s.atoms()[0];assert.equal(s.validate(),undefined);const parts=s.intoParts();assert.ok(parts instanceof b.BioStructureParts);assert.equal(parts.inputFormat,b.BioCoordinateFormat.Pdb);assert.throws(()=>{parts.inputFormat=b.BioCoordinateFormat.Unknown;},TypeError);assert.equal(s.numAtoms(),1);assert.equal(b.BioStructure.validateParts(parts),undefined);const a=b.BioStructure.fromParts(parts),c=b.BioStructure.fromParts(parts);assert.equal(parts.inputFormat,b.BioCoordinateFormat.Pdb);for(const v of [a,c]){assert.equal(v.validate(),undefined);assert.equal(v.inputFormat(),s.inputFormat());assert.equal(v.name(),s.name());assert.deepEqual(v.coordinates().positions,s.coordinates().positions);assert.deepEqual(v.atoms().map(x=>[x.name(),x.source().serial()]),[['CA',1]]);}s.free();parts.free();assert.deepEqual(atom.position(),[1,2,3]);assert.deepEqual(a.atomPosition(0),[1,2,3]);assert.equal(c.numResidues(),1);
});
test('BIO empty parts remain valid and distinct from missing coordinates',()=>{const s=b.BioStructure.fromPdb('END\n'),p=s.intoParts();b.BioStructure.validateParts(p);const restored=b.BioStructure.fromParts(p);assert.equal(restored.validate(),undefined);assert.equal(restored.models().length,1);assert.equal(restored.models()[0].sourceModelNumber(),1);assert.equal(restored.models()[0].len(),0);assert.deepEqual(restored.coordinates().positions,[]);assert.equal(restored.atomPosition(0),null);assert.equal(s.numModels(),1);});

test('BIO error detail fields absent from a variant use declared null transport',()=>{assert.throws(()=>new b.BioRowSpan(4294967295,1),e=>{assert.equal(e.detail.table,null);assert.equal(e.detail.index,null);assert.equal(e.detail.cause,null);return true;});});
