import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import test from 'node:test';import {pathToFileURL} from 'node:url';
const b=await import(pathToFileURL(process.env.COSMOLKIT_WASM_MODULE).href);b.initSync({module:readFileSync(process.env.COSMOLKIT_WASM_BINARY)});
test('Coordinate2DParams all frozen fields, checked widths and owned sorted map',()=>{
 const p=new b.Coordinate2DParams();assert.deepEqual([...p.coordinateMap],[]);assert.equal(p.canonicalOrientation,false);assert.equal(p.clearExisting2d,true);assert.equal(p.flipsPerSample,0);assert.equal(p.samples,0);assert.equal(p.sampleSeed,0);assert.equal(p.permuteDegreeFour,false);assert.equal(p.forceRdkit,false);assert.equal(p.useRingTemplates,false);
 const map=new Map([[2,new Float64Array([3,4])],[0,[1,2]]]);const q=new b.Coordinate2DParams(map,true,false,5,6,-7,true,true,true);map.get(0)[0]=99;assert.deepEqual([...q.coordinateMap],[[0,[1,2]],[2,[3,4]]]);q.coordinateMap.get(0)[0]=99;assert.equal(q.coordinateMap.get(0)[0],1);for(const [key,value] of Object.entries({canonicalOrientation:true,clearExisting2d:false,flipsPerSample:5,samples:6,sampleSeed:-7,permuteDegreeFour:true,forceRdkit:true,useRingTemplates:true})){assert.equal(q[key],value);assert.throws(()=>{q[key]=value;},TypeError);assert.equal(q[key],value);}
 for(const invalid of [{},new Map([[-1,[1,2]]]),new Map([['0',[1,2]]]),new Map([[0,[1]]]),new Map([[0,['1',2]]])])assert.throws(()=>new b.Coordinate2DParams(invalid));for(const [index,value,type] of [[1,1,TypeError],[3,-1,RangeError],[3,4294967296,RangeError],[4,1.5,RangeError],[5,2147483648,RangeError],[5,-2147483649,RangeError],[6,'true',TypeError]]){const args=Array(9).fill(undefined);args[index]=value;assert.throws(()=>new b.Coordinate2DParams(...args),type);}
});
test('All four layout operations preserve receiver/value distinction and borrowed map parameters',()=>{
 const m=b.Molecule.fromSmiles('CCO'),before=[...m.coordinates2d()],smiles=m.toSmiles(),params=new b.Coordinate2DParams(new Map([[0,[4,5]]]),false,true,0,0,0,false,true,false);const out=m.with2dCoordinates();assert.ok(out instanceof b.Molecule);assert.equal(out.coordinates2d().length,6);assert.deepEqual([...m.coordinates2d()],before);const pinned=m.with2dCoordinatesWithParams(params);assert.deepEqual([...pinned.coordinates2d()].slice(0,2),[4,5]);assert.deepEqual([...m.coordinates2d()],before);assert.equal(m.compute2dCoordinates(),undefined);assert.equal(m.coordinates2d().length,6);assert.equal(m.compute2dCoordinatesWithParams(params),undefined);assert.deepEqual([...m.coordinates2d()].slice(0,2),[4,5]);assert.equal(m.toSmiles(),smiles);assert.deepEqual([...params.coordinateMap],[[0,[4,5]]]);out.free();pinned.free();assert.equal(m.coordinates2d().length,6);
});
test('SVG text and PNG bytes use required checked dimensions and preserve source molecule',()=>{
 for(const text of ['CCO','c1ccccc1','F[C@](Cl)(Br)I']){const m=b.Molecule.fromSmiles(text),before=[...m.coordinates2d()],smiles=m.toSmiles();const svg=m.toSvg(120,100);assert.match(svg,/<svg/);assert.match(svg,/<\/svg>/);assert.ok(svg.includes('https://kit.cosmol.org/'));const png=m.toPng(120,100);assert.ok(png instanceof Uint8Array);assert.deepEqual([...png.slice(0,8)],[137,80,78,71,13,10,26,10]);assert.equal(new DataView(png.buffer,png.byteOffset).getUint32(16),120);assert.equal(new DataView(png.buffer,png.byteOffset).getUint32(20),100);png[0]=0;assert.equal(m.toPng(120,100)[0],137);assert.equal(m.toSvg(120,100),svg);assert.deepEqual([...m.coordinates2d()],before);assert.equal(m.toSmiles(),smiles);}
 const m=b.Molecule.fromSmiles('C');for(const method of ['toSvg','toPng']){assert.throws(()=>m[method](),TypeError);assert.throws(()=>m[method]('120',100),TypeError);for(const n of [-1,4294967296,NaN,1.5])assert.throws(()=>m[method](n,100),RangeError);assert.throws(()=>m[method](0,100),e=>e.name==='DrawingError'&&e.kind==='InvalidDimensions'&&e.width===0&&e.height===100&&e.detail instanceof b.DrawingError);}
});
test('Both file writes preserve typed source filesystem causes and rendering-before-write errors',()=>{
 const m=b.Molecule.fromSmiles('CCO'),before=[...m.coordinates2d()];for(const name of ['writeSvg','writePng']){const path='/binding-test/depiction.'+(name==='writeSvg'?'svg':'png');assert.throws(()=>m[name](path,120,100),e=>{assert.equal(e.name,'DrawingWriteError');assert.equal(e.kind,'Io');assert.equal(e.filename,path);assert.equal(e.errno,null);assert.ok(e.detail instanceof b.DrawingWriteError);assert.equal(e.cause.kind,'Unsupported');return true;});assert.throws(()=>m[name](path,0,100),e=>e.kind==='Drawing'&&e.cause.kind==='InvalidDimensions'&&e.cause.width===0);assert.deepEqual([...m.coordinates2d()],before);}
});
test('Coordinate error retains nested typed layout context and failed in-place receiver',()=>{
 const m=b.Molecule.fromSmiles('CCO');m.compute2dCoordinates();const before=[...m.coordinates2d()],params=new b.Coordinate2DParams(new Map([[99,[1,2]]]));for(const method of ['with2dCoordinatesWithParams','compute2dCoordinatesWithParams'])assert.throws(()=>m[method](params),e=>{assert.equal(e.kind,'Coordinate2D');assert.ok(e.cause.detail instanceof b.Coordinate2DError);assert.equal(e.cause.kind,'Fragment');const cause=e.cause.cause;assert.equal(cause.kind,'AtomIndexOutOfRange');assert.equal(cause.atom,99);assert.equal(cause.atomCount,3);assert.ok(cause.detail instanceof b.Coordinate2DLayoutError);assert.equal(cause.detail.atom,99);assert.equal(cause.detail.atomCount,3);assert.equal(cause.detail.bond,null);assert.equal(cause.detail.cause,null);return true;});assert.deepEqual([...m.coordinates2d()],before);assert.deepEqual([...params.coordinateMap],[[99,[1,2]]]);assert.equal(typeof b.Coordinate2DTemplateError,'function');
});
