import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import test from 'node:test';import {pathToFileURL} from 'node:url';
const b=await import(pathToFileURL(process.env.COSMOLKIT_WASM_MODULE).href);b.initSync({module:readFileSync(process.env.COSMOLKIT_WASM_BINARY)});
test('All forcefield parameter queries and MMFF atom/property methods preserve variants, charges and detached rows',()=>{
 const p=new b.MmffPropertiesParams();assert.equal(p.mmffVariant,'MMFF94');assert.throws(()=>{p.mmffVariant='MMFF94s';},TypeError);assert.throws(()=>new b.MmffPropertiesParams(94),TypeError);
 for(const text of ['CCO','c1ccncc1','CC(=O)N']){const m=b.Molecule.fromSmiles(text),before=m.toSmiles(),props=m.mmffProperties(),explicit=m.mmffPropertiesWithParams(p);assert.equal(m.uffHasAllMoleculeParams(),true);assert.equal(m.mmffHasAllMoleculeParams(),props.isValid());assert.equal(props.variant(),b.MmffVariant.Mmff94);assert.equal(explicit.variant(),props.variant());for(const [i,atom]of props.atoms().entries()){assert.ok(atom instanceof b.MmffAtomProperties);assert.equal(atom.atomType(),props.atomType(i));assert.equal(atom.formalCharge(),props.formalCharge(i));assert.equal(atom.partialCharge(),props.partialCharge(i));assert.equal(explicit.atomType(i),atom.atomType());assert.equal(explicit.partialCharge(i),atom.partialCharge());}assert.equal(m.mmffPropertiesWithParams(new b.MmffPropertiesParams('MMFF94s')).variant(),b.MmffVariant.Mmff94s);assert.equal(m.mmffPropertiesWithParams(new b.MmffPropertiesParams('source-fallback')).variant(),b.MmffVariant.Mmff94);assert.equal(m.toSmiles(),before);const atom=props.atoms()[0];props.free();m.free();assert.ok(Number.isFinite(atom.partialCharge()));assert.ok(explicit.atoms().length>0);}
});
test('Uncovered atom types remain false/invalid and exact query/cache/index failures remain typed',()=>{
 const dummy=b.Molecule.fromSmiles('*');assert.equal(dummy.mmffHasAllMoleculeParams(),false);assert.equal(dummy.mmffProperties().isValid(),false);assert.equal(b.Molecule.new().uffHasAllMoleculeParams(),true);
 const raw=b.Molecule.fromSmilesWithParams('CCO',new b.SmilesParseParams(false,undefined,undefined,undefined,false));assert.throws(()=>raw.uffHasAllMoleculeParams(),e=>e.name==='UffParameterQueryError'&&e.kind==='Cache'&&e.domain==='uff_parameters'&&e.detail instanceof b.UffParameterQueryError&&e.cause.kind==='InvalidDerivedCache');const m=b.Molecule.fromSmiles('CCO'),props=m.mmffProperties();for(const method of ['atomType','formalCharge','partialCharge']){assert.throws(()=>props[method](3),e=>e.name==='MmffMolPropertiesError'&&e.kind==='AtomIndexOutOfRange'&&e.domain==='mmff_properties'&&e.detail instanceof b.MmffMolPropertiesError);assert.throws(()=>props[method](-1),RangeError);assert.throws(()=>props[method](1.5),RangeError);assert.throws(()=>props[method]('0'),TypeError);}assert.equal(m.toSmiles(),'CCO');assert.equal(b.UffParameterErrorKind.Preparation,0);assert.equal(b.UffParameterErrorKind.ParameterTable,1);assert.equal(b.UffParameterErrorKind.Typing,2);
});
