import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import test from 'node:test';import {pathToFileURL} from 'node:url';const b=await import(pathToFileURL(process.env.COSMOLKIT_WASM_MODULE).href);b.initSync({module:readFileSync(process.env.COSMOLKIT_WASM_BINARY)});
test('Both hash APIs retain full u64 bigint and read-only state with checked unsigned rank transport',()=>{
 for(const text of ['CCO','c1ccccc1','[NH4+]','C[C@H](O)F']){const m=b.Molecule.fromSmiles(text),before=m.toSmiles(),hash=m.molecularHash();assert.equal(typeof hash,'bigint');assert.ok(hash>=0n&&hash<=0xffffffffffffffffn);assert.equal(hash,m.molecularHash());const ranks=Array.from({length:m.numAtoms()},(_,i)=>0xffffffff-i);assert.equal(m.molecularHashWithRanks(ranks),m.molecularHashWithRanks(new Uint32Array(ranks)));assert.equal(typeof m.molecularHashWithRanks(ranks),'bigint');assert.equal(m.toSmiles(),before);}
 const m=b.Molecule.fromSmiles('CCO');for(const ranks of [[-1,0,1],[0,1,2**32],[0,1,1.5]])assert.throws(()=>m.molecularHashWithRanks(ranks),RangeError);assert.throws(()=>m.molecularHashWithRanks(['0',1,2]),TypeError);assert.throws(()=>m.molecularHashWithRanks(null),TypeError);
});
test('Hash and CIP errors preserve source categories, exact fields and recursive typed causes',()=>{
 const m=b.Molecule.fromSmiles('CCO');for(const n of [0,2,4])assert.throws(()=>m.molecularHashWithRanks(Array(n).fill(0)),e=>e.name==='MoleculeHashError'&&e.domain==='molecular_hash'&&e.kind==='RankCount'&&e.actual===n&&e.atomCount===3&&e.detail instanceof b.MoleculeHashError&&e.detail.actual===n&&e.detail.atomCount===3);
 assert.throws(()=>b.Molecule.new().molecularHash(),e=>e.kind==='EmptyMolecule');const raw=b.Molecule.fromSmilesWithParams('CCO',new b.SmilesParseParams(false,undefined,undefined,undefined,false));assert.throws(()=>raw.molecularHash(),e=>e.kind==='MissingPreparedValence');assert.equal(typeof raw.molecularHashWithRanks([0,1,2]),'bigint');
 const mapped=b.Molecule.fromSmiles('[Fe]'+'(F)'.repeat(16));assert.throws(()=>mapped.molecularHash(),e=>e.kind==='CipRanks'&&e.cause.name==='CipRankError'&&e.cause.domain==='cip_ranking'&&e.cause.kind==='TooManyNeighbors'&&e.cause.degree===16&&e.cause.maximumSupported===15&&e.cause.atom===0&&e.cause.detail instanceof b.CipRankError&&e.cause.detail.degree===16);assert.equal(typeof mapped.molecularHashWithRanks(Array(17).fill(0)),'bigint');
});
