import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import test from 'node:test';import {pathToFileURL} from 'node:url';const b=await import(pathToFileURL(process.env.COSMOLKIT_WASM_MODULE).href);b.initSync({module:readFileSync(process.env.COSMOLKIT_WASM_BINARY)});
test('Eight hydrogen methods preserve value versus in-place behavior and reusable full typed parameters',()=>{
 const add=new b.AddHsParams(),remove=new b.RemoveHsParams();for(const text of ['CCO','c1ccccc1','[NH4+]','[2H]OC']){const m=b.Molecule.fromSmiles(text),before=m.toSmiles(),count=m.numAtoms(),a=m.withHydrogens(),a2=m.withHydrogensWithParams(add);assert.equal(a.numAtoms(),a2.numAtoms());assert.equal(a.toSmiles(),a2.toSmiles());const r=a.withoutHydrogens(),r2=a.withoutHydrogensWithParams(remove);assert.equal(r.toSmiles(),r2.toSmiles());assert.equal(m.toSmiles(),before);assert.equal(m.numAtoms(),count);assert.equal(m.addHydrogens(),undefined);assert.equal(m.numAtoms(),a.numAtoms());assert.equal(m.removeHydrogens(),undefined);assert.equal(m.toSmiles(),r.toSmiles());assert.equal(m.addHydrogensWithParams(add),undefined);assert.equal(m.numAtoms(),a.numAtoms());assert.equal(m.removeHydrogensWithParams(remove),undefined);assert.equal(m.toSmiles(),r.toSmiles());}
 const m=b.Molecule.fromSmiles('CCO');assert.equal(m.withHydrogens().numAtoms(),9);assert.equal(m.withHydrogensWithParams(new b.AddHsParams(true)).numAtoms(),3);assert.equal(m.withHydrogensWithParams(new b.AddHsParams(false,false,false,false,[2])).numAtoms(),4);const added=m.withHydrogens();added.removeHydrogens();assert.equal(m.numAtoms(),3);assert.equal(added.numAtoms(),3);const out=m.withHydrogens();m.free();assert.equal(out.numAtoms(),9);
 const isotopic=b.Molecule.fromSmiles('[2H]OC'),drop=new b.RemoveHsParams(undefined,undefined,undefined,true);assert.equal(isotopic.withoutHydrogens().numAtoms(),3);assert.equal(isotopic.withoutHydrogensWithParams(drop).numAtoms(),2);isotopic.removeHydrogensWithParams(drop);assert.equal(isotopic.numAtoms(),2);
});
test('Bad hydrogen selection retains structured source error and atomic molecule state for both mutation forms',()=>{
 const m=b.Molecule.fromSmiles('CCO'),before=m.toSmiles(),bad=new b.AddHsParams(false,false,false,false,[99]);for(const fn of [()=>m.withHydrogensWithParams(bad),()=>m.addHydrogensWithParams(bad)]){assert.throws(fn,e=>e.name==='OperationError'&&e.kind==='Hydrogen'&&e.cause.name==='HydrogenError'&&e.cause.domain==='hydrogens'&&e.cause.kind==='OnlyOnAtomOutOfRange'&&e.cause.atom===99&&e.cause.atomCount===3&&e.cause.detail instanceof b.HydrogenError);assert.equal(m.toSmiles(),before);assert.equal(m.numAtoms(),3);}assert.throws(()=>m.withHydrogensWithParams({}),TypeError);assert.throws(()=>m.removeHydrogensWithParams({}),TypeError);assert.equal(m.numAtoms(),3);
});
test('Coordinate addition returns full 3D hydrogen rows without modifying source geometry',()=>{const m=b.Molecule.fromSdf("ethanol\n     RDKit          3D\n\n  3  2  0  0  0  0  0  0  0  0999 V2000\n    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    1.7000    0.2000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    2.5000    1.2000    0.4000 O   0  0  0  0  0  0  0  0  0  0  0  0\n  1  2  1  0\n  2  3  1  0\nM  END\n$$$$\n"),before=Array.from(m.coordinates3d(0)),out=m.withHydrogensWithParams(new b.AddHsParams(false,true,true,true));assert.equal(out.coordinates3d(0).length,27);assert.ok(Array.from(out.coordinates3d(0)).every(Number.isFinite));assert.deepEqual(Array.from(m.coordinates3d(0)),before);});
