import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import test from 'node:test';import {pathToFileURL} from 'node:url';
const b=await import(pathToFileURL(process.env.COSMOLKIT_WASM_MODULE).href);b.initSync({module:readFileSync(process.env.COSMOLKIT_WASM_BINARY)});
test('All six concrete Layered/Pattern calls match batch and preserve detached outputs',()=>{
 const p=new b.LayeredFingerprintParams(),q=new b.PatternFingerprintParams();for(const text of ['CCO','c1ccncc1','CC(=O)N']){const m=b.Molecule.fromSmiles(text),batch=b.MoleculeBatch.fromSmilesList([text]),before=m.toSmiles();assert.deepEqual(m.layeredFingerprint().onBits(),m.layeredFingerprintWithParams(p).onBits());assert.deepEqual(m.layeredFingerprint().onBits(),batch.fingerprintLayeredList()[0].onBits());assert.deepEqual(m.patternFingerprint().onBits(),m.patternFingerprintWithParams(q).onBits());assert.deepEqual(m.patternFingerprint().onBits(),batch.patternFingerprintList()[0].onBits());const out=m.layeredFingerprintWithOutput(),explicit=m.layeredFingerprintWithOutputWithParams(p);assert.ok(out instanceof b.LayeredFingerprintResult);assert.deepEqual(out.fingerprint().onBits(),explicit.fingerprint().onBits());assert.equal(out.atomCounts(),null);assert.equal(m.toSmiles(),before);m.free();assert.ok(out.fingerprint() instanceof b.Fingerprint);}
 const m=b.Molecule.fromSmiles('CCO'),mask=b.Fingerprint.fromOnBits(2048,[674]),seed=new b.LayeredFingerprintParams(undefined,undefined,undefined,undefined,[10,20,30],mask),out=m.layeredFingerprintWithOutputWithParams(seed);assert.deepEqual(out.fingerprint().onBits(),[674]);assert.deepEqual(out.atomCounts(),[11,22,31]);const counts=out.atomCounts();counts[0]=99;assert.deepEqual(out.atomCounts(),[11,22,31]);assert.deepEqual(seed.atomCounts,[10,20,30]);
});
test('All four module-level query calls retain query semantics, parameters and output lifetimes',()=>{
 for(const text of ['[#6]-[#8]','[C,N]~*','c1ccccc1']){const query=b.QueryGraph.fromSmarts(text),p=new b.LayeredFingerprintParams(),q=new b.PatternFingerprintParams(),fp=b.layeredQueryFingerprintWithParams(query,p),out=b.layeredQueryFingerprintWithOutputWithParams(query,p);assert.ok(fp instanceof b.Fingerprint);assert.deepEqual(fp.onBits(),out.fingerprint().onBits());assert.equal(out.atomCounts(),null);assert.deepEqual(b.patternQueryFingerprint(query).onBits(),b.patternQueryFingerprintWithParams(query,q).onBits());assert.equal(b.patternQueryFingerprintWithParams(query,new b.PatternFingerprintParams(128,true)).nBits(),128);query.free();assert.equal(fp.nBits(),2048);}
 const query=b.QueryGraph.fromSmarts('[#6]-[#8]'),seed=new b.LayeredFingerprintParams(undefined,undefined,undefined,128,[0,0]);const out=b.layeredQueryFingerprintWithOutputWithParams(query,seed);assert.equal(out.fingerprint().nBits(),128);assert.equal(out.atomCounts().length,2);
});
test('Concrete and query failures preserve canonical typed errors and input atomicity',()=>{
 const m=b.Molecule.fromSmiles('CCO'),query=b.QueryGraph.fromSmarts('[#6]-[#8]');for(const [p,reason] of [[new b.LayeredFingerprintParams(undefined,0),'minPath==0'],[new b.LayeredFingerprintParams(undefined,5,4),'maxPath<minPath'],[new b.LayeredFingerprintParams(undefined,undefined,undefined,0),'fpSize==0']])for(const run of [()=>m.layeredFingerprintWithParams(p),()=>m.layeredFingerprintWithOutputWithParams(p),()=>b.layeredQueryFingerprintWithParams(query,p),()=>b.layeredQueryFingerprintWithOutputWithParams(query,p)])assert.throws(run,e=>e.name==='LayeredFingerprintError'&&e.kind==='InvalidArguments'&&e.reason===reason&&e.detail instanceof b.LayeredFingerprintError);
 for(const run of [()=>m.patternFingerprintWithParams(new b.PatternFingerprintParams(0)),()=>b.patternQueryFingerprintWithParams(query,new b.PatternFingerprintParams(0))])assert.throws(run,e=>e.name==='PatternFingerprintError'&&e.kind==='EmptyFingerprint'&&e.detail instanceof b.PatternFingerprintError);assert.equal(m.toSmiles(),'CCO');
});
