import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import test from 'node:test';import {pathToFileURL} from 'node:url';
const b=await import(pathToFileURL(process.env.COSMOLKIT_WASM_MODULE).href);b.initSync({module:readFileSync(process.env.COSMOLKIT_WASM_BINARY)});
const sdf="ethanol\n     RDKit          3D\n\n  3  2  0  0  0  0  0  0  0  0999 V2000\n    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    1.7000    0.2000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    2.5000    1.2000    0.4000 O   0  0  0  0  0  0  0  0  0  0  0  0\n  1  2  1  0\n  2  3  1  0\nM  END\n$$$$\n";
test('MMFF complete defaults, signed selectors, all scalar fields and strict input types',()=>{
 const e=new b.MmffEvaluationParams(),s=new b.MmffOptimizationParams(),c=new b.MmffConformerOptimizationParams();assert.deepEqual([e.mmffVariant,e.nonBondedThreshold,e.conformerId,e.ignoreInterfragmentInteractions],['MMFF94',100,null,true]);assert.deepEqual([s.mmffVariant,s.maxIterations,s.nonBondedThreshold,s.conformerId,s.ignoreInterfragmentInteractions],['MMFF94',200,100,null,true]);assert.deepEqual([c.numThreads,c.maxIterations,c.mmffVariant,c.nonBondedThreshold,c.ignoreInterfragmentInteractions],[1,1000,'MMFF94',10,true]);assert.equal(new b.MmffEvaluationParams('MMFF94s',5,-2,false).conformerId,null);assert.equal(new b.MmffOptimizationParams('MMFF94s',2,5,0,false).conformerId,0);assert.equal(new b.MmffConformerOptimizationParams(2,3,'MMFF94s',5,false).ignoreInterfragmentInteractions,false);assert.throws(()=>new b.MmffEvaluationParams(94),TypeError);assert.throws(()=>new b.MmffOptimizationParams('MMFF94',1.5),RangeError);assert.throws(()=>new b.MmffEvaluationParams('MMFF94',100,2**31),RangeError);assert.throws(()=>new b.MmffConformerOptimizationParams(1,2,'MMFF94','5'),TypeError);assert.throws(()=>{s.maxIterations=1;},TypeError);
});
test('MMFF all six calls, both variants, full precision gradients and independent returned molecules',()=>{
 const m=b.Molecule.fromSdf(sdf),before=m.mmffEnergyGradient(),a=m.mmffEnergyGradientWithParams(new b.MmffEvaluationParams());assert.ok(before instanceof b.MmffEnergyGradient);assert.equal(a.energy(),before.energy());assert.deepEqual(a.gradient(),before.gradient());assert.equal(a.gradient().length,9);const detached=a.gradient();detached[0]=Infinity;assert.ok(a.gradient().every(Number.isFinite));
 for(const variant of ['MMFF94','MMFF94s']){const e=m.mmffEnergyGradientWithParams(new b.MmffEvaluationParams(variant,100,-1)),s=m.withMmffOptimizedWithParams(new b.MmffOptimizationParams(variant)),c=m.withMmffOptimizedConformersWithParams(new b.MmffConformerOptimizationParams(1,1000,variant));assert.ok(Number.isFinite(e.energy()));assert.ok(s instanceof b.MmffOptimizeMoleculeResult);assert.equal(s.needsMore(),s.statusCode()>0);assert.ok(c instanceof b.MmffOptimizeMoleculeConfsResult);const rows=c.conformerResults();assert.equal(rows.length,1);assert.ok(rows[0] instanceof b.MmffOptimizeMoleculeConfResult);assert.equal(rows[0].needsMore(),rows[0].statusCode()>0);assert.ok(Number.isFinite(rows[0].energy()));const out=s.molecule(),many=c.molecule();s.free();c.free();assert.equal(out.numAtoms(),3);assert.equal(many.numAtoms(),3);assert.ok(Number.isFinite(rows[0].energy()));}
 const s=m.withMmffOptimized(),s2=m.withMmffOptimizedWithParams(new b.MmffOptimizationParams());assert.equal(s.statusCode(),s2.statusCode());const c=m.withMmffOptimizedConformers(),c2=m.withMmffOptimizedConformersWithParams(new b.MmffConformerOptimizationParams());assert.equal(c.conformerResults()[0].energy(),c2.conformerResults()[0].energy());assert.equal(m.withMmffOptimizedConformersWithParams(new b.MmffConformerOptimizationParams(2)).conformerResults()[0].energy(),c.conformerResults()[0].energy());assert.deepEqual(m.mmffEnergyGradient().gradient(),before.gradient());const out=s.molecule();m.free();assert.ok(Number.isFinite(out.mmffEnergyGradient().energy()));
});
test('Source-invalid types produce null/-1 and real construction errors preserve MMFF cause chains',()=>{
 const dummy=b.Molecule.fromSmiles('*');assert.equal(dummy.mmffEnergyGradient(),null);assert.equal(dummy.mmffEnergyGradientWithParams(new b.MmffEvaluationParams()),null);assert.equal(dummy.withMmffOptimized().statusCode(),-1);assert.equal(dummy.withMmffOptimized().needsMore(),false);assert.deepEqual(dummy.withMmffOptimizedConformers().conformerResults(),[]);
 const d=b.Molecule.fromSdf("helium\n     RDKit          3D\n\n  1  0  0  0  0  0  0  0  0  0999 V2000\n    0.0000    0.0000    0.0000 He  0  0  0  0  0  0  0  0  0  0  0  0\nM  END\n$$$$\n");const rows=d.withMmffOptimizedConformers().conformerResults();assert.equal(rows.length,1);assert.equal(rows[0].statusCode(),-1);assert.equal(rows[0].energy(),-1);
 const m=b.Molecule.fromSmiles('CCO');for(const fn of [()=>m.mmffEnergyGradient(),()=>m.withMmffOptimized(),()=>m.withMmffOptimizedConformers()])assert.throws(fn,e=>e.kind==='MmffOptimization'&&e.cause.name==='MmffOptimizationError'&&e.cause.domain==='mmff_optimization'&&e.cause.detail instanceof b.MmffOptimizationError&&e.cause.cause instanceof Error);const good=b.Molecule.fromSdf(sdf);assert.throws(()=>good.mmffEnergyGradientWithParams(new b.MmffEvaluationParams('MMFF94',100,99)),e=>e.kind==='MmffOptimization'&&e.cause.cause instanceof Error);assert.equal(good.numAtoms(),3);
});
