import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import test from 'node:test';import {pathToFileURL} from 'node:url';
const b=await import(pathToFileURL(process.env.COSMOLKIT_WASM_MODULE).href);b.initSync({module:readFileSync(process.env.COSMOLKIT_WASM_BINARY)});
const sdf='writing\n  COSMolKit         2D\n\n  2  1  0  0  0  0  0  0  0  0999 V2000\n    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    1.4000    0.0000    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0\n  1  2  1  0\nM  END\n>  <NOTE>\nfirst\n\n>  <NOTE>\nsecond\n\n$$$$\n';
function failure(fn,kind){let e;try{fn();}catch(x){e=x;}assert.ok(e instanceof Error);assert.equal(e.name,'MolecularIoError');assert.equal(e.kind,kind);assert.ok(e.detail instanceof b.MolecularIoError);return e;}
test('MOL/SDF default and all full writer policies preserve graph, ordered fields and immutable source',()=>{
 const m=b.Molecule.fromSdf(sdf),r=b.SdfRecord.fromSdf(sdf),before=Array.from(m.coordinates2d()),defaults=new b.MolBlockWriteParams();assert.equal(defaults.format,b.SdfFormat.V2000);assert.equal(defaults.force2d,false);assert.equal(defaults.includeStereo,true);assert.equal(defaults.kekulize,true);assert.equal(defaults.precision,6);assert.equal(defaults.includeCoordinates,true);assert.equal(defaults.coordinateSelection.kind,'Auto');assert.equal(defaults.coordinateSelection.id,null);
 assert.equal(m.toMol(),r.toMol());assert.equal(m.toSdf(),r.toSdf());assert.ok(m.toSdf2d().endsWith('$$$$\n'));const missing3d=failure(()=>m.toSdf3d(),'MolWrite');assert.equal(missing3d.coordinateId,0);assert.equal(missing3d.dimension,'3d');const spatial=b.Molecule.fromXyzBlock('2\n\nC 0 0 0\nO 1.4 0 1\n');assert.ok(spatial.toSdf3d().endsWith('$$$$\n'));assert.deepEqual(Array.from(b.Molecule.fromSdf(spatial.toSdf3d()).coordinates3d(0)),[0,0,0,1.4,0,1]);
 for(const format of [b.SdfFormat.V2000,b.SdfFormat.V3000])for(const force of [false,true])for(const stereo of [false,true])for(const kek of [false,true])for(const precision of [0,2,6])for(const coordinates of [false,true]){
 const p=new b.MolBlockWriteParams(format,force,stereo,kek,precision,b.MolCoordinateSelection.Auto,coordinates);assert.equal(p.format,format);assert.equal(p.force2d,force);assert.equal(p.includeStereo,stereo);assert.equal(p.kekulize,kek);assert.equal(p.precision,precision);assert.equal(p.includeCoordinates,coordinates);
 for(const [name,record] of [['toMolWithParams','toMolWithParams'],['toSdfWithParams','toSdfWithParams']]){const text=m[name](p);assert.equal(text,r[record](p));assert.ok(text.includes(format===b.SdfFormat.V2000?'V2000':'V3000'));const restored=b.Molecule.fromMol(text);assert.equal(restored.numAtoms(),2);assert.equal(restored.numBonds(),1);}
 const out=m.toSdf2dWithParams(p),round=b.SdfRecord.fromSdf(out);assert.deepEqual(round.dataFields(),[['NOTE','first'],['NOTE','second']]);assert.equal(round.molecule().numAtoms(),2);if(coordinates){const e=failure(()=>m.toSdf3dWithParams(p),'MolWrite');assert.equal(e.coordinateId,0);assert.equal(e.dimension,'3d');}else assert.ok(m.toSdf3dWithParams(p).endsWith('$$$$\n'));
 }
 assert.deepEqual(Array.from(m.coordinates2d()),before);assert.equal(m.numAtoms(),2);
});
test('Query records retain typed graph construction, parser semantics, fields and reusable inputs',()=>{
 const q=b.QueryGraph.fromSmarts('[#6,#7]-O'),props=b.SdfRecord.fromSdf(sdf).properties();
 for(let repeat=0;repeat<2;repeat++){const r=b.SdfRecord.fromQueryGraph(q,props);assert.equal(r.graph().kind,'query_graph');assert.equal(r.sourceCoordinateDim(),null);assert.equal(r.title(),'writing');assert.deepEqual(r.dataFields(),[['NOTE','first'],['NOTE','second']]);for(const format of [b.SdfFormat.V2000,b.SdfFormat.V3000]){const p=new b.MolBlockWriteParams(format);for(const text of [r.toMolWithParams(p),r.toSdfWithParams(p)]){const round=b.SdfRecord.fromSdf(text);assert.equal(round.graph().kind,'query_graph');assert.equal(round.queryGraph().numAtoms(),2);}}assert.ok(r.toMol().includes('M  END'));assert.ok(r.toSdf().endsWith('$$$$\n'));}
 q.free();props.free();const r=b.SdfRecord.fromSdf(sdf),other=b.SdfRecord.fromQueryGraph(b.QueryGraph.fromSmarts('*'),r.properties());assert.equal(other.graph().kind,'query_graph');
});
test('Explicit coordinate IDs, output dimensions and disabled geometry preserve typed canonical errors',()=>{
 const m=b.Molecule.fromSdf(sdf);for(const [selection,dimension] of [[b.MolCoordinateSelection.TwoD(99),b.CoordinateDimension.TwoD],[b.MolCoordinateSelection.ThreeD(99),b.CoordinateDimension.ThreeD]]){
 const p=new b.MolBlockWriteParams(undefined,undefined,undefined,undefined,undefined,selection),e=failure(()=>m.toMolWithParams(p),'MolWrite');assert.equal(e.coordinateKind,'MissingCoordinate');assert.equal(e.coordinateId,99);assert.equal(e.cause.kind,'MissingCoordinate');assert.ok(e.cause.detail instanceof b.MolWriteError);assert.equal(e.cause.detail.dimension,dimension);assert.equal(e.cause.detail.id,99);assert.equal(e.cause.detail.cause,null);assert.equal(e.cause.detail.subset,null);
 const disabled=new b.MolBlockWriteParams(undefined,false,true,true,6,selection,false);assert.ok(m.toSdfWithParams(disabled).endsWith('$$$$\n'));assert.equal(selection.id,99);
 }
 const selected=b.MolCoordinateSelection.TwoD(0),p=new b.MolBlockWriteParams(undefined,false,true,true,6,selected);assert.equal(m.toSdfWithParams(p),m.toSdf());assert.equal(p.coordinateSelection.kind,'TwoD');assert.equal(p.coordinateSelection.id,0);
 const e=failure(()=>m.toSdf3dWithParams(p),'MolWrite');assert.equal(e.coordinateKind,'CoordinateDimensionMismatch');assert.equal(e.cause.kind,'CoordinateDimensionMismatch');
});
test('All writer filesystem calls preserve platform errors and formatting validation order',()=>{
 // MolToMolFile opens the file before MolToMolBlock: exercise both error paths.
 const m=b.Molecule.fromSdf(sdf),p=new b.MolBlockWriteParams(),path='/binding.mol';for(const fn of [()=>m.writeMol(path),()=>m.writeMolWithParams(path,p),()=>m.writeSdf(path),()=>m.writeSdfWithParams(path,p)]){const e=failure(fn,'Io');assert.equal(e.detail.filename,path);assert.equal(e.detail.ioKind,'Unsupported');}
 for(const fn of [()=>m.writeSdfFiles('/binding-directory',null),()=>m.writeSdfFilesWithParams('/binding-directory','name.sdf',p)]){const e=failure(fn,'Io');assert.equal(e.detail.filename,'/binding-directory');assert.equal(e.detail.ioKind,'NotFound');}
 const missing=new b.MolBlockWriteParams(undefined,false,true,true,6,b.MolCoordinateSelection.TwoD(99));const e=failure(()=>m.toMolWithParams(missing),'MolWrite');assert.equal(e.coordinateId,99);const io=failure(()=>m.writeMolWithParams(path,missing),'Io');assert.equal(io.detail.filename,path);assert.equal(io.detail.ioKind,'Unsupported');
});
test('Strict enums, numbers, booleans and parameter/query/property classes reject host coercion',()=>{
 for(const v of [-1,0.5,4294967296,Infinity,NaN]){assert.throws(()=>b.MolCoordinateSelection.TwoD(v),RangeError);assert.throws(()=>b.MolCoordinateSelection.ThreeD(v),RangeError);assert.throws(()=>new b.MolBlockWriteParams(undefined,false,true,true,v),RangeError);}for(const v of ['0',null,0n,{}])assert.throws(()=>b.MolCoordinateSelection.TwoD(v),TypeError);
 assert.equal(b.MolCoordinateSelection.ThreeD(4294967295).id,4294967295);assert.equal(new b.MolBlockWriteParams(undefined,false,true,true,4294967295).precision,4294967295);assert.throws(()=>new b.MolBlockWriteParams(2),RangeError);assert.throws(()=>new b.MolBlockWriteParams('0'),TypeError);
 for(const position of [1,2,3,6]){const args=[];args[position]='false';assert.throws(()=>new b.MolBlockWriteParams(...args),TypeError);}for(const v of [null,{},new b.SdfReadParams()])assert.throws(()=>new b.MolBlockWriteParams(undefined,false,true,true,6,v),TypeError);
 const m=b.Molecule.fromSdf(sdf),r=b.SdfRecord.fromSdf(sdf);for(const v of [undefined,null,{},new b.SdfReadParams()]){for(const obj of [m,r])for(const name of ['toMolWithParams','toSdfWithParams'])assert.throws(()=>obj[name](v),TypeError);assert.throws(()=>m.toSdf2dWithParams(v),TypeError);assert.throws(()=>m.toSdf3dWithParams(v),TypeError);assert.throws(()=>m.writeMolWithParams('/x',v),TypeError);assert.throws(()=>m.writeSdfWithParams('/x',v),TypeError);assert.throws(()=>m.writeSdfFilesWithParams('/x',null,v),TypeError);}
 const q=b.QueryGraph.fromSmarts('*'),props=r.properties();for(const v of [null,undefined,{}]){assert.throws(()=>b.SdfRecord.fromQueryGraph(v,props),TypeError);assert.throws(()=>b.SdfRecord.fromQueryGraph(q,v),TypeError);}assert.throws(()=>m.writeSdfFiles('/x',1),TypeError);
});
