import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import test from 'node:test';import {pathToFileURL} from 'node:url';
const b=await import(pathToFileURL(process.env.COSMOLKIT_WASM_MODULE).href);b.initSync({module:readFileSync(process.env.COSMOLKIT_WASM_BINARY)});
const families=[['morganFingerprint','Fingerprint','onBits','fingerprints'],['morganSparseFingerprint','SparseBitFingerprint','onBits','sparseFingerprints'],['morganCountFingerprint','SparseCountFingerprint32','nonzeroElements','counts'],['morganSparseCountFingerprint','SparseCountFingerprint','nonzeroElements','sparseCounts']];
const chain=e=>{let out=[];for(;e;e=e.cause)out.push(e);return out;};
function output(){const out=b.FingerprintAdditionalOutput.new();out.allocateAtomCounts();out.allocateAtomToBits();out.allocateBitInfoMap();out.allocateBitPaths();out.allocateAtomsPerBit();return out;}
test('All twelve scalar Morgan calls and four persistent collection calls retain defaults, ordered null rows and types',()=>{
 const generator=b.MorganFingerprintGenerator.new(),params=new b.MorganFingerprintParams(),call=new b.MorganCallParams();for(const text of ['CCO','c1ccncc1','F[C@](Cl)(Br)I']){const m=b.Molecule.fromSmiles(text),before=m.toSmiles();for(const [name,Class,read,bulk] of families){const base=m[name](),explicit=m[name+'WithParams'](params,null),generated=m[name+'WithGenerator'](generator);assert.ok(base instanceof b[Class]);assert.deepEqual(base[read](),explicit[read]());assert.deepEqual(base[read](),generated[read]());assert.deepEqual(base[read](),m[name+'WithGenerator'](generator,call,null)[read]());const rows=generator[bulk]([m,null,m]);assert.equal(rows.length,3);assert.equal(rows[1],null);assert.deepEqual(rows[0][read](),base[read]());assert.deepEqual(rows[2][read](),base[read]());assert.deepEqual(generator[bulk]([]),[]);assert.deepEqual(generator[bulk]([null,null]),[null,null]);assert.equal(m.toSmiles(),before);}assert.equal(params.generator.radius,3);assert.equal(call.fromAtoms,null);}
});
test('Persistent constructors, JSON, provider snapshots, and all settings methods preserve shared source state and detached params',()=>{
 const p=new b.MorganParams(1),atom=b.MorganAtomInvariantsGenerator.features([]),bond=b.MorganBondInvariantsGenerator.new(false,true);const g=new b.MorganFingerprintGenerator(p,atom,bond),view=g.settings(),other=g.settings();assert.equal(p.radius,1);assert.equal(view.radius,1);assert.equal(typeof g.infoString(),'string');const serialized=g.toJson();const restored=b.MorganFingerprintGenerator.fromJson(serialized);assert.equal(restored.toJson(),serialized);atom.free();bond.free();p.free();
 const fields=[['radius',2],['onlyNonzeroInvariants',true],['includeRedundantEnvironments',true],['includeChirality',true],['countSimulation',true],['fpSize',128],['bitsPerFeature',2],['countBounds',[1,3]]];for(const [name,value] of fields){view['set'+name[0].toUpperCase()+name.slice(1)](value);assert.deepEqual(other[name],value);}const snap=view.params();assert.equal(snap.radius,2);assert.deepEqual(snap.countBounds,[1,3]);view.radius=0;view.countBounds=new Uint32Array([1,2]);assert.equal(other.radius,0);assert.equal(snap.radius,2);assert.deepEqual(snap.countBounds,[1,3]);const bounds=view.countBounds;bounds.push(99);assert.deepEqual(view.countBounds,[1,2]);assert.throws(()=>view.setRadius(-1),RangeError);assert.throws(()=>view.setRadius('2'),TypeError);assert.throws(()=>{view.includeChirality=1;},TypeError);assert.throws(()=>view.setCountBounds([1.5]),RangeError);assert.equal(view.radius,0);g.free();assert.equal(view.radius,0);other.setRadius(4);assert.equal(view.radius,4);assert.equal(snap.radius,2);assert.throws(()=>b.MorganFingerprintGenerator.new({}),TypeError);assert.throws(()=>b.MorganFingerprintGenerator.fromJson('{'),e=>chain(e).some(c=>c.kind==='Parse'));
});
test('Morgan outputs, per-call selection, live settings and explicit providers reach the canonical calculation',()=>{
 const m=b.Molecule.fromSmiles('CCO'),g=b.MorganFingerprintGenerator.new(),p=new b.MorganFingerprintParams(),call=new b.MorganCallParams(),out=output();for(const [name] of families){m[name+'WithParams'](p,out);assert.equal(out.atomCounts().length,3);m[name+'WithGenerator'](g,call,out);assert.equal(out.atomToBits().length,3);assert.ok(out.bitInfoMap() instanceof Map);assert.ok(out.bitPaths() instanceof Map);}assert.deepEqual(m.morganFingerprintWithGenerator(g,new b.MorganCallParams([])).onBits(),[]);assert.deepEqual(m.morganFingerprintWithParams(new b.MorganFingerprintParams(null,[]),null).onBits(),[]);const custom=new b.MorganCallParams(null,null,[1,2,3]);assert.ok(m.morganSparseCountFingerprintWithGenerator(g,custom).nonzeroElements().size>0);const saved=out.atomCounts();out.free();assert.equal(saved.length,3);assert.equal(call.fromAtoms,null);
 const state=g.settings();state.setFpSize(64);assert.equal(m.morganFingerprintWithGenerator(g).nBits(),64);const query=b.QueryGraph.fromSmarts('[#8]'),provider=b.MorganAtomInvariantsGenerator.features([query]),feature=b.MorganFingerprintGenerator.new(new b.MorganParams(0),provider);query.free();provider.free();assert.ok(m.morganFingerprintWithGenerator(feature) instanceof b.Fingerprint);
});
test('Morgan preparation failures, invalid host arguments and unavailable workers preserve exact causes',()=>{
 const m=b.Molecule.fromSmiles('CCO'),raw=b.Molecule.fromSmilesWithParams('CCO',new b.SmilesParseParams(false,undefined,undefined,undefined,false)),g=b.MorganFingerprintGenerator.new(),p=new b.MorganFingerprintParams();for(const [name,,,bulk] of families){for(const run of [()=>raw[name](),()=>raw[name+'WithGenerator'](g),()=>g[bulk]([m,null,raw])])assert.throws(run,e=>e.name==='MorganReadError'&&e.kind==='Preparation'&&e.cause.kind==='MissingPreparedValence');assert.throws(()=>m[name+'WithParams'](p,undefined),TypeError);assert.throws(()=>m[name+'WithGenerator'](g,{}),TypeError);assert.throws(()=>g[bulk]([{}]),TypeError);assert.throws(()=>g[bulk]([m],1.5),RangeError);assert.throws(()=>g[bulk]([m],'1'),TypeError);assert.throws(()=>g[bulk]([m],2),e=>e.name==='MorganReadError'&&e.kind==='Generator'&&chain(e).some(c=>c.kind==='Unsupported'));}assert.equal(m.toSmiles(),'CCO');assert.equal(g.settings().radius,3);
});
