import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import test from 'node:test';import {pathToFileURL} from 'node:url';
const b=await import(pathToFileURL(process.env.COSMOLKIT_WASM_MODULE).href);b.initSync({module:readFileSync(process.env.COSMOLKIT_WASM_BINARY)});
test('All atom-pair constants and full atom-code explanations retain source widths and chirality',()=>{
 const p=b.AtomPairsParameters;assert.equal(typeof p.version(),'string');for(const f of ['numTypeBits','numPiBits','numBranchBits','numChiralBits','codeSize','numPathBits','maxPathLength','numAtomPairFingerprintBits'])assert.ok(Number.isInteger(p[f]()));assert.equal(p.codeSize(),p.numTypeBits()+p.numPiBits()+p.numBranchBits());const types=p.atomTypes();assert.ok(types instanceof Uint32Array);assert.equal(types.length,16);const first=types[0];types[0]=999;assert.equal(p.atomTypes()[0],first);
 const a=b.AtomCodeExplanation.fromCode(33n);assert.equal(a.symbol(),'C');assert.equal(a.branchCount(),1);assert.equal(a.piElectrons(),0);assert.equal(a.chirality(),null);for(const subtract of [-9223372036854775808n,9223372036854775807n])assert.equal(b.AtomCodeExplanation.fromCode(33n,subtract).branchCount(),1);for(const [flag,symbol] of [[0n,''],[1n,'R'],[2n,'S']])assert.equal(b.AtomCodeExplanation.fromCode(33n+(flag<<9n),0n,true).chirality(),symbol);
 assert.throws(()=>b.AtomCodeExplanation.fromCode(33n+(3n<<9n),0n,true),e=>{assert.equal(e.name,'AtomCodeExplanationError');assert.equal(e.domain,'Fingerprint');assert.equal(e.kind,'UnknownChirality');assert.equal(e.code,3);assert.ok(e.detail instanceof b.AtomCodeExplanationError);assert.equal(e.detail.code,3);assert.equal(e.detail.cause,null);return true;});for(const value of [-1n,1n<<64n])assert.throws(()=>b.AtomCodeExplanation.fromCode(value),RangeError);assert.throws(()=>b.AtomCodeExplanation.fromCode(33),TypeError);assert.throws(()=>b.AtomCodeExplanation.fromCode(33n,0),TypeError);assert.throws(()=>b.AtomCodeExplanation.fromCode(33n,1n<<63n),RangeError);assert.throws(()=>b.AtomCodeExplanation.fromCode(33n,0n,1),TypeError);
});
test('Path scores preserve bigint packing, reversal, custom/empty codes and explicit tuple decoding',()=>{
 const m=b.Molecule.fromSmiles('CCCC');const score=m.topologicalTorsionPathScore([0,1,2,3],4);assert.equal(typeof score,'bigint');assert.equal(score,m.topologicalTorsionPathScore(new Uint32Array([3,2,1,0]),4));assert.equal(score,m.topologicalTorsionPathScore([0,1,2,3],4,[]));assert.equal(score,m.topologicalTorsionPathScore([0,1,2,3],4,null));assert.equal(score,m.topologicalTorsionPathScore([0,1,2,3],4,new Uint32Array([33,34,34,33])));assert.deepEqual(b.explainPathScore(score),[['C',1,0],['C',2,0],['C',2,0],['C',1,0]]);assert.deepEqual(b.explainPathScore(score,0),[]);assert.equal(b.explainPathScore(0xffffffffffffffffn,10).length,10);assert.equal(score,m.topologicalTorsionPathScore([0,1,2,3,999],4));const decoded=b.explainPathScore(score);decoded[0][0]='X';assert.equal(b.explainPathScore(score)[0][0],'C');assert.equal(typeof m.topologicalTorsionPathScore([0,1,2,3,0,1,2,3],8),'bigint');assert.equal(m.toSmiles(),'CCCC');
 for(const v of [-1n,1n<<64n])assert.throws(()=>b.explainPathScore(v),RangeError);assert.throws(()=>b.explainPathScore(1),TypeError);assert.throws(()=>b.explainPathScore(1n,-1),RangeError);assert.throws(()=>m.topologicalTorsionPathScore(['0'],1),TypeError);assert.throws(()=>m.topologicalTorsionPathScore([0],4294967296),RangeError);assert.throws(()=>m.topologicalTorsionPathScore([0],1,[4294967296]),RangeError);
});
test('All constructible path-score failure categories retain typed source context and causes',()=>{
 const m=b.Molecule.fromSmiles('CCCC');const cases=[[[[],0],'ZeroSize',{}],[[[0],4],'ShortPath',{actual:1,required:4}],[[[0,1,2,3],4,[33]],'ShortAtomCodes',{actual:1,required:4}],[[[9],1],'AtomIndexOutOfRange',{index:9,atomCount:4}],[[[0],1,[0,0,0,0]],'AtomCodeUnderflow',{index:0,code:0,subtract:1}],[[[0,1,2,3,0,1,2,3,0],9],'PackedCode',{}]];
 for(const [args,kind,fields] of cases)assert.throws(()=>m.topologicalTorsionPathScore(...args),e=>{assert.equal(e.name,'TopologicalTorsionPathScoreError');assert.equal(e.kind,kind);assert.equal(e.domain,'Fingerprint');assert.ok(e.detail instanceof b.TopologicalTorsionPathScoreError);for(const [k,v] of Object.entries(fields)){assert.equal(e[k],v);assert.equal(e.detail[k],v);}assert.equal(e.detail.actual,fields.actual??null);if(kind==='PackedCode'){assert.ok(e.cause instanceof Error);assert.ok(e.detail.cause instanceof Error);}else assert.equal(e.detail.cause,null);return true;});assert.equal(m.toSmiles(),'CCCC');
});
test('Atom-code operation returns a detached result molecule, retains defaults and errors, and never changes receiver',()=>{
 const m=b.Molecule.fromSmiles('CCO'),before=m.toSmiles();const r=m.withAtomPairAtomCode(0);assert.ok(r instanceof b.AtomPairAtomCodeResult);assert.equal(r.code,33);assert.equal(r.molecule.toSmiles(),before);assert.equal(m.toSmiles(),before);assert.equal(m.withAtomPairAtomCode(0,0,false,true).code,r.code);assert.throws(()=>{r.code=0;},TypeError);assert.throws(()=>{r.molecule=m;},TypeError);const n=r.molecule;r.free();m.free();assert.equal(n.toSmiles(),before);
 const other=b.Molecule.fromSmiles('F[C@](Cl)(Br)I');const original=other.toSmiles();const chiral=other.withAtomPairAtomCode(1,0,true,false);assert.equal(typeof chiral.code,'number');assert.equal(other.toSmiles(),original);assert.equal(chiral.molecule.numAtoms(),5);assert.throws(()=>other.withAtomPairAtomCode(99),e=>e.name==='OperationError'&&e.kind==='AtomCode'&&e.cause instanceof Error);for(const v of [-1,4294967296,1.2])assert.throws(()=>other.withAtomPairAtomCode(v),RangeError);assert.throws(()=>other.withAtomPairAtomCode('1'),TypeError);assert.throws(()=>other.withAtomPairAtomCode(1,0,1),TypeError);assert.throws(()=>other.withAtomPairAtomCode(1,0,false,0),TypeError);
});
