import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import test from 'node:test';import {pathToFileURL} from 'node:url';
const b=await import(pathToFileURL(process.env.COSMOLKIT_WASM_MODULE).href);b.initSync({module:readFileSync(process.env.COSMOLKIT_WASM_BINARY)});
const record='batch\n  COSMolKit         2D\n\n  1  0  0  0  0  0  0  0  0  0999 V2000\n    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\nM  END\n$$$$\n';
function failure(fn){let e;try{fn();}catch(x){e=x;}assert.ok(e instanceof Error);assert.equal(e.name,'BatchValidationError');assert.equal(e.domain,'batch');assert.equal(e.kind,'Validation');assert.ok(e.detail instanceof b.BatchValidationError);assert.ok(e.detail.errors>=1);return e;}
test('SDF batch text construction, full read policy and record values preserve order and detached COW',()=>{
 const batch=b.MoleculeBatch.fromSdfRecords(record.repeat(3)),p=new b.SdfReadParams();assert.equal(batch.len(),3);assert.deepEqual(batch.validMask(),[true,true,true]);assert.equal(batch.get(3),null);assert.equal(batch.get(4294967295),null);
 for(const mode of [b.BatchErrorMode.Strict,b.BatchErrorMode.KeepErrors])for(let repeat=0;repeat<2;repeat++){const value=b.MoleculeBatch.fromSdfRecordsWithParams(record.repeat(2),p,mode,null);assert.equal(value.len(),2);assert.deepEqual(value.validMask(),[true,true]);}
 const values=batch.records();assert.equal(values.length,3);for(const value of values){assert.ok(value instanceof b.BatchRecord);assert.equal(value.errorValue(),null);assert.equal(value.moleculeValue().numAtoms(),1);}
 const m=batch.get(0).moleculeValue();m.addHydrogens();assert.equal(m.numAtoms(),5);assert.equal(batch.get(0).moleculeValue().numAtoms(),1);assert.equal(values[0].moleculeValue().numAtoms(),1);batch.free();assert.equal(values[2].moleculeValue().numAtoms(),1);assert.equal(b.MoleculeBatch.fromSdfRecords('').len(),0);
});
test('KeepErrors retains malformed records and Strict reports original indices and causes',()=>{
 const text=record+'bad\nproducer\n\ninvalid counts\njunk\n$$$$\n'+record,p=new b.SdfReadParams(),kept=b.MoleculeBatch.fromSdfRecordsWithParams(text,p,b.BatchErrorMode.KeepErrors,null);assert.deepEqual(kept.validMask(),[true,false,true]);assert.equal(kept.records().length,3);const error=kept.get(1).errorValue();assert.equal(error.index(),1);assert.ok(error.cause() instanceof Error);assert.equal(kept.get(1).moleculeValue(),null);
 const e=failure(()=>b.MoleculeBatch.fromSdfRecords(text));assert.equal(e.detail.errors,1);assert.equal(e.detail.recordErrors[0].index(),1);assert.equal(e.cause.name,'BatchError');assert.equal(e.cause.index,1);assert.ok(e.cause.cause instanceof Error);
});
test('Complete export policy defaults, strict-before-IO ordering and actual platform failures',()=>{
 const batch=b.MoleculeBatch.fromSdfRecords(record),p=new b.BatchExportParams();assert.equal(p.format,b.SdfFormat.V2000);assert.equal(p.errors,b.BatchErrorMode.Strict);assert.equal(p.nJobs,null);assert.equal(p.progressBar,null);
 for(const format of [b.SdfFormat.V2000,b.SdfFormat.V3000])for(const mode of [b.BatchErrorMode.Strict,b.BatchErrorMode.KeepErrors])for(const progress of [null,false,true]){const params=new b.BatchExportParams(format,mode,null,progress);assert.equal(params.format,format);assert.equal(params.errors,mode);assert.equal(params.progressBar,progress);const e=failure(()=>batch.toSdfWithParams('/binding-export.sdf',params,null));assert.equal(e.cause.operation,'batch.write_sdf');assert.ok(e.cause.cause instanceof Error);}
 for(const fn of [()=>batch.toSdf('/binding-export.sdf'),()=>batch.toSdfFiles('/binding-files'),()=>batch.toSdfFilesWithParams('/binding-files',p,['file.sdf'],null)]){const e=failure(fn);assert.ok(e.cause.cause instanceof Error);}
 const names=failure(()=>batch.toSdfFilesWithParams('/binding-files',p,[],null));assert.equal(names.cause.operation,'filenames');assert.ok(names.cause.message.includes('expected 1, got 0'));
 const kept=b.MoleculeBatch.fromSdfRecordsWithParams(record+'bad\nproducer\n\ninvalid counts\njunk\n$$$$\n',new b.SdfReadParams(),b.BatchErrorMode.KeepErrors,null);const e=failure(()=>kept.toSdf('/binding-export.sdf'));assert.equal(e.detail.recordErrors[0].index(),1);assert.equal(e.cause.index,1);
});
test('File reads and lazy reader batches preserve typed errors and canonical validation priority',()=>{
 const p=new b.SdfReadParams(),path='/binding-input.sdf';for(const fn of [()=>b.MoleculeBatch.readSdf(path),()=>b.MoleculeBatch.readSdfWithParams(path,p,b.BatchErrorMode.Strict,null,false),()=>b.MoleculeBatch.readSdfWithParams(path,p,b.BatchErrorMode.KeepErrors,null,true)]){const e=failure(fn);assert.equal(e.cause.operation,'read_sdf');assert.equal(e.cause.cause.name,'MolecularIoError');assert.equal(e.cause.cause.detail.ioKind,'Unsupported');assert.equal(e.cause.cause.filename,path);}
 const reader=b.SdfReader.open(path);for(const fn of [()=>reader.batches(),()=>reader.batches(2,b.BatchErrorMode.KeepErrors,null)]){const e=failure(fn);assert.equal(e.cause.operation,'SdfReader.open');assert.ok(e.cause.cause instanceof Error);}
 for(const fn of [()=>reader.batches(0),()=>reader.batches(1,b.BatchErrorMode.Strict,0),()=>b.MoleculeBatch.fromSdfRecordsWithParams(record,p,b.BatchErrorMode.Strict,0)]){const e=failure(fn);assert.ok(['size','n_jobs'].includes(e.cause.operation));}
 for(const cls of [b.SdfBatchIterator,b.SdfReaderBatchIterator]){assert.equal(typeof cls.prototype.nextBatch,'function');assert.equal(typeof cls.prototype.next,'function');}assert.equal(typeof b.SdfDataset.prototype.batches,'function');assert.equal(typeof b.SdfRecordStream.prototype.batches,'function');
});
test('Explicit thread pool requests retain the canonical WASM platform error',()=>{
 for(const n of [1,2]){const e=failure(()=>b.MoleculeBatch.fromSdfRecordsWithParams(record,new b.SdfReadParams(),b.BatchErrorMode.Strict,n));assert.equal(e.cause.operation,'n_jobs');assert.ok(e.cause.cause instanceof Error);}
});
test('Batch host argument boundaries reject lossy indices, enums and unrelated classes',()=>{
 const p=new b.SdfReadParams(),batch=b.MoleculeBatch.fromSdfRecords(record),exportParams=new b.BatchExportParams();for(const v of [-1,0.5,4294967296,Infinity,NaN]){assert.throws(()=>batch.get(v),RangeError);assert.throws(()=>new b.BatchExportParams(undefined,undefined,v),RangeError);}for(const v of ['0',0n,null,{}])assert.throws(()=>batch.get(v),TypeError);assert.equal(new b.BatchExportParams(undefined,undefined,4294967295).nJobs,4294967295);
 assert.throws(()=>new b.BatchExportParams(2),RangeError);assert.throws(()=>new b.BatchExportParams(undefined,2),RangeError);assert.throws(()=>new b.BatchExportParams(undefined,undefined,null,'false'),TypeError);
 for(const v of [null,undefined,{},exportParams])assert.throws(()=>b.MoleculeBatch.fromSdfRecordsWithParams(record,v,b.BatchErrorMode.Strict,null),TypeError);for(const v of [null,undefined,{},p]){assert.throws(()=>batch.toSdfWithParams('/x',v,null),TypeError);assert.throws(()=>batch.toSdfFilesWithParams('/x',v,null,null),TypeError);}
 assert.throws(()=>b.MoleculeBatch.fromSdfRecordsWithParams(record,p,2,null),RangeError);assert.throws(()=>b.MoleculeBatch.readSdfWithParams('/x',p,b.BatchErrorMode.Strict,null,'false'),TypeError);assert.throws(()=>batch.toSdfFilesWithParams('/x',exportParams,[1],null),TypeError);assert.throws(()=>batch.toSdfWithParams('/x',exportParams,1),TypeError);assert.throws(()=>b.MoleculeBatch.fromDatasetIndices({},[0],b.BatchErrorMode.Strict),TypeError);assert.throws(()=>b.MoleculeBatch.fromDatasetIndices({},[-1],b.BatchErrorMode.Strict),RangeError);
});
