import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import test from 'node:test';import {pathToFileURL} from 'node:url';
const b=await import(pathToFileURL(process.env.COSMOLKIT_WASM_MODULE).href);b.initSync({module:readFileSync(process.env.COSMOLKIT_WASM_BINARY)});
const sdf="binding record\n  COSMolKit         2D\n\n  2  1  0  0  0  0  0  0  0  0999 V2000\n    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    1.4000    0.0000    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0\n  1  2  1  0\nM  END\n>  <NOTE>\nfirst\nline\n\n>  <NOTE>\nsecond\n\n>  <atom.iprop.score>\n-2147483648 2147483647\n\n>  <atom.prop.label>\nalpha n/a\n\n>  <atom.dprop.weight>\n1.25 -2.5\n\n>  <atom.bprop.flag>\n1 0\n\n>  <bond.iprop.edge>\n7\n\n$$$$\n",query="binding record\n  COSMolKit         2D\n\n  2  1  0  0  0  0  0  0  0  0999 V2000\n    0.0000    0.0000    0.0000 *   0  0  0  0  0  0  0  0  0  0  0  0\n    1.4000    0.0000    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0\n  1  2  1  0\nM  END\n>  <NOTE>\nfirst\nline\n\n>  <NOTE>\nsecond\n\n>  <atom.iprop.score>\n-2147483648 2147483647\n\n>  <atom.prop.label>\nalpha n/a\n\n>  <atom.dprop.weight>\n1.25 -2.5\n\n>  <atom.bprop.flag>\n1 0\n\n>  <bond.iprop.edge>\n7\n\n$$$$\n",groups="binding record\n  COSMolKit         2D\n\n  2  1  0  0  0  0  0  0  0  0999 V2000\n    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    1.4000    0.0000    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0\n  1  2  1  0\nM  STY  1   1 SUP\nM  SAL   1  1   1\nM  SBL   1  1   1\nM  SMT   1 Me\nM  SDI   1  4    0.0000    1.0000    2.0000    3.0000\nM  SBV   1   1    0.5000    0.2500\nM  END\n$$$$\n";
test('SDF full params and both coordinate modes retain strict boundary types',()=>{
 const p=new b.SdfReadParams();assert.deepEqual([p.sanitize,p.removeHydrogens,p.strictParsing,p.expandAttachmentPoints,p.processPropertyLists,p.coordinateMode],[true,true,true,false,true,b.SdfCoordinateMode.Preserve]);
 const q=new b.SdfReadParams(false,false,false,true,false,b.SdfCoordinateMode.Require3D);assert.deepEqual([q.sanitize,q.removeHydrogens,q.strictParsing,q.expandAttachmentPoints,q.processPropertyLists,q.coordinateMode],[false,false,false,true,false,b.SdfCoordinateMode.Require3D]);
 assert.throws(()=>new b.SdfReadParams(1),TypeError);for(const n of [-1,1.5,3,4294967296])assert.throws(()=>new b.SdfReadParams(true,true,true,false,true,n),RangeError);
 for(const mode of [b.SdfCoordinateMode.Preserve,b.SdfCoordinateMode.Require2D,b.SdfCoordinateMode.Require3D]){const p=new b.SdfReadParams(true,true,true,false,true,mode),m=b.Molecule.fromSdfWithParams(sdf,p);if(mode===b.SdfCoordinateMode.Require3D)assert.deepEqual(Array.from(m.coordinates3d(0)),[0,0,0,1.4,0,0]);else assert.deepEqual(Array.from(m.coordinates2d()),[0,0,1.4,0]);assert.equal(p.coordinateMode,mode);}
});
test('SDF query-preserving tags, typed wrong-kind failures and independent molecule values',()=>{
 const r=b.SdfRecord.fromSdf(sdf),g=r.graph();assert.equal(r.title(),'binding record');assert.equal(r.index(),0);assert.equal(r.sourceCoordinateDim(),b.CoordinateDimension.TwoD);assert.equal(g.kind,'molecule');assert.equal(g.queryGraph,null);assert.equal(g.molecule.numAtoms(),2);
 for(const m of [r.molecule(),b.Molecule.fromSdf(sdf),b.Molecule.fromMol(sdf.split('>')[0]),b.Molecule.fromMolWithParams(sdf.split('>')[0],new b.SdfReadParams())])assert.equal(m.numAtoms(),2);
 assert.throws(()=>r.queryGraph(),e=>e.kind==='WrongGraphKind'&&e.expected==='query_graph'&&e.actual==='molecule'&&e.detail instanceof b.SdfError&&e.detail.expected==='query_graph');
 const q=b.SdfRecord.fromSdfWithParams(query,new b.SdfReadParams());assert.equal(q.graph().kind,'query_graph');assert.equal(q.graph().molecule,null);assert.equal(q.graph().queryGraph.numAtoms(),2);assert.equal(q.queryGraph().numBonds(),1);assert.throws(()=>q.molecule(),e=>e.kind==='WrongGraphKind'&&e.actual==='query_graph');assert.throws(()=>b.Molecule.fromSdf(query),e=>e.kind==='QueryRecord'&&e.detail instanceof b.SdfError);
 const out=r.molecule();out.addHydrogens();assert.ok(out.numAtoms()>2);assert.equal(r.molecule().numAtoms(),2);r.free();assert.equal(g.molecule.numAtoms(),2);assert.equal(q.queryGraph().numAtoms(),2);
});
test('SDF ordered duplicate fields, property list values, missing rows and exact accessor errors',()=>{
 const r=b.SdfRecord.fromSdf(sdf),p=r.properties();assert.deepEqual(r.dataFields().slice(0,2),[['NOTE','first\nline'],['NOTE','second']]);assert.equal(r.dataField('NOTE'),'first\nline');assert.equal(r.dataField('absent'),null);assert.deepEqual(p.sdfDataFields(),r.dataFields());assert.equal(p.name(),'binding record');assert.equal(p.prop('absent'),null);assert.equal(p.isPropComputed('absent'),false);assert.deepEqual(p.computedPropNames(),['numArom','_StereochemDone']);assert.equal(p.isPropComputed('_StereochemDone'),true);assert.equal(p.isPropComputed('numArom'),true);assert.equal(p.prop('_StereochemDone').asInt(),1);assert.equal(p.prop('numArom').asInt(),0);const map=p.props();assert.ok(map instanceof Map);map.set('NOTE','changed');assert.notEqual(p.prop('NOTE'),'changed');const f=r.dataFields();f[0][1]='changed';assert.equal(r.dataField('NOTE'),'first\nline');
 const lists=p.sdfPropertyLists();assert.equal(lists.length,5);assert.equal(lists[0].target(),b.SdfPropertyListTarget.Atom);assert.equal(lists[0].name(),'score');assert.deepEqual(lists[0].values().map(v=>v.asInt()),[-2147483648,2147483647]);assert.equal(lists[1].values()[0].asString(),'alpha');assert.equal(lists[1].values()[1],null);assert.deepEqual(lists[2].values().map(v=>v.asDouble()),[1.25,-2.5]);assert.deepEqual(lists[3].values().map(v=>v.asBool()),[true,false]);assert.equal(lists[4].target(),b.SdfPropertyListTarget.Bond);assert.equal(lists[4].values()[0].asInt(),7);
 const v=lists[0].values()[0];assert.equal(v.kind(),b.PropertyValueKind.Int);for(const name of ['asString','asUint','asIntVector','asDouble','asBool'])assert.throws(()=>v[name](),e=>e.kind==='KindMismatch'&&e.actual===b.PropertyValueKind.Int&&e.detail instanceof b.PropertyValueError&&e.detail.actual()===b.PropertyValueKind.Int&&e.detail.expected()===e.expected);
 const off=b.SdfRecord.fromSdfWithParams(sdf,new b.SdfReadParams(true,true,true,false,false));assert.deepEqual(off.properties().sdfPropertyLists(),[]);r.free();assert.equal(p.name(),'binding record');assert.equal(v.asInt(),-2147483648);
});
test('SDF group values preserve constructors, detached display points, CStates and lifetimes',()=>{
 const id=b.SubstanceGroupId.new(4294967295),kind=b.SubstanceGroupKind.Generic('CUSTOM'),g=b.SubstanceGroup.new(id,kind);assert.equal(id.index(),4294967295);assert.equal(g.id().index(),4294967295);assert.equal(g.kind().genericValue,'CUSTOM');assert.ok(g.kind().equals(kind));assert.equal(g.display(),null);assert.deepEqual(g.cstates(),[]);assert.deepEqual(g.headCrossingBonds(),[]);assert.deepEqual(g.crossingBondCorrespondence(),[]);
 for(const name of ['Data','Superatom','MultipleGroup','StructuralRepeatUnit','Monomer','Copolymer','Crosslink','Graft','Modification','Mer','AnyPolymer','MixtureComponent','Mixture','Formulation'])assert.ok(b.SubstanceGroupKind[name].equals(b.SubstanceGroupKind[name]));assert.equal(b.SubstanceGroupKind.Data.genericValue,null);
 const bracket=b.SGroupBracket.new([[0,1,2],[3,4,5],[6,7,8]]);assert.deepEqual(bracket.points(),[[0,1,2],[3,4,5],[6,7,8]]);const points=bracket.points();points[0][0]=99;assert.equal(bracket.points()[0][0],0);const state=b.SGroupCState.new(4294967295,[1.25,-2.5,3.75]);assert.equal(state.bond(),4294967295);assert.deepEqual(state.vector(),[1.25,-2.5,3.75]);assert.throws(()=>b.SubstanceGroupId.new(-1),RangeError);assert.throws(()=>b.SubstanceGroup.new({},kind),TypeError);assert.throws(()=>b.SGroupBracket.new([[1,2,3]]),TypeError);
 const r=b.SdfRecord.fromSdf(groups),values=r.substanceGroups();assert.equal(values.length,1);assert.ok(values[0].kind().equals(b.SubstanceGroupKind.Superatom));assert.deepEqual(values[0].display().brackets()[0].points(),[[0,1,0],[2,3,0],[0,0,0]]);assert.equal(values[0].cstates()[0].bond(),0);assert.deepEqual(values[0].cstates()[0].vector(),[.5,.25,0]);r.free();assert.equal(values[0].id().index(),0);
});
test('SDF malformed inputs and WASM filesystem failures retain canonical typed errors',()=>{
 for(const fn of [()=>b.SdfRecord.fromSdf(''),()=>b.Molecule.fromSdf(''),()=>b.Molecule.fromMol('')])assert.throws(fn,e=>e.name==='SdfError'&&e.domain==='io'&&e.kind==='Read'&&e.detail instanceof b.SdfError&&e.cause instanceof Error);
 for(const fn of [()=>b.SdfRecord.fromSdfWithParams(sdf,{}),()=>b.Molecule.fromSdfWithParams(sdf,null),()=>b.Molecule.fromMolWithParams(sdf,undefined),()=>b.Molecule.readMolWithParams('missing',{}),()=>b.Molecule.readSdfWithParams('missing',{})])assert.throws(fn,TypeError);
 const path='/cosmolkit-not-a-wasm-file.sdf';for(const fn of [()=>b.Molecule.readMol(path),()=>b.Molecule.readSdf(path),()=>b.Molecule.readMolWithParams(path,new b.SdfReadParams()),()=>b.Molecule.readSdfWithParams(path,new b.SdfReadParams())])assert.throws(fn,e=>e.name==='MolecularIoError'&&e.kind==='Io'&&e.filename===path&&e.ioKind==='Unsupported'&&e.detail instanceof b.MolecularIoError&&e.detail.filename===path&&e.cause instanceof Error);
});
