import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import test from 'node:test';import {pathToFileURL} from 'node:url';
const b=await import(pathToFileURL(process.env.COSMOLKIT_WASM_MODULE).href);b.initSync({module:readFileSync(process.env.COSMOLKIT_WASM_BINARY)});
test('Complete topological parameters and output requests retain every default, snapshots and numeric error boundary',()=>{
 const p=new b.TopologicalFingerprintParams();assert.deepEqual([p.minPath,p.maxPath,p.fpSize,p.numBitsPerFeature,p.useHs,p.targetDensity,p.minSize,p.branchedPaths,p.useBondOrder,p.atomInvariants,p.fromAtoms],[1,7,2048,2,true,0,128,true,true,null,null]);
 const inv=[1,2,3],roots=[0],q=new b.TopologicalFingerprintParams(2,4,128,1,false,.5,32,false,false,inv,roots);inv[0]=99;roots.push(2);assert.deepEqual([q.minPath,q.maxPath,q.fpSize,q.numBitsPerFeature,q.useHs,q.targetDensity,q.minSize,q.branchedPaths,q.useBondOrder,q.atomInvariants,q.fromAtoms],[2,4,128,1,false,.5,32,false,false,[1,2,3],[0]]);const copy=q.atomInvariants;copy[0]=99;assert.deepEqual(q.atomInvariants,[1,2,3]);assert.throws(()=>{q.minPath=0;},TypeError);assert.throws(()=>new b.TopologicalFingerprintParams(-1),RangeError);assert.throws(()=>new b.TopologicalFingerprintParams(undefined,undefined,undefined,undefined,1),TypeError);assert.throws(()=>new b.TopologicalFingerprintParams(undefined,undefined,undefined,undefined,undefined,'0.5'),TypeError);const req=new b.TopologicalFingerprintOutputRequest();assert.equal(req.atomBits,false);assert.equal(req.bitInfo,false);assert.throws(()=>{req.bitInfo=true;},TypeError);
});
test('All concrete topological calls retain results, request combinations, path mappings and detached lifetimes',()=>{
 for(const text of ['CCO','c1ccncc1','CC(=O)N']){const m=b.Molecule.fromSmiles(text),p=new b.TopologicalFingerprintParams(),before=m.toSmiles(),base=m.fingerprintTopological();assert.ok(base instanceof b.Fingerprint);assert.deepEqual(base.onBits(),m.fingerprintTopologicalWithParams(p).onBits());assert.deepEqual(base.onBits(),m.fingerprintTopologicalWithOutput().fingerprint().onBits());for(const atoms of [false,true])for(const bits of [false,true]){const req=new b.TopologicalFingerprintOutputRequest(atoms,bits),out=m.fingerprintTopologicalWithOutputWithParams(p,req);assert.deepEqual(out.fingerprint().onBits(),base.onBits());if(atoms){const rows=out.atomBits();assert.equal(rows.length,m.numAtoms());rows[0].push(999);assert.ok(!out.atomBits()[0].includes(999));}else assert.throws(()=>out.atomBits(),e=>e.kind==='OutputNotRequested'&&e.field==='atom_bits'&&e.detail instanceof b.TopologicalFingerprintError&&e.detail.field==='atom_bits');if(bits){const map=out.bitInfo();assert.ok(map instanceof Map);assert.ok(map.size>0);assert.ok([...map.keys()].every(k=>typeof k==='number'));map.clear();assert.ok(out.bitInfo().size>0);}else assert.throws(()=>out.bitInfo(),e=>e.kind==='OutputNotRequested'&&e.field==='bit_info');assert.equal(req.atomBits,atoms);assert.equal(req.bitInfo,bits);}assert.equal(m.toSmiles(),before);m.free();assert.equal(base.nBits(),2048);}
});
test('Both topological query modules preserve requested provenance and source argument failures',()=>{
 const p=new b.TopologicalFingerprintParams(),req=new b.TopologicalFingerprintOutputRequest(true,true);for(const text of ['[#6]-[#8]','[C,N]~*','c1ccccc1']){const q=b.QueryGraph.fromSmarts(text),fp=b.fingerprintTopologicalQueryWithParams(q,p),out=b.fingerprintTopologicalQueryWithOutputWithParams(q,p,req);assert.deepEqual(fp.onBits(),out.fingerprint().onBits());assert.ok(Array.isArray(out.atomBits()));assert.ok(out.bitInfo() instanceof Map);q.free();assert.equal(out.fingerprint().nBits(),2048);}
 const m=b.Molecule.fromSmiles('CCO'),q=b.QueryGraph.fromSmarts('[#6]-[#8]');for(const [params,reason] of [[new b.TopologicalFingerprintParams(0),'minPath==0'],[new b.TopologicalFingerprintParams(5,4),'maxPath<minPath'],[new b.TopologicalFingerprintParams(undefined,undefined,0),'fpSize==0'],[new b.TopologicalFingerprintParams(undefined,undefined,undefined,0),'nBitsPerHash==0'],[new b.TopologicalFingerprintParams(undefined,undefined,undefined,undefined,undefined,NaN),'tgtDensity must be finite and non-negative']])for(const run of [()=>m.fingerprintTopologicalWithParams(params),()=>m.fingerprintTopologicalWithOutputWithParams(params,req),()=>b.fingerprintTopologicalQueryWithParams(q,params),()=>b.fingerprintTopologicalQueryWithOutputWithParams(q,params,req)])assert.throws(run,e=>e.name==='TopologicalFingerprintError'&&e.kind==='InvalidArguments'&&e.reason===reason&&e.detail.reason===reason&&e.detail.field===null);assert.equal(m.toSmiles(),'CCO');
 const empty=new b.TopologicalFingerprintParams(undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,null,[]);assert.deepEqual(m.fingerprintTopologicalWithParams(empty).onBits(),[]);
});
