import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import test from 'node:test';import {pathToFileURL} from 'node:url';
const b=await import(pathToFileURL(process.env.COSMOLKIT_WASM_MODULE).href);b.initSync({module:readFileSync(process.env.COSMOLKIT_WASM_BINARY)});
const families=[['fingerprintTopologicalTorsion','Fingerprint','onBits','fingerprints'],['fingerprintTopologicalTorsionSparse','SparseBitFingerprint','onBits','sparseFingerprints'],['fingerprintTopologicalTorsionCount','SparseCountFingerprint32','nonzeroElements','counts'],['fingerprintTopologicalTorsionSparseCount','SparseCountFingerprint','nonzeroElements','sparseCounts']];
const chain=e=>{let out=[];for(;e;e=e.cause)out.push(e);return out;};
function output(){const out=b.FingerprintAdditionalOutput.new();out.allocateAtomCounts();out.allocateAtomToBits();out.allocateBitInfoMap();out.allocateBitPaths();out.allocateAtomsPerBit();return out;}
test('All twelve scalar TopologicalTorsion calls and four persistent collection calls retain defaults, ordered null rows and types',()=>{
 const generator=b.TopologicalTorsionFingerprintGenerator.new(),params=new b.TopologicalTorsionFingerprintParams(),call=new b.TopologicalTorsionCallParams();for(const text of ['CCCCO','c1ccncc1','CC[C@H](F)CO']){const m=b.Molecule.fromSmiles(text),before=m.toSmiles();for(const [name,Class,read,bulk] of families){const base=m[name](),explicit=m[name+'WithParams'](params,null),generated=m[name+'WithGenerator'](generator);assert.ok(base instanceof b[Class]);assert.deepEqual(base[read](),explicit[read]());assert.deepEqual(base[read](),generated[read]());assert.deepEqual(base[read](),m[name+'WithGenerator'](generator,call,null)[read]());const rows=generator[bulk]([m,null,m]);assert.equal(rows.length,3);assert.equal(rows[1],null);assert.deepEqual(rows[0][read](),base[read]());assert.deepEqual(rows[2][read](),base[read]());assert.deepEqual(generator[bulk]([]),[]);assert.deepEqual(generator[bulk]([null,null]),[null,null]);assert.equal(m.toSmiles(),before);}assert.equal(params.generator.torsionAtomCount,4);assert.equal(call.fromAtoms,null);}
});
test('Persistent constructors, JSON, provider snapshots, and all settings methods preserve shared source state and detached params',()=>{
 const p=new b.TopologicalTorsionParams(3),atom=new b.AtomPairAtomInvariantsGenerator(true,true);const g=new b.TopologicalTorsionFingerprintGenerator(p,atom),view=g.settings(),other=g.settings();assert.equal(p.torsionAtomCount,3);assert.equal(view.torsionAtomCount,3);assert.equal(typeof g.infoString(),'string');const serialized=g.toJson();const restored=b.TopologicalTorsionFingerprintGenerator.fromJson(serialized);assert.equal(restored.toJson(),serialized);atom.free();p.free();
 const fields=[['torsionAtomCount',5],['onlyShortestPaths',true],['includeChirality',true],['countSimulation',true],['fpSize',128],['bitsPerFeature',2],['countBounds',[1,3]]];for(const [name,value] of fields){view['set'+name[0].toUpperCase()+name.slice(1)](value);assert.deepEqual(other[name],value);}const snap=view.params();assert.equal(snap.torsionAtomCount,5);assert.deepEqual(snap.countBounds,[1,3]);view.torsionAtomCount=3;view.countBounds=new Uint32Array([1,2]);assert.equal(other.torsionAtomCount,3);assert.equal(snap.torsionAtomCount,5);assert.deepEqual(snap.countBounds,[1,3]);const bounds=view.countBounds;bounds.push(99);assert.deepEqual(view.countBounds,[1,2]);assert.throws(()=>view.setTorsionAtomCount(-1),RangeError);assert.throws(()=>view.setTorsionAtomCount('2'),TypeError);assert.throws(()=>{view.includeChirality=1;},TypeError);assert.throws(()=>view.setCountBounds([1.5]),RangeError);assert.equal(view.torsionAtomCount,3);g.free();assert.equal(view.torsionAtomCount,3);other.setTorsionAtomCount(4);assert.equal(view.torsionAtomCount,4);assert.equal(snap.torsionAtomCount,5);assert.throws(()=>b.TopologicalTorsionFingerprintGenerator.new({}),TypeError);assert.throws(()=>b.TopologicalTorsionFingerprintGenerator.fromJson('{'),e=>chain(e).some(c=>c.kind==='Parse'));
});
test('TopologicalTorsion outputs, per-call selection, live settings and explicit providers reach the canonical calculation',()=>{
 const m=b.Molecule.fromSmiles('CCCCO'),g=b.TopologicalTorsionFingerprintGenerator.new(),p=new b.TopologicalTorsionFingerprintParams(),call=new b.TopologicalTorsionCallParams(),out=output();for(const [name] of families){m[name+'WithParams'](p,out);assert.equal(out.atomCounts().length,5);m[name+'WithGenerator'](g,call,out);assert.equal(out.atomToBits().length,5);assert.ok(out.bitInfoMap() instanceof Map);assert.ok(out.bitPaths() instanceof Map);}assert.deepEqual(m.fingerprintTopologicalTorsionWithGenerator(g,new b.TopologicalTorsionCallParams([])).onBits(),[]);assert.deepEqual(m.fingerprintTopologicalTorsionWithParams(new b.TopologicalTorsionFingerprintParams(null,[]),null).onBits(),[]);const custom=new b.TopologicalTorsionCallParams(null,null,[1,2,3,4,5]);assert.ok(m.fingerprintTopologicalTorsionSparseCountWithGenerator(g,custom).nonzeroElements().size>0);const saved=out.atomCounts();out.free();assert.equal(saved.length,5);assert.equal(call.fromAtoms,null);
 const state=g.settings();state.setFpSize(64);assert.equal(m.fingerprintTopologicalTorsionWithGenerator(g).nBits(),64);const provider=new b.AtomPairAtomInvariantsGenerator(false,true),explicit=b.TopologicalTorsionFingerprintGenerator.new(new b.TopologicalTorsionParams(3),provider);provider.free();assert.ok(m.fingerprintTopologicalTorsionWithGenerator(explicit) instanceof b.Fingerprint);
});
test('TopologicalTorsion preparation failures, invalid host arguments and unavailable workers preserve exact causes',()=>{
 const m=b.Molecule.fromSmiles('CCO'),raw=b.Molecule.fromSmilesWithParams('CCO',new b.SmilesParseParams(false,undefined,undefined,undefined,false)),g=b.TopologicalTorsionFingerprintGenerator.new(),p=new b.TopologicalTorsionFingerprintParams();for(const [name,,,bulk] of families){for(const run of [()=>raw[name](),()=>raw[name+'WithGenerator'](g),()=>g[bulk]([m,null,raw])])assert.throws(run,e=>e.name==='TopologicalTorsionReadError'&&e.kind==='Preparation'&&e.cause.kind==='MissingPreparedValence');assert.throws(()=>m[name+'WithParams'](p,undefined),TypeError);assert.throws(()=>m[name+'WithGenerator'](g,{}),TypeError);assert.throws(()=>g[bulk]([{}]),TypeError);assert.throws(()=>g[bulk]([m],1.5),RangeError);assert.throws(()=>g[bulk]([m],'1'),TypeError);assert.throws(()=>g[bulk]([m],2),e=>e.name==='TopologicalTorsionReadError'&&e.kind==='Generator'&&chain(e).some(c=>c.kind==='Unsupported'));}assert.equal(m.toSmiles(),'CCO');assert.equal(g.settings().torsionAtomCount,4);
});

test('All six legacy calls, path IDs and full immutable configurations retain widths, defaults and source JSON',()=>{
 const m=b.Molecule.fromSmiles('CCCCO'),p=new b.LegacyTopologicalTorsionParams(),q=b.LegacyTopologicalTorsionParams.new();assert.equal(p.torsionAtomCount,4);assert.equal(p.includeChirality,false);assert.equal(p.fpSize,2048);assert.equal(p.bitsPerEntry,4);assert.equal(p.fromAtoms,null);assert.equal(p.ignoreAtoms,null);assert.equal(p.customAtomInvariants,null);
 for(const [name,Class,read] of [['fingerprintTopologicalTorsionLegacy','Fingerprint','onBits'],['fingerprintTopologicalTorsionCountLegacy','SparseCountFingerprint','nonzeroElements'],['fingerprintTopologicalTorsionSparseCountLegacy','SparseCountFingerprint','nonzeroElements']]){const base=m[name]();assert.ok(base instanceof b[Class]);assert.deepEqual(base[read](),m[name+'WithParams'](p)[read]());assert.deepEqual(base[read](),m[name+'WithParams'](q)[read]());const custom=b.LegacyTopologicalTorsionParams.new(3,true,128,2,[0],[],[1,2,3,4,5]);assert.ok(m[name+'WithParams'](custom) instanceof b[Class]);}
 const ids=m.topologicalTorsionIds();assert.deepEqual(ids,m.topologicalTorsionIdsWithParams(4));assert.ok(ids.length>0);assert.ok(ids.every(v=>typeof v==='bigint'));assert.throws(()=>m.topologicalTorsionIdsWithParams(-1),RangeError);
 const params=new b.TopologicalTorsionParams();assert.equal(params.torsionAtomCount,4);assert.equal(params.onlyShortestPaths,false);assert.equal(params.includeChirality,false);assert.equal(params.countSimulation,true);assert.equal(params.fpSize,2048);assert.equal(params.bitsPerFeature,1);assert.deepEqual(params.countBounds,[1,2,4,8]);assert.equal(typeof params.infoString(),'string');const json=params.toJson();assert.equal(params.withJson(json).toJson(),json);assert.throws(()=>params.withJson('{'),e=>chain(e).some(c=>c.kind==='Parse'));const bounds=params.countBounds;bounds.push(99);assert.deepEqual(params.countBounds,[1,2,4,8]);assert.throws(()=>{params.fpSize=1;},TypeError);
 const atom=new b.AtomPairAtomInvariantsGenerator(true,true),full=new b.TopologicalTorsionFingerprintParams(params,[0],[],[1,2,3,4,5],[7,8,9,10],-1,atom,false);assert.deepEqual(full.fromAtoms,[0]);assert.deepEqual(full.ignoreAtoms,[]);assert.deepEqual(full.customAtomInvariants,[1,2,3,4,5]);assert.deepEqual(full.customBondInvariants,[7,8,9,10]);assert.equal(full.conformerId,-1);assert.equal(full.useLegacyStereoPerception,false);atom.free();assert.equal(full.atomInvariantsGenerator.includeChirality,true);assert.equal(full.generator.torsionAtomCount,4);const c=new b.TopologicalTorsionCallParams([0],[],[1,2,3,4,5],[1,2,3,4],-1,false);assert.deepEqual(c.fromAtoms,[0]);assert.deepEqual(c.ignoreAtoms,[]);assert.equal(c.useLegacyStereoPerception,false);assert.equal(c.conformerId,-1);assert.deepEqual(c.customBondInvariants,[1,2,3,4]);assert.throws(()=>new b.TopologicalTorsionCallParams(null,null,null,null,1.5),RangeError);
});
