import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import test from 'node:test';import {pathToFileURL} from 'node:url';
const b=await import(pathToFileURL(process.env.COSMOLKIT_WASM_MODULE).href);b.initSync({module:readFileSync(process.env.COSMOLKIT_WASM_BINARY)});
const sdf="ethanol\n     RDKit          3D\n\n  3  2  0  0  0  0  0  0  0  0999 V2000\n    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    1.7000    0.2000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    2.5000    1.2000    0.4000 O   0  0  0  0  0  0  0  0  0  0  0  0\n  1  2  1  0\n  2  3  1  0\nM  END\n$$$$\n";
test('UFF complete parameter defaults, signed selectors, immutable fields and checked host inputs',()=>{
 const e=new b.UffEvaluationParams(),s=new b.UffOptimizationParams(),c=new b.UffConformerOptimizationParams();
 assert.deepEqual([e.vdwThreshold,e.conformerId,e.ignoreInterfragmentInteractions],[10,null,true]);assert.deepEqual([s.maxIterations,s.vdwThreshold,s.conformerId,s.ignoreInterfragmentInteractions],[1000,10,null,true]);assert.deepEqual([c.numThreads,c.maxIterations,c.vdwThreshold,c.ignoreInterfragmentInteractions],[1,1000,10,true]);
 assert.equal(new b.UffEvaluationParams(5,-2,false).conformerId,null);assert.equal(new b.UffOptimizationParams(2,4,0,false).conformerId,0);assert.equal(new b.UffOptimizationParams(2,4,null,false).conformerId,null);assert.equal(new b.UffConformerOptimizationParams(2,3,4,false).numThreads,2);
 assert.throws(()=>{s.maxIterations=1;},TypeError);assert.throws(()=>new b.UffOptimizationParams(1.5),RangeError);assert.throws(()=>new b.UffOptimizationParams(2**31),RangeError);assert.throws(()=>new b.UffEvaluationParams('10'),TypeError);assert.throws(()=>new b.UffEvaluationParams(10,2**31),RangeError);assert.throws(()=>new b.UffEvaluationParams(10,null,1),TypeError);assert.ok(Number.isNaN(new b.UffEvaluationParams(NaN).vdwThreshold));
});
test('UFF all six operations, full gradients, typed ordered conformer results and independent molecule lifetimes',()=>{
 const m=b.Molecule.fromSdf(sdf),before=m.uffEnergyGradient(),explicit=m.uffEnergyGradientWithParams(new b.UffEvaluationParams());assert.ok(before instanceof b.UffEnergyGradient);assert.equal(before.energy(),explicit.energy());assert.deepEqual(before.gradient(),explicit.gradient());assert.equal(before.gradient().length,9);assert.ok(before.gradient().every(Number.isFinite));const g=before.gradient();g[0]=Infinity;assert.ok(Number.isFinite(before.gradient()[0]));
 assert.deepEqual(m.uffEnergyGradientWithParams(new b.UffEvaluationParams(10,-1)).gradient(),before.gradient());
 const a=m.withUffOptimized(),a2=m.withUffOptimizedWithParams(new b.UffOptimizationParams());assert.ok(a instanceof b.UffOptimizationResult);assert.equal(a.energy(),a2.energy());assert.equal(a.statusCode(),a2.statusCode());assert.equal(a.needsMore(),a.statusCode()>0);assert.ok(a.energy()<=before.energy());
 const c=m.withUffOptimizedConformers(),c2=m.withUffOptimizedConformersWithParams(new b.UffConformerOptimizationParams());assert.ok(c instanceof b.UffConformerOptimizationResult);const workerRows=m.withUffOptimizedConformersWithParams(new b.UffConformerOptimizationParams(2)).conformerResults();assert.equal(workerRows[0].energy(),c.conformerResults()[0].energy());const rows=c.conformerResults();assert.equal(rows.length,1);assert.ok(rows[0] instanceof b.UffConformerResult);assert.equal(rows[0].conformerId(),0);assert.equal(rows[0].energy(),c2.conformerResults()[0].energy());assert.equal(rows[0].needsMore(),rows[0].statusCode()>0);
 assert.deepEqual(m.uffEnergyGradient().gradient(),before.gradient());const out=a.molecule(),many=c.molecule();a.free();c.free();m.free();assert.equal(out.numAtoms(),3);assert.equal(many.numAtoms(),3);assert.ok(Number.isFinite(out.uffEnergyGradient().energy()));assert.ok(Number.isFinite(rows[0].energy()));assert.equal(before.gradient().length,9);
});
test('UFF missing geometry and selected conformer retain typed kind, requested id and source chain',()=>{
 const m=b.Molecule.fromSmiles('CCO');for(const fn of [()=>m.uffEnergyGradient(),()=>m.withUffOptimized()])assert.throws(fn,e=>e.name==='OperationError'&&e.kind==='UffOptimization'&&e.cause.name==='UffOptimizationError'&&e.cause.domain==='uff_optimization'&&e.cause.requested===null&&e.cause.detail.kind() instanceof b.UffOptimizationErrorKind&&e.cause.detail.kind().variant==='MissingConformer');
 const d=b.Molecule.fromSdf(sdf);for(const fn of [()=>d.uffEnergyGradientWithParams(new b.UffEvaluationParams(10,99)),()=>d.withUffOptimizedWithParams(new b.UffOptimizationParams(2,10,99))])assert.throws(fn,e=>{const k=e.cause.detail.kind();return e.cause.requested===99&&k.requested===99&&k.equals(e.cause._kind)&&k.variant==='MissingConformer';});assert.equal(d.numAtoms(),3);
});
