import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import test from 'node:test';import {pathToFileURL} from 'node:url';
const b=await import(pathToFileURL(process.env.COSMOLKIT_WASM_MODULE).href);b.initSync({module:readFileSync(process.env.COSMOLKIT_WASM_BINARY)});
const xyz='2\nXYZ comment\nC 0.125 -1.5 2\nH 1 0 0\n';
const mol2='@<TRIPOS>MOLECULE\nbinding mol2\n3 2 0 0 0\nSMALL\nNO_CHARGES\n\n@<TRIPOS>ATOM\n1 C1 0.0 0.0 0.0 C.3 1 UNL 0.0\n2 O1 1.4 0.0 0.0 O.3 1 UNL 0.0\n3 H1 2.2 0.0 0.0 H 1 UNL 0.0\n@<TRIPOS>BOND\n1 1 2 1\n2 2 3 1\n';
function failure(fn,kind){let e;try{fn();}catch(x){e=x;}assert.ok(e instanceof Error);assert.equal(e.name,'MolecularIoError');assert.equal(e.kind,kind);assert.equal(e.domain,'io');assert.ok(e.detail instanceof b.MolecularIoError);return e;}
test('XYZ all conformer/precision controls preserve canonical output and input coordinates',()=>{
 const m=b.Molecule.fromXyzBlock(xyz),before=Array.from(m.coordinates3d(0)),p=new b.XyzWriteParams();assert.equal(p.conformerId,null);assert.equal(p.precision,6);assert.equal(m.numAtoms(),2);assert.equal(m.numBonds(),0);assert.deepEqual(before,[0.125,-1.5,2,1,0,0]);
 assert.equal(m.toXyz(),'2\n\nC      0.125000   -1.500000    2.000000\nH      1.000000    0.000000    0.000000\n');
 for(const precision of [0,2,6,12]){const p=new b.XyzWriteParams(0,precision);assert.equal(p.conformerId,0);assert.equal(p.precision,precision);const out=m.toXyzWithParams(p);assert.equal(m.toXyzWithParams(p),out);const round=b.Molecule.fromXyzBlock(out);assert.equal(round.numAtoms(),2);assert.equal(round.numBonds(),0);if(precision>=6)assert.deepEqual(Array.from(round.coordinates3d(0)),before);}
 const e=failure(()=>m.toXyzWithParams(new b.XyzWriteParams(99,2)),'XyzWrite');assert.ok(e.cause.detail instanceof b.XyzWriteError);assert.equal(e.cause.kind,'ConformerNotFound');assert.equal(e.cause.id,99);assert.equal(e.cause.detail.id,99);assert.equal(e.cause.detail.cause,null);
 assert.deepEqual(Array.from(m.coordinates3d(0)),before);assert.equal(b.Molecule.new().toXyz(),'');assert.equal(b.Molecule.new().toXyzWithParams(new b.XyzWriteParams(99,6)),'');
});
test('MOL2 full parameter combinations, explicit hydrogen handling and reusable typed inputs',()=>{
 const defaults=new b.Mol2ReadParams();assert.equal(defaults.sanitize,true);assert.equal(defaults.removeHydrogens,true);assert.equal(defaults.cleanupSubstructures,true);assert.equal(defaults.variant,b.Mol2Type.Corina);assert.equal(b.Molecule.fromMol2(mol2).numAtoms(),2);
 for(const sanitize of [false,true])for(const remove of [false,true])for(const cleanup of [false,true]){const p=new b.Mol2ReadParams(sanitize,remove,b.Mol2Type.Corina,cleanup);assert.equal(p.sanitize,sanitize);assert.equal(p.removeHydrogens,remove);assert.equal(p.cleanupSubstructures,cleanup);for(let repeat=0;repeat<2;repeat++){const m=b.Molecule.fromMol2WithParams(mol2,p);assert.equal(m.numAtoms(),sanitize&&remove?2:3);assert.equal(m.numBonds(),sanitize&&remove?1:2);assert.deepEqual(Array.from(m.coordinates3d(0)),sanitize&&remove?[0,0,0,1.4,0,0]:[0,0,0,1.4,0,0,2.2,0,0]);assert.ok(m.toXyz().startsWith(`${m.numAtoms()}\nbinding mol2\n`));}}
});
test('XYZ and MOL2 typed failures preserve fields, recursive causes and error priority',()=>{
 for(const [text,kind] of [['','EmptyBlock'],['bad\n','AtomCount'],['1\ncomment\n','UnexpectedEof'],['1\n\nC 0 0\n','MissingCoordinates'],['1\n\nZz bad 0 0\n','Coordinate'],['1\n\nZz 0 0 0\n','AtomSymbol']]){const e=failure(()=>b.Molecule.fromXyzBlock(text),'XyzRead'),c=e.cause;assert.ok(c.detail instanceof b.XyzReadError);assert.equal(c.kind,kind);assert.equal(c.detail.kind,kind);if(kind==='Coordinate'){assert.equal(c.line,2);assert.equal(c.value,'bad');assert.equal(c.detail.line,2);assert.equal(c.detail.value,'bad');assert.ok(c.cause instanceof Error);}else assert.equal(c.detail.cause,null);if(kind==='AtomCount')assert.equal(c.detail.value,'bad');if(kind==='MissingCoordinates')assert.equal(c.detail.line,2);}
 const empty=failure(()=>b.Molecule.fromMol2(''),'Mol2Read');assert.equal(empty.cause.kind,'Parse');assert.equal(empty.cause.detail.parseDetail,'No MOLECULE block found in Mol2 data');assert.equal(empty.cause.detail.cause,null);
 const unsupported=failure(()=>b.Molecule.fromMol2(mol2.replace('C.3','ANY')),'Mol2Read');assert.equal(unsupported.cause.kind,'Unsupported');assert.ok(unsupported.cause.detail instanceof b.Mol2ReadError);assert.equal(unsupported.cause.feature,'MOL2 query atom types ANY/Du/HEV/HET/HAL in concrete TopologyBlock');assert.equal(unsupported.cause.detail.parseDetail,null);
 const parse=failure(()=>b.Molecule.fromMol2(mol2.replace('C.3','Zz')),'Mol2Read');assert.equal(parse.cause.kind,'Parse');assert.equal(parse.cause.detail.parseDetail,"Element 'Zz' not found");assert.equal(parse.cause.detail.feature,null);
});
test('All file entrypoints preserve actual platform unsupported IO errors',()=>{
 // MolToXYZFile opens the file before MolToXYZBlock: exercise both error paths.
 const m=b.Molecule.fromXyzBlock(xyz),path='/binding-roundtrip.xyz',p=new b.XyzWriteParams(0,2),read=new b.Mol2ReadParams();
 for(const fn of [()=>b.Molecule.readXyz(path),()=>b.Molecule.readMol2(path),()=>b.Molecule.readMol2WithParams(path,read),()=>m.writeXyz(path),()=>m.writeXyzWithParams(path,p)]){const e=failure(fn,'Io');assert.equal(e.filename,path);assert.equal(e.detail.filename,path);assert.equal(e.detail.ioKind,'Unsupported');assert.equal(e.detail.errno,null);assert.ok(e.cause instanceof Error);}
 const missing=new b.XyzWriteParams(99);const e=failure(()=>m.toXyzWithParams(missing),'XyzWrite');assert.equal(e.cause.id,99);const io=failure(()=>m.writeXyzWithParams(path,missing),'Io');assert.equal(io.detail.filename,path);assert.equal(io.detail.ioKind,'Unsupported');
});
test('Strict host numeric/boolean/enum and parameter class boundaries reject coercion',()=>{
 for(const v of [-1,1.1,4294967296,Infinity,NaN]){assert.throws(()=>new b.XyzWriteParams(v),RangeError);assert.throws(()=>new b.XyzWriteParams(null,v),RangeError);}for(const v of ['0',0n,{}]){assert.throws(()=>new b.XyzWriteParams(v),TypeError);assert.throws(()=>new b.XyzWriteParams(null,v),TypeError);}assert.throws(()=>new b.XyzWriteParams(null,null),TypeError);assert.equal(new b.XyzWriteParams(4294967295,4294967295).precision,4294967295);
 for(const v of [null,1,'true',{}]){assert.throws(()=>new b.Mol2ReadParams(v),TypeError);assert.throws(()=>new b.Mol2ReadParams(true,v),TypeError);assert.throws(()=>new b.Mol2ReadParams(true,true,0,v),TypeError);}assert.throws(()=>new b.Mol2ReadParams(true,true,1),RangeError);assert.throws(()=>new b.Mol2ReadParams(true,true,'0'),TypeError);
 const m=b.Molecule.fromXyzBlock(xyz);for(const p of [null,undefined,{},new b.Mol2ReadParams()]){assert.throws(()=>m.toXyzWithParams(p),TypeError);assert.throws(()=>m.writeXyzWithParams('/x',p),TypeError);}for(const p of [null,undefined,{},new b.XyzWriteParams()]){assert.throws(()=>b.Molecule.fromMol2WithParams(mol2,p),TypeError);assert.throws(()=>b.Molecule.readMol2WithParams('/x',p),TypeError);}
});

test('MOL2 postprocessing preserves typed stage and recursive sanitize cause; 2D XYZ output promotes zero z',()=>{
 const bad='@<TRIPOS>MOLECULE\nhypervalent\n6 5 0 0 0\nSMALL\nNO_CHARGES\n\n@<TRIPOS>ATOM\n1 C1 0 0 0 C.3\n'+Array.from({length:5},(_,i)=>`${i+2} F${i+1} ${i+1} 0 0 F\n`).join('')+'@<TRIPOS>BOND\n'+Array.from({length:5},(_,i)=>`${i+1} 1 ${i+2} 1\n`).join('');
 const e=failure(()=>b.Molecule.fromMol2(bad),'Mol2Post');assert.equal(e.stage,'Sanitize');assert.equal(e.detail.stage,'Sanitize');assert.equal(e.cause.kind,'Sanitize');assert.ok(e.cause.detail instanceof b.Mol2PostError);assert.equal(e.cause.detail.stage,'Sanitize');assert.equal(e.cause.cause.name,'SanitizeError');assert.ok(e.cause.message.includes('Explicit valence for atom # 0 C, 5, is greater than permitted'));
 const sdf='flat\n  COSMolKit         2D\n\n  1  0  0  0  0  0  0  0  0  0999 V2000\n    1.2500   -2.5000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\nM  END\n$$$$\n';const flat=b.Molecule.fromSdf(sdf),before=Array.from(flat.coordinates2d()),out=flat.toXyzWithParams(new b.XyzWriteParams(null,2));assert.equal(out,'1\nflat\nC      1.25   -2.50    0.00\n');assert.deepEqual(Array.from(b.Molecule.fromXyzBlock(out).coordinates3d(0)),[1.25,-2.5,0]);assert.deepEqual(Array.from(flat.coordinates2d()),before);
});
