#![cfg(feature = "cap-fingerprints")]
//! Fixed source-native guarded atom-code and COW effect regressions.
use cosmolkit::{
    Atom, AtomId, AtomSpec, Bond, BondId, BondOrder, BondSpec, ChiralTag, CoordinateBlock, Element,
    Molecule, MoleculeProperties, TopologyBlock,
};
use serde_json::Value;

#[test]
fn original_native_complete_guarded_code_and_effects_73_cases() {
    // Fixed observations from the pinned source probe; retain all 72 combinations
    // and the missing-cache case without depending on a generated corpus file.
    let cases: [(
        Option<&str>,
        bool,
        bool,
        bool,
        u32,
        u32,
        Option<&str>,
        bool,
        bool,
        [Option<&str>; 5],
    ); 72] = [
        (
            None,
            false,
            false,
            false,
            0,
            36,
            None,
            false,
            false,
            [None, None, None, None, None],
        ),
        (
            None,
            false,
            false,
            false,
            4,
            32,
            None,
            false,
            false,
            [None, None, None, None, None],
        ),
        (
            None,
            false,
            false,
            false,
            4294967295,
            32,
            None,
            false,
            false,
            [None, None, None, None, None],
        ),
        (
            Some("0"),
            false,
            false,
            false,
            0,
            36,
            Some("0"),
            true,
            true,
            [None, None, None, None, None],
        ),
        (
            Some("0"),
            false,
            false,
            false,
            4,
            32,
            Some("0"),
            true,
            true,
            [None, None, None, None, None],
        ),
        (
            Some("0"),
            false,
            false,
            false,
            4294967295,
            32,
            Some("0"),
            true,
            true,
            [None, None, None, None, None],
        ),
        (
            Some("1"),
            false,
            false,
            false,
            0,
            36,
            Some("1"),
            true,
            true,
            [None, None, None, None, None],
        ),
        (
            Some("1"),
            false,
            false,
            false,
            4,
            32,
            Some("1"),
            true,
            true,
            [None, None, None, None, None],
        ),
        (
            Some("1"),
            false,
            false,
            false,
            4294967295,
            32,
            Some("1"),
            true,
            true,
            [None, None, None, None, None],
        ),
        (
            None,
            true,
            false,
            false,
            0,
            36,
            None,
            false,
            false,
            [None, None, None, None, None],
        ),
        (
            None,
            true,
            false,
            false,
            4,
            32,
            None,
            false,
            false,
            [None, None, None, None, None],
        ),
        (
            None,
            true,
            false,
            false,
            4294967295,
            32,
            None,
            false,
            false,
            [None, None, None, None, None],
        ),
        (
            Some("0"),
            true,
            false,
            false,
            0,
            36,
            Some("0"),
            true,
            true,
            [None, None, None, None, None],
        ),
        (
            Some("0"),
            true,
            false,
            false,
            4,
            32,
            Some("0"),
            true,
            true,
            [None, None, None, None, None],
        ),
        (
            Some("0"),
            true,
            false,
            false,
            4294967295,
            32,
            Some("0"),
            true,
            true,
            [None, None, None, None, None],
        ),
        (
            Some("1"),
            true,
            false,
            false,
            0,
            36,
            Some("1"),
            true,
            true,
            [None, None, None, None, None],
        ),
        (
            Some("1"),
            true,
            false,
            false,
            4,
            32,
            Some("1"),
            true,
            true,
            [None, None, None, None, None],
        ),
        (
            Some("1"),
            true,
            false,
            false,
            4294967295,
            32,
            Some("1"),
            true,
            true,
            [None, None, None, None, None],
        ),
        (
            None,
            false,
            false,
            true,
            0,
            36,
            None,
            false,
            false,
            [None, None, None, None, None],
        ),
        (
            None,
            false,
            false,
            true,
            4,
            32,
            None,
            false,
            false,
            [None, None, None, None, None],
        ),
        (
            None,
            false,
            false,
            true,
            4294967295,
            32,
            None,
            false,
            false,
            [None, None, None, None, None],
        ),
        (
            Some("0"),
            false,
            false,
            true,
            0,
            36,
            Some("0"),
            true,
            true,
            [None, None, None, None, None],
        ),
        (
            Some("0"),
            false,
            false,
            true,
            4,
            32,
            Some("0"),
            true,
            true,
            [None, None, None, None, None],
        ),
        (
            Some("0"),
            false,
            false,
            true,
            4294967295,
            32,
            Some("0"),
            true,
            true,
            [None, None, None, None, None],
        ),
        (
            Some("1"),
            false,
            false,
            true,
            0,
            36,
            Some("1"),
            true,
            true,
            [None, None, None, None, None],
        ),
        (
            Some("1"),
            false,
            false,
            true,
            4,
            32,
            Some("1"),
            true,
            true,
            [None, None, None, None, None],
        ),
        (
            Some("1"),
            false,
            false,
            true,
            4294967295,
            32,
            Some("1"),
            true,
            true,
            [None, None, None, None, None],
        ),
        (
            None,
            true,
            false,
            true,
            0,
            1060,
            Some("1"),
            true,
            false,
            [Some("S"), None, None, None, None],
        ),
        (
            None,
            true,
            false,
            true,
            4,
            1056,
            Some("1"),
            true,
            false,
            [Some("S"), None, None, None, None],
        ),
        (
            None,
            true,
            false,
            true,
            4294967295,
            1056,
            Some("1"),
            true,
            false,
            [Some("S"), None, None, None, None],
        ),
        (
            Some("0"),
            true,
            false,
            true,
            0,
            36,
            Some("0"),
            true,
            true,
            [None, None, None, None, None],
        ),
        (
            Some("0"),
            true,
            false,
            true,
            4,
            32,
            Some("0"),
            true,
            true,
            [None, None, None, None, None],
        ),
        (
            Some("0"),
            true,
            false,
            true,
            4294967295,
            32,
            Some("0"),
            true,
            true,
            [None, None, None, None, None],
        ),
        (
            Some("1"),
            true,
            false,
            true,
            0,
            36,
            Some("1"),
            true,
            true,
            [None, None, None, None, None],
        ),
        (
            Some("1"),
            true,
            false,
            true,
            4,
            32,
            Some("1"),
            true,
            true,
            [None, None, None, None, None],
        ),
        (
            Some("1"),
            true,
            false,
            true,
            4294967295,
            32,
            Some("1"),
            true,
            true,
            [None, None, None, None, None],
        ),
        (
            None,
            false,
            true,
            false,
            0,
            36,
            None,
            false,
            false,
            [None, None, None, None, None],
        ),
        (
            None,
            false,
            true,
            false,
            4,
            32,
            None,
            false,
            false,
            [None, None, None, None, None],
        ),
        (
            None,
            false,
            true,
            false,
            4294967295,
            32,
            None,
            false,
            false,
            [None, None, None, None, None],
        ),
        (
            Some("0"),
            false,
            true,
            false,
            0,
            36,
            Some("0"),
            true,
            true,
            [None, None, None, None, None],
        ),
        (
            Some("0"),
            false,
            true,
            false,
            4,
            32,
            Some("0"),
            true,
            true,
            [None, None, None, None, None],
        ),
        (
            Some("0"),
            false,
            true,
            false,
            4294967295,
            32,
            Some("0"),
            true,
            true,
            [None, None, None, None, None],
        ),
        (
            Some("1"),
            false,
            true,
            false,
            0,
            36,
            Some("1"),
            true,
            true,
            [None, None, None, None, None],
        ),
        (
            Some("1"),
            false,
            true,
            false,
            4,
            32,
            Some("1"),
            true,
            true,
            [None, None, None, None, None],
        ),
        (
            Some("1"),
            false,
            true,
            false,
            4294967295,
            32,
            Some("1"),
            true,
            true,
            [None, None, None, None, None],
        ),
        (
            None,
            true,
            true,
            false,
            0,
            36,
            None,
            false,
            false,
            [None, None, None, None, None],
        ),
        (
            None,
            true,
            true,
            false,
            4,
            32,
            None,
            false,
            false,
            [None, None, None, None, None],
        ),
        (
            None,
            true,
            true,
            false,
            4294967295,
            32,
            None,
            false,
            false,
            [None, None, None, None, None],
        ),
        (
            Some("0"),
            true,
            true,
            false,
            0,
            36,
            Some("0"),
            true,
            true,
            [None, None, None, None, None],
        ),
        (
            Some("0"),
            true,
            true,
            false,
            4,
            32,
            Some("0"),
            true,
            true,
            [None, None, None, None, None],
        ),
        (
            Some("0"),
            true,
            true,
            false,
            4294967295,
            32,
            Some("0"),
            true,
            true,
            [None, None, None, None, None],
        ),
        (
            Some("1"),
            true,
            true,
            false,
            0,
            36,
            Some("1"),
            true,
            true,
            [None, None, None, None, None],
        ),
        (
            Some("1"),
            true,
            true,
            false,
            4,
            32,
            Some("1"),
            true,
            true,
            [None, None, None, None, None],
        ),
        (
            Some("1"),
            true,
            true,
            false,
            4294967295,
            32,
            Some("1"),
            true,
            true,
            [None, None, None, None, None],
        ),
        (
            None,
            false,
            true,
            true,
            0,
            36,
            None,
            false,
            false,
            [None, None, None, None, None],
        ),
        (
            None,
            false,
            true,
            true,
            4,
            32,
            None,
            false,
            false,
            [None, None, None, None, None],
        ),
        (
            None,
            false,
            true,
            true,
            4294967295,
            32,
            None,
            false,
            false,
            [None, None, None, None, None],
        ),
        (
            Some("0"),
            false,
            true,
            true,
            0,
            36,
            Some("0"),
            true,
            true,
            [None, None, None, None, None],
        ),
        (
            Some("0"),
            false,
            true,
            true,
            4,
            32,
            Some("0"),
            true,
            true,
            [None, None, None, None, None],
        ),
        (
            Some("0"),
            false,
            true,
            true,
            4294967295,
            32,
            Some("0"),
            true,
            true,
            [None, None, None, None, None],
        ),
        (
            Some("1"),
            false,
            true,
            true,
            0,
            36,
            Some("1"),
            true,
            true,
            [None, None, None, None, None],
        ),
        (
            Some("1"),
            false,
            true,
            true,
            4,
            32,
            Some("1"),
            true,
            true,
            [None, None, None, None, None],
        ),
        (
            Some("1"),
            false,
            true,
            true,
            4294967295,
            32,
            Some("1"),
            true,
            true,
            [None, None, None, None, None],
        ),
        (
            None,
            true,
            true,
            true,
            0,
            36,
            None,
            false,
            false,
            [None, None, None, None, None],
        ),
        (
            None,
            true,
            true,
            true,
            4,
            32,
            None,
            false,
            false,
            [None, None, None, None, None],
        ),
        (
            None,
            true,
            true,
            true,
            4294967295,
            32,
            None,
            false,
            false,
            [None, None, None, None, None],
        ),
        (
            Some("0"),
            true,
            true,
            true,
            0,
            36,
            Some("0"),
            true,
            true,
            [None, None, None, None, None],
        ),
        (
            Some("0"),
            true,
            true,
            true,
            4,
            32,
            Some("0"),
            true,
            true,
            [None, None, None, None, None],
        ),
        (
            Some("0"),
            true,
            true,
            true,
            4294967295,
            32,
            Some("0"),
            true,
            true,
            [None, None, None, None, None],
        ),
        (
            Some("1"),
            true,
            true,
            true,
            0,
            36,
            Some("1"),
            true,
            true,
            [None, None, None, None, None],
        ),
        (
            Some("1"),
            true,
            true,
            true,
            4,
            32,
            Some("1"),
            true,
            true,
            [None, None, None, None, None],
        ),
        (
            Some("1"),
            true,
            true,
            true,
            4294967295,
            32,
            Some("1"),
            true,
            true,
            [None, None, None, None, None],
        ),
    ];
    let mut rows: Vec<Value> = cases
        .into_iter()
        .map(
            |(
                before,
                tagged,
                legacy,
                include,
                subtract,
                code,
                marker,
                computed,
                ordinary,
                labels,
            )| {
                serde_json::json!({
                    "before": { "marker": before },
                    "tagged": tagged, "legacy": legacy, "include": include,
                    "subtract": subtract, "code": code,
                    "after": { "marker": marker, "marker_in_computed_list": computed,
                        "marker_in_ordinary_list": ordinary, "atom_labels": labels,
                        "user": "preserved" }
                })
            },
        )
        .collect();
    rows.push(serde_json::json!({
        "case": "missing-cache-before-cip", "error": {},
        "before": {"marker": null},
        "after": {"marker": null, "marker_in_computed_list": false,
            "marker_in_ordinary_list": false, "atom_labels": [null, null, null, null, null],
            "user": "preserved"}
    }));
    let mut count = 0;
    let mut errors = 0;
    for row in rows {
        let cache_failure = row.get("case").is_some();
        let tagged = cache_failure || row["tagged"].as_bool().unwrap();
        let atoms = [Element::C, Element::F, Element::CL, Element::BR, Element::I]
            .into_iter()
            .enumerate()
            .map(|(i, element)| {
                let spec = AtomSpec::new(element);
                Atom::from_spec(
                    AtomId::new(i),
                    if i == 0 && tagged {
                        spec.with_chiral_tag(ChiralTag::TetrahedralCcw)
                    } else {
                        spec
                    },
                )
            })
            .collect();
        let bonds = (1..5)
            .map(|i| {
                Bond::from_spec(
                    BondId::new(i - 1),
                    BondSpec::new(AtomId::new(0), AtomId::new(i), BondOrder::Single),
                )
            })
            .collect();
        let topology = TopologyBlock::try_from_parts(atoms, bonds, Vec::new(), Vec::new()).unwrap();
        let mut properties = MoleculeProperties::default()
            .with_prop("user", "preserved")
            .unwrap();
        if let Some(marker) = row["before"]["marker"].as_str() {
            properties.set_prop("_CIPComputed", marker).unwrap();
        }
        let initial =
            Molecule::from_parts(topology, CoordinateBlock::default(), properties).unwrap();
        let source = if cache_failure {
            initial
        } else {
            initial.with_assigned_valence().unwrap()
        };
        let peer = source.clone();
        let result = source.with_atom_pair_atom_code(
            AtomId::new(0),
            if cache_failure {
                u32::MAX
            } else {
                row["subtract"].as_u64().unwrap().try_into().unwrap()
            },
            cache_failure || row["include"].as_bool().unwrap(),
            !cache_failure && row["legacy"].as_bool().unwrap(),
        );
        let molecule = if row.get("error").is_some() {
            errors += 1;
            let error = result.unwrap_err();
            assert_eq!(
                error.to_string(),
                "getValence(ValenceType::EXPLICIT) called without call to calcExplicitValence()"
            );
            &source
        } else {
            let result = result.as_ref().unwrap();
            assert_eq!(
                u64::from(result.code),
                row["code"].as_u64().unwrap(),
                "row{count}"
            );
            &result.molecule
        };
        let effects = &row["after"];
        assert_eq!(
            molecule.properties().prop("_CIPComputed"),
            effects["marker"].as_str(),
            "row{count}"
        );
        assert_eq!(
            molecule.property("user"),
            effects["user"].as_str(),
            "row{count}"
        );
        assert_eq!(
            molecule.properties().is_prop_computed("_CIPComputed"),
            effects["marker_in_computed_list"].as_bool().unwrap()
                && !effects["marker_in_ordinary_list"].as_bool().unwrap(),
            "row{count}"
        );
        for (atom, expected) in molecule
            .atoms()
            .iter()
            .zip(effects["atom_labels"].as_array().unwrap())
        {
            assert_eq!(
                atom.prop("_CIPCode").map(|v| v.as_string().unwrap()),
                expected.as_str(),
                "row{count}"
            );
        }
        assert_eq!(source, peer);
        assert!(std::ptr::eq(source.topology(), peer.topology()));
        assert!(std::ptr::eq(source.properties(), peer.properties()));
        count += 1;
    }
    assert_eq!(count, 73);
    assert_eq!(errors, 1);
}
