[package]
name = "cosmolkit-fingerprints"
description = "Molecular fingerprints over COSMolKit detached model values"
keywords = ["cheminformatics", "fingerprints", "molecular-similarity"]
categories = ["science", "algorithms"]
repository.workspace = true
homepage.workspace = true
license.workspace = true
version.workspace = true
edition.workspace = true
readme = "../cosmolkit/README.md"
documentation = "https://docs.rs/cosmolkit"

[dependencies]
cosmolkit-core = { version = "0.5.0-rc.23", path = "../cosmolkit-core" }
cosmolkit-model = { version = "0.5.0-rc.23", path = "../cosmolkit-model" }
cosmolkit-search = { version = "0.5.0-rc.23", path = "../cosmolkit-search" }

cosmolkit-stereo = { version = "0.5.0-rc.23", path = "../cosmolkit-stereo", default-features = false }

serde_json = { version = "1", features = ["raw_value"] }

[dev-dependencies]
cosmolkit-smiles = { version = "0.5.0-rc.23", path = "../cosmolkit-smiles" }
