[package]
name = "cosmolkit-io"
description = "SDF, PDB, XYZ, and related detached molecular IO"
keywords = ["cheminformatics", "sdf", "pdb", "xyz", "io"]
categories = ["parser-implementations", "science"]
repository.workspace = true
homepage.workspace = true
license.workspace = true
version.workspace = true
edition.workspace = true
readme = "../cosmolkit/README.md"
documentation = "https://docs.rs/cosmolkit"

[dependencies]
cosmolkit-bio = { version = "0.5.0-rc.1", path = "../cosmolkit-bio" }
cosmolkit-model = { version = "0.5.0-rc.1", path = "../cosmolkit-model" }
cosmolkit-types = { version = "0.5.0-rc.1", path = "../cosmolkit-types" }
