//! BIO-PARENT1-44: frozen regressions for the restored legacy residue
//! metadata helpers. Expected values are pasted from the ROOT-frozen
//! 368-row annex — never computed by invoking the methods under test.

use cosmolkit_bio::{ResidueCode, ResidueInfo, ResidueInfoKind, residue_info};

/// Frozen 368-row annex tuple (index, name, kind, one-letter, canonical,
/// parent, modified). Immutable expected data from the packet.
const ANNEX: [(
    usize,
    &str,
    ResidueInfoKind,
    char,
    Option<char>,
    Option<ResidueCode>,
    bool,
); 368] = [
    (
        0,
        "ALA",
        ResidueInfoKind::Aa,
        'A',
        Some('A'),
        Some(ResidueCode::ALA),
        false,
    ),
    (
        1,
        "ARG",
        ResidueInfoKind::Aa,
        'R',
        Some('R'),
        Some(ResidueCode::ARG),
        false,
    ),
    (
        2,
        "ASN",
        ResidueInfoKind::Aa,
        'N',
        Some('N'),
        Some(ResidueCode::ASN),
        false,
    ),
    (
        3,
        "ABA",
        ResidueInfoKind::Aa,
        'a',
        Some('A'),
        Some(ResidueCode::ALA),
        true,
    ),
    (
        4,
        "ASP",
        ResidueInfoKind::Aa,
        'D',
        Some('D'),
        Some(ResidueCode::ASP),
        false,
    ),
    (
        5,
        "ASX",
        ResidueInfoKind::Aa,
        'B',
        Some('B'),
        Some(ResidueCode::ASX),
        false,
    ),
    (
        6,
        "CYS",
        ResidueInfoKind::Aa,
        'C',
        Some('C'),
        Some(ResidueCode::CYS),
        false,
    ),
    (
        7,
        "CSH",
        ResidueInfoKind::Aa,
        's',
        Some('S'),
        Some(ResidueCode::SER),
        true,
    ),
    (
        8,
        "GLN",
        ResidueInfoKind::Aa,
        'Q',
        Some('Q'),
        Some(ResidueCode::GLN),
        false,
    ),
    (
        9,
        "GLU",
        ResidueInfoKind::Aa,
        'E',
        Some('E'),
        Some(ResidueCode::GLU),
        false,
    ),
    (
        10,
        "GLX",
        ResidueInfoKind::Aa,
        'Z',
        Some('Z'),
        Some(ResidueCode::GLX),
        false,
    ),
    (
        11,
        "GLY",
        ResidueInfoKind::Aa,
        'G',
        Some('G'),
        Some(ResidueCode::GLY),
        false,
    ),
    (
        12,
        "HIS",
        ResidueInfoKind::Aa,
        'H',
        Some('H'),
        Some(ResidueCode::HIS),
        false,
    ),
    (
        13,
        "ILE",
        ResidueInfoKind::Aa,
        'I',
        Some('I'),
        Some(ResidueCode::ILE),
        false,
    ),
    (
        14,
        "LEU",
        ResidueInfoKind::Aa,
        'L',
        Some('L'),
        Some(ResidueCode::LEU),
        false,
    ),
    (
        15,
        "LYS",
        ResidueInfoKind::Aa,
        'K',
        Some('K'),
        Some(ResidueCode::LYS),
        false,
    ),
    (
        16,
        "MET",
        ResidueInfoKind::Aa,
        'M',
        Some('M'),
        Some(ResidueCode::MET),
        false,
    ),
    (
        17,
        "MSE",
        ResidueInfoKind::Aa,
        'm',
        Some('M'),
        Some(ResidueCode::MET),
        true,
    ),
    (
        18,
        "ORN",
        ResidueInfoKind::Aa,
        'a',
        Some('A'),
        Some(ResidueCode::ALA),
        true,
    ),
    (
        19,
        "PHE",
        ResidueInfoKind::Aa,
        'F',
        Some('F'),
        Some(ResidueCode::PHE),
        false,
    ),
    (
        20,
        "PRO",
        ResidueInfoKind::Aa,
        'P',
        Some('P'),
        Some(ResidueCode::PRO),
        false,
    ),
    (
        21,
        "SER",
        ResidueInfoKind::Aa,
        'S',
        Some('S'),
        Some(ResidueCode::SER),
        false,
    ),
    (
        22,
        "THR",
        ResidueInfoKind::Aa,
        'T',
        Some('T'),
        Some(ResidueCode::THR),
        false,
    ),
    (
        23,
        "TRP",
        ResidueInfoKind::Aa,
        'W',
        Some('W'),
        Some(ResidueCode::TRP),
        false,
    ),
    (
        24,
        "TYR",
        ResidueInfoKind::Aa,
        'Y',
        Some('Y'),
        Some(ResidueCode::TYR),
        false,
    ),
    (
        25,
        "UNK",
        ResidueInfoKind::Aa,
        'X',
        Some('X'),
        Some(ResidueCode::UNK),
        false,
    ),
    (
        26,
        "VAL",
        ResidueInfoKind::Aa,
        'V',
        Some('V'),
        Some(ResidueCode::VAL),
        false,
    ),
    (
        27,
        "SEC",
        ResidueInfoKind::Aa,
        'U',
        Some('U'),
        Some(ResidueCode::SEC),
        false,
    ),
    (
        28,
        "PYL",
        ResidueInfoKind::Aa,
        'O',
        Some('O'),
        Some(ResidueCode::PYL),
        false,
    ),
    (
        29,
        "SEP",
        ResidueInfoKind::Aa,
        's',
        Some('S'),
        Some(ResidueCode::SER),
        true,
    ),
    (
        30,
        "TPO",
        ResidueInfoKind::Aa,
        't',
        Some('T'),
        Some(ResidueCode::THR),
        true,
    ),
    (
        31,
        "PCA",
        ResidueInfoKind::Aa,
        'e',
        Some('E'),
        Some(ResidueCode::GLU),
        true,
    ),
    (
        32,
        "CSO",
        ResidueInfoKind::Aa,
        'c',
        Some('C'),
        Some(ResidueCode::CYS),
        true,
    ),
    (
        33,
        "PTR",
        ResidueInfoKind::Aa,
        'y',
        Some('Y'),
        Some(ResidueCode::TYR),
        true,
    ),
    (
        34,
        "KCX",
        ResidueInfoKind::Aa,
        'k',
        Some('K'),
        Some(ResidueCode::LYS),
        true,
    ),
    (
        35,
        "CSD",
        ResidueInfoKind::Aa,
        'c',
        Some('C'),
        Some(ResidueCode::CYS),
        true,
    ),
    (
        36,
        "LLP",
        ResidueInfoKind::Aa,
        'k',
        Some('K'),
        Some(ResidueCode::LYS),
        true,
    ),
    (
        37,
        "CME",
        ResidueInfoKind::Aa,
        'c',
        Some('C'),
        Some(ResidueCode::CYS),
        true,
    ),
    (
        38,
        "MLY",
        ResidueInfoKind::Aa,
        'k',
        Some('K'),
        Some(ResidueCode::LYS),
        true,
    ),
    (
        39,
        "DAL",
        ResidueInfoKind::Aad,
        'a',
        Some('A'),
        Some(ResidueCode::ALA),
        true,
    ),
    (
        40,
        "TYS",
        ResidueInfoKind::Aa,
        'y',
        Some('Y'),
        Some(ResidueCode::TYR),
        true,
    ),
    (
        41,
        "OCS",
        ResidueInfoKind::Aa,
        'c',
        Some('C'),
        Some(ResidueCode::CYS),
        true,
    ),
    (
        42,
        "M3L",
        ResidueInfoKind::Aa,
        'k',
        Some('K'),
        Some(ResidueCode::LYS),
        true,
    ),
    (
        43,
        "FME",
        ResidueInfoKind::Aa,
        'm',
        Some('M'),
        Some(ResidueCode::MET),
        true,
    ),
    (
        44,
        "ALY",
        ResidueInfoKind::Aa,
        'k',
        Some('K'),
        Some(ResidueCode::LYS),
        true,
    ),
    (
        45,
        "HYP",
        ResidueInfoKind::Aa,
        'p',
        Some('P'),
        Some(ResidueCode::PRO),
        true,
    ),
    (
        46,
        "CAS",
        ResidueInfoKind::Aa,
        'c',
        Some('C'),
        Some(ResidueCode::CYS),
        true,
    ),
    (
        47,
        "CRO",
        ResidueInfoKind::Aa,
        't',
        Some('T'),
        Some(ResidueCode::THR),
        true,
    ),
    (
        48,
        "CSX",
        ResidueInfoKind::Aa,
        'c',
        Some('C'),
        Some(ResidueCode::CYS),
        true,
    ),
    (
        49,
        "DPR",
        ResidueInfoKind::Aad,
        'p',
        Some('P'),
        Some(ResidueCode::PRO),
        true,
    ),
    (
        50,
        "DGL",
        ResidueInfoKind::Aad,
        'e',
        Some('E'),
        Some(ResidueCode::GLU),
        true,
    ),
    (
        51,
        "DVA",
        ResidueInfoKind::Aad,
        'v',
        Some('V'),
        Some(ResidueCode::VAL),
        true,
    ),
    (
        52,
        "CSS",
        ResidueInfoKind::Aa,
        'c',
        Some('C'),
        Some(ResidueCode::CYS),
        true,
    ),
    (
        53,
        "DPN",
        ResidueInfoKind::Aad,
        'f',
        Some('F'),
        Some(ResidueCode::PHE),
        true,
    ),
    (
        54,
        "DSN",
        ResidueInfoKind::Aad,
        's',
        Some('S'),
        Some(ResidueCode::SER),
        true,
    ),
    (
        55,
        "DLE",
        ResidueInfoKind::Aad,
        'l',
        Some('L'),
        Some(ResidueCode::LEU),
        true,
    ),
    (
        56,
        "HIC",
        ResidueInfoKind::Aa,
        'h',
        Some('H'),
        Some(ResidueCode::HIS),
        true,
    ),
    (
        57,
        "NLE",
        ResidueInfoKind::Aa,
        'l',
        Some('L'),
        Some(ResidueCode::LEU),
        true,
    ),
    (
        58,
        "MVA",
        ResidueInfoKind::Aa,
        'v',
        Some('V'),
        Some(ResidueCode::VAL),
        true,
    ),
    (
        59,
        "MLZ",
        ResidueInfoKind::Aa,
        'k',
        Some('K'),
        Some(ResidueCode::LYS),
        true,
    ),
    (
        60,
        "CR2",
        ResidueInfoKind::Aa,
        'g',
        Some('G'),
        Some(ResidueCode::GLY),
        true,
    ),
    (
        61,
        "SAR",
        ResidueInfoKind::Aa,
        'g',
        Some('G'),
        Some(ResidueCode::GLY),
        true,
    ),
    (
        62,
        "DAR",
        ResidueInfoKind::Aad,
        'r',
        Some('R'),
        Some(ResidueCode::ARG),
        true,
    ),
    (
        63,
        "DLY",
        ResidueInfoKind::Aad,
        'k',
        Some('K'),
        Some(ResidueCode::LYS),
        true,
    ),
    (
        64,
        "YCM",
        ResidueInfoKind::Aa,
        'c',
        Some('C'),
        Some(ResidueCode::CYS),
        true,
    ),
    (
        65,
        "NRQ",
        ResidueInfoKind::Aa,
        'm',
        Some('M'),
        Some(ResidueCode::MET),
        true,
    ),
    (
        66,
        "CGU",
        ResidueInfoKind::Aa,
        'e',
        Some('E'),
        Some(ResidueCode::GLU),
        true,
    ),
    (
        67,
        "0TD",
        ResidueInfoKind::Aa,
        'd',
        Some('D'),
        Some(ResidueCode::ASP),
        true,
    ),
    (
        68,
        "MLE",
        ResidueInfoKind::Aa,
        'l',
        Some('L'),
        Some(ResidueCode::LEU),
        true,
    ),
    (
        69,
        "DAS",
        ResidueInfoKind::Aad,
        'd',
        Some('D'),
        Some(ResidueCode::ASP),
        true,
    ),
    (
        70,
        "DTR",
        ResidueInfoKind::Aad,
        'w',
        Some('W'),
        Some(ResidueCode::TRP),
        true,
    ),
    (
        71,
        "CXM",
        ResidueInfoKind::Aa,
        'm',
        Some('M'),
        Some(ResidueCode::MET),
        true,
    ),
    (
        72,
        "TPQ",
        ResidueInfoKind::Aa,
        'y',
        Some('Y'),
        Some(ResidueCode::TYR),
        true,
    ),
    (
        73,
        "DCY",
        ResidueInfoKind::Aad,
        'c',
        Some('C'),
        Some(ResidueCode::CYS),
        true,
    ),
    (
        74,
        "DSG",
        ResidueInfoKind::Aad,
        'n',
        Some('N'),
        Some(ResidueCode::ASN),
        true,
    ),
    (
        75,
        "DTY",
        ResidueInfoKind::Aad,
        'y',
        Some('Y'),
        Some(ResidueCode::TYR),
        true,
    ),
    (
        76,
        "DHI",
        ResidueInfoKind::Aad,
        'h',
        Some('H'),
        Some(ResidueCode::HIS),
        true,
    ),
    (
        77,
        "MEN",
        ResidueInfoKind::Aa,
        'n',
        Some('N'),
        Some(ResidueCode::ASN),
        true,
    ),
    (
        78,
        "DTH",
        ResidueInfoKind::Aad,
        't',
        Some('T'),
        Some(ResidueCode::THR),
        true,
    ),
    (
        79,
        "SAC",
        ResidueInfoKind::Aa,
        's',
        Some('S'),
        Some(ResidueCode::SER),
        true,
    ),
    (
        80,
        "DGN",
        ResidueInfoKind::Aad,
        'q',
        Some('Q'),
        Some(ResidueCode::GLN),
        true,
    ),
    (
        81,
        "AIB",
        ResidueInfoKind::Aa,
        'a',
        Some('A'),
        Some(ResidueCode::ALA),
        true,
    ),
    (
        82,
        "SMC",
        ResidueInfoKind::Aa,
        'c',
        Some('C'),
        Some(ResidueCode::CYS),
        true,
    ),
    (
        83,
        "IAS",
        ResidueInfoKind::Aa,
        'd',
        Some('D'),
        Some(ResidueCode::ASP),
        true,
    ),
    (
        84,
        "CIR",
        ResidueInfoKind::Aa,
        'r',
        Some('R'),
        Some(ResidueCode::ARG),
        true,
    ),
    (
        85,
        "BMT",
        ResidueInfoKind::Aa,
        't',
        Some('T'),
        Some(ResidueCode::THR),
        true,
    ),
    (
        86,
        "DIL",
        ResidueInfoKind::Aad,
        'i',
        Some('I'),
        Some(ResidueCode::ILE),
        true,
    ),
    (
        87,
        "FGA",
        ResidueInfoKind::Aa,
        'e',
        Some('E'),
        Some(ResidueCode::GLU),
        true,
    ),
    (
        88,
        "PHI",
        ResidueInfoKind::Aa,
        'f',
        Some('F'),
        Some(ResidueCode::PHE),
        true,
    ),
    (
        89,
        "CRQ",
        ResidueInfoKind::Aa,
        'q',
        Some('Q'),
        Some(ResidueCode::GLN),
        true,
    ),
    (
        90,
        "SME",
        ResidueInfoKind::Aa,
        'm',
        Some('M'),
        Some(ResidueCode::MET),
        true,
    ),
    (
        91,
        "GHP",
        ResidueInfoKind::Aa,
        'g',
        Some('G'),
        Some(ResidueCode::GLY),
        true,
    ),
    (
        92,
        "MHO",
        ResidueInfoKind::Aa,
        'm',
        Some('M'),
        Some(ResidueCode::MET),
        true,
    ),
    (
        93,
        "NEP",
        ResidueInfoKind::Aa,
        'h',
        Some('H'),
        Some(ResidueCode::HIS),
        true,
    ),
    (
        94,
        "TRQ",
        ResidueInfoKind::Aa,
        'w',
        Some('W'),
        Some(ResidueCode::TRP),
        true,
    ),
    (
        95,
        "TOX",
        ResidueInfoKind::Aa,
        'w',
        Some('W'),
        Some(ResidueCode::TRP),
        true,
    ),
    (
        96,
        "ALC",
        ResidueInfoKind::Aa,
        'a',
        Some('A'),
        Some(ResidueCode::ALA),
        true,
    ),
    (97, "3FG", ResidueInfoKind::Aa, ' ', None, None, true),
    (
        98,
        "SCH",
        ResidueInfoKind::Aa,
        'c',
        Some('C'),
        Some(ResidueCode::CYS),
        true,
    ),
    (
        99,
        "MDO",
        ResidueInfoKind::Aa,
        'a',
        Some('A'),
        Some(ResidueCode::ALA),
        true,
    ),
    (
        100,
        "MAA",
        ResidueInfoKind::Aa,
        'a',
        Some('A'),
        Some(ResidueCode::ALA),
        true,
    ),
    (
        101,
        "GYS",
        ResidueInfoKind::Aa,
        's',
        Some('S'),
        Some(ResidueCode::SER),
        true,
    ),
    (
        102,
        "MK8",
        ResidueInfoKind::Aa,
        'l',
        Some('L'),
        Some(ResidueCode::LEU),
        true,
    ),
    (
        103,
        "CR8",
        ResidueInfoKind::Aa,
        'h',
        Some('H'),
        Some(ResidueCode::HIS),
        true,
    ),
    (
        104,
        "KPI",
        ResidueInfoKind::Aa,
        'k',
        Some('K'),
        Some(ResidueCode::LYS),
        true,
    ),
    (
        105,
        "SCY",
        ResidueInfoKind::Aa,
        'c',
        Some('C'),
        Some(ResidueCode::CYS),
        true,
    ),
    (
        106,
        "DHA",
        ResidueInfoKind::Aa,
        's',
        Some('S'),
        Some(ResidueCode::SER),
        true,
    ),
    (
        107,
        "OMY",
        ResidueInfoKind::Aa,
        'y',
        Some('Y'),
        Some(ResidueCode::TYR),
        true,
    ),
    (
        108,
        "CAF",
        ResidueInfoKind::Aa,
        'c',
        Some('C'),
        Some(ResidueCode::CYS),
        true,
    ),
    (
        109,
        "0AF",
        ResidueInfoKind::Aa,
        'w',
        Some('W'),
        Some(ResidueCode::TRP),
        true,
    ),
    (
        110,
        "SNN",
        ResidueInfoKind::Aa,
        'n',
        Some('N'),
        Some(ResidueCode::ASN),
        true,
    ),
    (
        111,
        "MHS",
        ResidueInfoKind::Aa,
        'h',
        Some('H'),
        Some(ResidueCode::HIS),
        true,
    ),
    (112, "MLU", ResidueInfoKind::Aad, ' ', None, None, true),
    (
        113,
        "SNC",
        ResidueInfoKind::Aa,
        'c',
        Some('C'),
        Some(ResidueCode::CYS),
        true,
    ),
    (
        114,
        "PHD",
        ResidueInfoKind::Aa,
        'd',
        Some('D'),
        Some(ResidueCode::ASP),
        true,
    ),
    (
        115,
        "B3E",
        ResidueInfoKind::Aa,
        'e',
        Some('E'),
        Some(ResidueCode::GLU),
        true,
    ),
    (
        116,
        "MEA",
        ResidueInfoKind::Aa,
        'f',
        Some('F'),
        Some(ResidueCode::PHE),
        true,
    ),
    (
        117,
        "MED",
        ResidueInfoKind::Aad,
        'm',
        Some('M'),
        Some(ResidueCode::MET),
        true,
    ),
    (
        118,
        "OAS",
        ResidueInfoKind::Aa,
        's',
        Some('S'),
        Some(ResidueCode::SER),
        true,
    ),
    (
        119,
        "GL3",
        ResidueInfoKind::Aa,
        'g',
        Some('G'),
        Some(ResidueCode::GLY),
        true,
    ),
    (
        120,
        "FVA",
        ResidueInfoKind::Aa,
        'v',
        Some('V'),
        Some(ResidueCode::VAL),
        true,
    ),
    (
        121,
        "PHL",
        ResidueInfoKind::Aa,
        'f',
        Some('F'),
        Some(ResidueCode::PHE),
        true,
    ),
    (
        122,
        "CRF",
        ResidueInfoKind::Aa,
        't',
        Some('T'),
        Some(ResidueCode::THR),
        true,
    ),
    (123, "OMZ", ResidueInfoKind::Aa, ' ', None, None, true),
    (
        124,
        "BFD",
        ResidueInfoKind::Aa,
        'd',
        Some('D'),
        Some(ResidueCode::ASP),
        true,
    ),
    (
        125,
        "MEQ",
        ResidueInfoKind::Aa,
        'q',
        Some('Q'),
        Some(ResidueCode::GLN),
        true,
    ),
    (
        126,
        "DAB",
        ResidueInfoKind::Aa,
        'a',
        Some('A'),
        Some(ResidueCode::ALA),
        true,
    ),
    (
        127,
        "AGM",
        ResidueInfoKind::Aa,
        'r',
        Some('R'),
        Some(ResidueCode::ARG),
        true,
    ),
    (128, "PSU", ResidueInfoKind::Rna, 'u', None, None, false),
    (129, "5MU", ResidueInfoKind::Rna, 'u', None, None, false),
    (130, "7MG", ResidueInfoKind::Rna, 'g', None, None, false),
    (131, "OMG", ResidueInfoKind::Rna, 'g', None, None, false),
    (132, "UR3", ResidueInfoKind::Rna, 'u', None, None, false),
    (133, "OMC", ResidueInfoKind::Rna, 'c', None, None, false),
    (134, "2MG", ResidueInfoKind::Rna, 'g', None, None, false),
    (135, "H2U", ResidueInfoKind::Rna, 'u', None, None, false),
    (136, "4SU", ResidueInfoKind::Rna, 'u', None, None, false),
    (137, "OMU", ResidueInfoKind::Rna, 'u', None, None, false),
    (138, "4OC", ResidueInfoKind::Rna, 'c', None, None, false),
    (139, "MA6", ResidueInfoKind::Rna, 'a', None, None, false),
    (140, "M2G", ResidueInfoKind::Rna, 'g', None, None, false),
    (141, "1MA", ResidueInfoKind::Rna, 'a', None, None, false),
    (142, "6MZ", ResidueInfoKind::Rna, 'a', None, None, false),
    (143, "CCC", ResidueInfoKind::Rna, 'c', None, None, false),
    (144, "2MA", ResidueInfoKind::Rna, 'a', None, None, false),
    (145, "1MG", ResidueInfoKind::Rna, 'g', None, None, false),
    (146, "5BU", ResidueInfoKind::Rna, 'u', None, None, false),
    (147, "MIA", ResidueInfoKind::Rna, 'a', None, None, false),
    (148, "DOC", ResidueInfoKind::Dna, 'c', None, None, false),
    (149, "8OG", ResidueInfoKind::Dna, 'g', None, None, false),
    (150, "5CM", ResidueInfoKind::Dna, 'c', None, None, false),
    (151, "3DR", ResidueInfoKind::Dna, ' ', None, None, false),
    (152, "BRU", ResidueInfoKind::Dna, 'u', None, None, false),
    (153, "CBR", ResidueInfoKind::Dna, 'c', None, None, false),
    (154, "HOH", ResidueInfoKind::Hoh, ' ', None, None, false),
    (155, "DOD", ResidueInfoKind::Hoh, ' ', None, None, false),
    (156, "HEM", ResidueInfoKind::Els, ' ', None, None, false),
    (157, "SO4", ResidueInfoKind::Buf, ' ', None, None, false),
    (158, "GOL", ResidueInfoKind::Buf, ' ', None, None, false),
    (159, "EDO", ResidueInfoKind::Buf, ' ', None, None, false),
    (160, "NAG", ResidueInfoKind::Pyr, ' ', None, None, false),
    (161, "PO4", ResidueInfoKind::Els, ' ', None, None, false),
    (162, "ACT", ResidueInfoKind::Buf, ' ', None, None, false),
    (163, "PEG", ResidueInfoKind::Els, ' ', None, None, false),
    (164, "MAN", ResidueInfoKind::Pyr, ' ', None, None, false),
    (165, "FAD", ResidueInfoKind::Els, ' ', None, None, false),
    (166, "BMA", ResidueInfoKind::Pyr, ' ', None, None, false),
    (167, "ADP", ResidueInfoKind::Els, ' ', None, None, false),
    (168, "DMS", ResidueInfoKind::Buf, ' ', None, None, false),
    (169, "ACE", ResidueInfoKind::Els, ' ', None, None, false),
    (170, "NH2", ResidueInfoKind::Els, ' ', None, None, false),
    (171, "MPD", ResidueInfoKind::Buf, ' ', None, None, false),
    (172, "MES", ResidueInfoKind::Els, ' ', None, None, false),
    (173, "NAD", ResidueInfoKind::Els, ' ', None, None, false),
    (174, "NAP", ResidueInfoKind::Els, ' ', None, None, false),
    (175, "TRS", ResidueInfoKind::Buf, ' ', None, None, false),
    (176, "ATP", ResidueInfoKind::Els, ' ', None, None, false),
    (177, "PG4", ResidueInfoKind::Els, ' ', None, None, false),
    (178, "GDP", ResidueInfoKind::Els, 'g', None, None, false),
    (179, "FUC", ResidueInfoKind::Pyr, ' ', None, None, false),
    (180, "FMT", ResidueInfoKind::Buf, ' ', None, None, false),
    (181, "GAL", ResidueInfoKind::Pyr, ' ', None, None, false),
    (182, "PGE", ResidueInfoKind::Buf, ' ', None, None, false),
    (183, "FMN", ResidueInfoKind::Els, ' ', None, None, false),
    (184, "PLP", ResidueInfoKind::Els, ' ', None, None, false),
    (185, "EPE", ResidueInfoKind::Els, ' ', None, None, false),
    (186, "SF4", ResidueInfoKind::Els, ' ', None, None, false),
    (187, "BME", ResidueInfoKind::Els, ' ', None, None, false),
    (188, "CIT", ResidueInfoKind::Buf, ' ', None, None, false),
    (189, "BE7", ResidueInfoKind::Buf, ' ', None, None, false),
    (190, "MRD", ResidueInfoKind::Buf, ' ', None, None, false),
    (191, "MHA", ResidueInfoKind::Buf, ' ', None, None, false),
    (192, "BU3", ResidueInfoKind::Buf, ' ', None, None, false),
    (193, "PGO", ResidueInfoKind::Buf, ' ', None, None, false),
    (194, "BU2", ResidueInfoKind::Buf, ' ', None, None, false),
    (195, "PDO", ResidueInfoKind::Buf, ' ', None, None, false),
    (196, "BU1", ResidueInfoKind::Buf, ' ', None, None, false),
    (197, "PG6", ResidueInfoKind::Buf, ' ', None, None, false),
    (198, "1BO", ResidueInfoKind::Buf, ' ', None, None, false),
    (199, "PE7", ResidueInfoKind::Buf, ' ', None, None, false),
    (200, "PG5", ResidueInfoKind::Buf, ' ', None, None, false),
    (201, "TFP", ResidueInfoKind::Buf, ' ', None, None, false),
    (202, "DHD", ResidueInfoKind::Buf, ' ', None, None, false),
    (203, "PEU", ResidueInfoKind::Buf, ' ', None, None, false),
    (204, "TAU", ResidueInfoKind::Buf, ' ', None, None, false),
    (205, "SBT", ResidueInfoKind::Buf, ' ', None, None, false),
    (206, "SAL", ResidueInfoKind::Buf, ' ', None, None, false),
    (207, "IOH", ResidueInfoKind::Buf, ' ', None, None, false),
    (208, "IPA", ResidueInfoKind::Buf, ' ', None, None, false),
    (209, "PIG", ResidueInfoKind::Buf, ' ', None, None, false),
    (210, "B3P", ResidueInfoKind::Buf, ' ', None, None, false),
    (211, "BTB", ResidueInfoKind::Buf, ' ', None, None, false),
    (212, "NHE", ResidueInfoKind::Buf, ' ', None, None, false),
    (213, "C8E", ResidueInfoKind::Buf, ' ', None, None, false),
    (214, "OTE", ResidueInfoKind::Buf, ' ', None, None, false),
    (215, "PE4", ResidueInfoKind::Buf, ' ', None, None, false),
    (216, "XPE", ResidueInfoKind::Buf, ' ', None, None, false),
    (217, "PE8", ResidueInfoKind::Buf, ' ', None, None, false),
    (218, "P33", ResidueInfoKind::Buf, ' ', None, None, false),
    (219, "N8E", ResidueInfoKind::Buf, ' ', None, None, false),
    (220, "2OS", ResidueInfoKind::Buf, ' ', None, None, false),
    (221, "1PS", ResidueInfoKind::Buf, ' ', None, None, false),
    (222, "CPS", ResidueInfoKind::Buf, ' ', None, None, false),
    (223, "DMX", ResidueInfoKind::Buf, ' ', None, None, false),
    (224, "MPO", ResidueInfoKind::Buf, ' ', None, None, false),
    (225, "GCD", ResidueInfoKind::Pyr, ' ', None, None, false),
    (226, "DXG", ResidueInfoKind::Buf, ' ', None, None, false),
    (227, "CM5", ResidueInfoKind::Buf, ' ', None, None, false),
    (228, "ACA", ResidueInfoKind::Buf, ' ', None, None, false),
    (229, "ACN", ResidueInfoKind::Buf, ' ', None, None, false),
    (230, "CCN", ResidueInfoKind::Buf, ' ', None, None, false),
    (231, "GLC", ResidueInfoKind::Pyr, ' ', None, None, false),
    (232, "DR6", ResidueInfoKind::Buf, ' ', None, None, false),
    (233, "NH4", ResidueInfoKind::Buf, ' ', None, None, false),
    (234, "AZI", ResidueInfoKind::Buf, ' ', None, None, false),
    (235, "BNG", ResidueInfoKind::Pyr, ' ', None, None, false),
    (236, "BOG", ResidueInfoKind::Pyr, ' ', None, None, false),
    (237, "BGC", ResidueInfoKind::Pyr, ' ', None, None, false),
    (238, "BCN", ResidueInfoKind::Buf, ' ', None, None, false),
    (239, "BRO", ResidueInfoKind::Buf, ' ', None, None, false),
    (240, "CAC", ResidueInfoKind::Buf, ' ', None, None, false),
    (241, "CBX", ResidueInfoKind::Buf, ' ', None, None, false),
    (242, "ACY", ResidueInfoKind::Buf, ' ', None, None, false),
    (243, "CBM", ResidueInfoKind::Buf, ' ', None, None, false),
    (244, "CLO", ResidueInfoKind::Buf, ' ', None, None, false),
    (245, "3CO", ResidueInfoKind::Buf, ' ', None, None, false),
    (246, "NCO", ResidueInfoKind::Buf, ' ', None, None, false),
    (247, "CU1", ResidueInfoKind::Buf, ' ', None, None, false),
    (248, "CYN", ResidueInfoKind::Buf, ' ', None, None, false),
    (249, "MA4", ResidueInfoKind::Buf, ' ', None, None, false),
    (250, "TAR", ResidueInfoKind::Buf, ' ', None, None, false),
    (251, "GLO", ResidueInfoKind::Buf, ' ', None, None, false),
    (252, "MTL", ResidueInfoKind::Buf, ' ', None, None, false),
    (253, "SOR", ResidueInfoKind::Buf, ' ', None, None, false),
    (254, "DMU", ResidueInfoKind::Buf, ' ', None, None, false),
    (255, "DDQ", ResidueInfoKind::Buf, ' ', None, None, false),
    (256, "DMF", ResidueInfoKind::Buf, ' ', None, None, false),
    (257, "DIO", ResidueInfoKind::Buf, ' ', None, None, false),
    (258, "DOX", ResidueInfoKind::Buf, ' ', None, None, false),
    (259, "12P", ResidueInfoKind::Buf, ' ', None, None, false),
    (260, "SDS", ResidueInfoKind::Buf, ' ', None, None, false),
    (261, "LMT", ResidueInfoKind::Buf, ' ', None, None, false),
    (262, "EOH", ResidueInfoKind::Buf, ' ', None, None, false),
    (263, "EEE", ResidueInfoKind::Buf, ' ', None, None, false),
    (264, "EGL", ResidueInfoKind::Buf, ' ', None, None, false),
    (265, "FLO", ResidueInfoKind::Buf, ' ', None, None, false),
    (266, "TRT", ResidueInfoKind::Buf, ' ', None, None, false),
    (267, "FCY", ResidueInfoKind::Buf, ' ', None, None, false),
    (268, "FRU", ResidueInfoKind::Buf, ' ', None, None, false),
    (269, "GBL", ResidueInfoKind::Buf, ' ', None, None, false),
    (270, "GPX", ResidueInfoKind::Buf, ' ', None, None, false),
    (271, "HTO", ResidueInfoKind::Buf, ' ', None, None, false),
    (272, "HTG", ResidueInfoKind::Buf, ' ', None, None, false),
    (273, "B7G", ResidueInfoKind::Buf, ' ', None, None, false),
    (274, "C10", ResidueInfoKind::Buf, ' ', None, None, false),
    (275, "16D", ResidueInfoKind::Buf, ' ', None, None, false),
    (276, "HEZ", ResidueInfoKind::Buf, ' ', None, None, false),
    (277, "IOD", ResidueInfoKind::Buf, ' ', None, None, false),
    (278, "IDO", ResidueInfoKind::Buf, ' ', None, None, false),
    (279, "ICI", ResidueInfoKind::Buf, ' ', None, None, false),
    (280, "ICT", ResidueInfoKind::Buf, ' ', None, None, false),
    (281, "TLA", ResidueInfoKind::Buf, ' ', None, None, false),
    (282, "LAT", ResidueInfoKind::Buf, ' ', None, None, false),
    (283, "LBT", ResidueInfoKind::Buf, ' ', None, None, false),
    (284, "LDA", ResidueInfoKind::Buf, ' ', None, None, false),
    (285, "MN3", ResidueInfoKind::Buf, ' ', None, None, false),
    (286, "MRY", ResidueInfoKind::Buf, ' ', None, None, false),
    (287, "MOH", ResidueInfoKind::Buf, ' ', None, None, false),
    (288, "BEQ", ResidueInfoKind::Buf, ' ', None, None, false),
    (289, "C15", ResidueInfoKind::Buf, ' ', None, None, false),
    (290, "MG8", ResidueInfoKind::Buf, ' ', None, None, false),
    (291, "POL", ResidueInfoKind::Buf, ' ', None, None, false),
    (292, "NO3", ResidueInfoKind::Buf, ' ', None, None, false),
    (293, "JEF", ResidueInfoKind::Buf, ' ', None, None, false),
    (294, "P4C", ResidueInfoKind::Buf, ' ', None, None, false),
    (295, "CE1", ResidueInfoKind::Buf, ' ', None, None, false),
    (296, "DIA", ResidueInfoKind::Buf, ' ', None, None, false),
    (297, "CXE", ResidueInfoKind::Buf, ' ', None, None, false),
    (298, "IPH", ResidueInfoKind::Buf, ' ', None, None, false),
    (299, "PIN", ResidueInfoKind::Buf, ' ', None, None, false),
    (300, "15P", ResidueInfoKind::Buf, ' ', None, None, false),
    (301, "CRY", ResidueInfoKind::Buf, ' ', None, None, false),
    (302, "PGR", ResidueInfoKind::Buf, ' ', None, None, false),
    (303, "PGQ", ResidueInfoKind::Buf, ' ', None, None, false),
    (304, "SPD", ResidueInfoKind::Buf, ' ', None, None, false),
    (305, "SPK", ResidueInfoKind::Buf, ' ', None, None, false),
    (306, "SPM", ResidueInfoKind::Buf, ' ', None, None, false),
    (307, "SUC", ResidueInfoKind::Pyr, ' ', None, None, false),
    (308, "TBU", ResidueInfoKind::Buf, ' ', None, None, false),
    (309, "TMA", ResidueInfoKind::Buf, ' ', None, None, false),
    (310, "TEP", ResidueInfoKind::Buf, ' ', None, None, false),
    (311, "SCN", ResidueInfoKind::Buf, ' ', None, None, false),
    (312, "TRE", ResidueInfoKind::Pyr, ' ', None, None, false),
    (313, "ETF", ResidueInfoKind::Buf, ' ', None, None, false),
    (314, "144", ResidueInfoKind::Buf, ' ', None, None, false),
    (315, "UMQ", ResidueInfoKind::Buf, ' ', None, None, false),
    (316, "URE", ResidueInfoKind::Buf, ' ', None, None, false),
    (317, "YT3", ResidueInfoKind::Buf, ' ', None, None, false),
    (318, "ZN2", ResidueInfoKind::Buf, ' ', None, None, false),
    (319, "FE2", ResidueInfoKind::Buf, ' ', None, None, false),
    (320, "3NI", ResidueInfoKind::Buf, ' ', None, None, false),
    (321, "SIA", ResidueInfoKind::Pyr, ' ', None, None, false),
    (322, "XYP", ResidueInfoKind::Pyr, ' ', None, None, false),
    (323, "A2G", ResidueInfoKind::Pyr, ' ', None, None, false),
    (324, "GLA", ResidueInfoKind::Pyr, ' ', None, None, false),
    (325, "NDG", ResidueInfoKind::Pyr, ' ', None, None, false),
    (326, "NGA", ResidueInfoKind::Pyr, ' ', None, None, false),
    (327, "A", ResidueInfoKind::Rna, 'A', None, None, false),
    (328, "C", ResidueInfoKind::Rna, 'C', None, None, false),
    (329, "G", ResidueInfoKind::Rna, 'G', None, None, false),
    (330, "I", ResidueInfoKind::Rna, 'I', None, None, false),
    (331, "U", ResidueInfoKind::Rna, 'U', None, None, false),
    (332, "N", ResidueInfoKind::Rna, 'N', None, None, false),
    (333, "F", ResidueInfoKind::Buf, ' ', None, None, false),
    (334, "K", ResidueInfoKind::Buf, ' ', None, None, false),
    (335, "DA", ResidueInfoKind::Dna, 'A', None, None, false),
    (336, "DC", ResidueInfoKind::Dna, 'C', None, None, false),
    (337, "DG", ResidueInfoKind::Dna, 'G', None, None, false),
    (338, "DI", ResidueInfoKind::Dna, 'I', None, None, false),
    (339, "DT", ResidueInfoKind::Dna, 'T', None, None, false),
    (340, "DU", ResidueInfoKind::Dna, 'U', None, None, false),
    (341, "DN", ResidueInfoKind::Dna, 'N', None, None, false),
    (342, "AG", ResidueInfoKind::Buf, ' ', None, None, false),
    (343, "AL", ResidueInfoKind::Buf, ' ', None, None, false),
    (344, "BA", ResidueInfoKind::Buf, ' ', None, None, false),
    (345, "BR", ResidueInfoKind::Buf, ' ', None, None, false),
    (346, "CA", ResidueInfoKind::Buf, ' ', None, None, false),
    (347, "CD", ResidueInfoKind::Buf, ' ', None, None, false),
    (348, "CL", ResidueInfoKind::Buf, ' ', None, None, false),
    (349, "CM", ResidueInfoKind::Buf, ' ', None, None, false),
    (350, "CN", ResidueInfoKind::Buf, ' ', None, None, false),
    (351, "CO", ResidueInfoKind::Buf, ' ', None, None, false),
    (352, "CS", ResidueInfoKind::Buf, ' ', None, None, false),
    (353, "CU", ResidueInfoKind::Buf, ' ', None, None, false),
    (354, "FE", ResidueInfoKind::Buf, ' ', None, None, false),
    (355, "HG", ResidueInfoKind::Buf, ' ', None, None, false),
    (356, "LI", ResidueInfoKind::Buf, ' ', None, None, false),
    (357, "MG", ResidueInfoKind::Buf, ' ', None, None, false),
    (358, "MN", ResidueInfoKind::Buf, ' ', None, None, false),
    (359, "NA", ResidueInfoKind::Buf, ' ', None, None, false),
    (360, "NI", ResidueInfoKind::Buf, ' ', None, None, false),
    (361, "NO", ResidueInfoKind::Els, ' ', None, None, false),
    (362, "PB", ResidueInfoKind::Buf, ' ', None, None, false),
    (363, "RB", ResidueInfoKind::Buf, ' ', None, None, false),
    (364, "SR", ResidueInfoKind::Buf, ' ', None, None, false),
    (365, "Y1", ResidueInfoKind::Buf, ' ', None, None, false),
    (366, "ZN", ResidueInfoKind::Buf, ' ', None, None, false),
    (367, "", ResidueInfoKind::Unknown, ' ', None, None, false),
];

/// Frozen synthetic-fixture constructor: the deliberately contradicting
/// name/code fields prove outputs depend ONLY on kind/one_letter.
fn synthetic(kind: ResidueInfoKind, one_letter_code: char) -> ResidueInfo {
    ResidueInfo {
        code: ResidueCode::HOH,
        name: "HOH",
        kind,
        linking_type: 17,
        one_letter_code,
        hydrogen_count: 9,
        weight: 17.25f32,
    }
}

/// Frozen 8-character synthetic grid.
const CHARS: [(char, Option<char>); 8] = [
    ('m', Some('M')),
    ('M', Some('M')),
    ('j', None),
    ('J', None),
    (' ', None),
    ('é', None),
    ('B', Some('B')),
    ('X', Some('X')),
];

/// Frozen kind grid with per-kind expected canonical outputs (amino rows
/// only; the other eight kinds return None for every char).
const KINDS: [(ResidueInfoKind, [Option<char>; 8]); 12] = [
    (ResidueInfoKind::Unknown, [None; 8]),
    (
        ResidueInfoKind::Aa,
        [
            Some('M'),
            Some('M'),
            None,
            None,
            None,
            None,
            Some('B'),
            Some('X'),
        ],
    ),
    (
        ResidueInfoKind::Aad,
        [
            Some('M'),
            Some('M'),
            None,
            None,
            None,
            None,
            Some('B'),
            Some('X'),
        ],
    ),
    (
        ResidueInfoKind::Paa,
        [
            Some('M'),
            Some('M'),
            None,
            None,
            None,
            None,
            Some('B'),
            Some('X'),
        ],
    ),
    (
        ResidueInfoKind::Maa,
        [
            Some('M'),
            Some('M'),
            None,
            None,
            None,
            None,
            Some('B'),
            Some('X'),
        ],
    ),
    (ResidueInfoKind::Rna, [None; 8]),
    (ResidueInfoKind::Dna, [None; 8]),
    (ResidueInfoKind::Buf, [None; 8]),
    (ResidueInfoKind::Hoh, [None; 8]),
    (ResidueInfoKind::Pyr, [None; 8]),
    (ResidueInfoKind::Ket, [None; 8]),
    (ResidueInfoKind::Els, [None; 8]),
];

/// Frozen kind grid for PARENT outputs (amino rows only; 'm'/'M' -> MET,
/// 'B' -> ASX, 'X' -> UNK per the frozen product table).
const PARENT_KINDS: [(ResidueInfoKind, [Option<ResidueCode>; 8]); 12] = [
    (ResidueInfoKind::Unknown, [None; 8]),
    (
        ResidueInfoKind::Aa,
        [
            Some(ResidueCode::MET),
            Some(ResidueCode::MET),
            None,
            None,
            None,
            None,
            Some(ResidueCode::ASX),
            Some(ResidueCode::UNK),
        ],
    ),
    (
        ResidueInfoKind::Aad,
        [
            Some(ResidueCode::MET),
            Some(ResidueCode::MET),
            None,
            None,
            None,
            None,
            Some(ResidueCode::ASX),
            Some(ResidueCode::UNK),
        ],
    ),
    (
        ResidueInfoKind::Paa,
        [
            Some(ResidueCode::MET),
            Some(ResidueCode::MET),
            None,
            None,
            None,
            None,
            Some(ResidueCode::ASX),
            Some(ResidueCode::UNK),
        ],
    ),
    (
        ResidueInfoKind::Maa,
        [
            Some(ResidueCode::MET),
            Some(ResidueCode::MET),
            None,
            None,
            None,
            None,
            Some(ResidueCode::ASX),
            Some(ResidueCode::UNK),
        ],
    ),
    (ResidueInfoKind::Rna, [None; 8]),
    (ResidueInfoKind::Dna, [None; 8]),
    (ResidueInfoKind::Buf, [None; 8]),
    (ResidueInfoKind::Hoh, [None; 8]),
    (ResidueInfoKind::Pyr, [None; 8]),
    (ResidueInfoKind::Ket, [None; 8]),
    (ResidueInfoKind::Els, [None; 8]),
];

/// Frozen kind grid for MODIFIED outputs (amino rows only, per the frozen
/// 8-char table: lowercase/space/é rows true, uppercase rows false).
const MODIFIED_KINDS: [(ResidueInfoKind, [bool; 8]); 12] = [
    (ResidueInfoKind::Unknown, [false; 8]),
    (
        ResidueInfoKind::Aa,
        [true, false, true, false, true, true, false, false],
    ),
    (
        ResidueInfoKind::Aad,
        [true, false, true, false, true, true, false, false],
    ),
    (
        ResidueInfoKind::Paa,
        [true, false, true, false, true, true, false, false],
    ),
    (
        ResidueInfoKind::Maa,
        [true, false, true, false, true, true, false, false],
    ),
    (ResidueInfoKind::Rna, [false; 8]),
    (ResidueInfoKind::Dna, [false; 8]),
    (ResidueInfoKind::Buf, [false; 8]),
    (ResidueInfoKind::Hoh, [false; 8]),
    (ResidueInfoKind::Pyr, [false; 8]),
    (ResidueInfoKind::Ket, [false; 8]),
    (ResidueInfoKind::Els, [false; 8]),
];

/// Step-6 canonical regressions: all 368 immutable annex rows plus the
/// frozen 12-kind x 8-char product (96 synthetic calls) = exactly 464
/// invocations, each with a fresh whole-input snapshot and literal expected
/// `Option<char>` from the ROOT annex (never SUT-derived).
#[test]
fn residue_parent_canonical_all_rows_and_kind_product() {
    let mut calls = 0usize;
    for (index, name, kind, one_letter, expected, _, _) in ANNEX {
        let info = residue_info(index);
        let label = format!("{index}/{name}");
        // Frozen identity preconditions before every invocation.
        assert_eq!(info.name, name, "{label}: annex name");
        assert_eq!(info.kind, kind, "{label}: annex kind");
        assert_eq!(info.one_letter_code, one_letter, "{label}: annex letter");
        let before = info;
        assert_eq!(info.canonical_one_letter_code(), expected, "{label}");
        calls += 1;
        assert_eq!(info, before, "{label}: whole input preserved");
    }
    for (kind, expected_row) in KINDS {
        for &(character, _) in &CHARS {
            let expected = expected_row[CHARS
                .iter()
                .position(|&(candidate, _)| candidate == character)
                .expect("frozen character grid")];
            let label = format!("{kind:?}/{character:?}");
            let info = synthetic(kind, character);
            let before = info;
            assert_eq!(
                info.canonical_one_letter_code(),
                expected,
                "{label}: canonical"
            );
            calls += 1;
            assert_eq!(info, before, "{label}: whole input preserved");
        }
    }
    assert_eq!(calls, 464, "exact 464-invocation census");
}

/// Step-12 parent regressions: the same immutable 368 annex rows and the
/// frozen 96-call kind/character product = exactly 464 invocations with
/// literal `Option<ResidueCode>` parents, per-call whole-input snapshots,
/// and the explicit source controls (MSE->MET, HYP->PRO, SEP->SER,
/// PRO->PRO, 3FG->None, HOH->None) taken from the annex, not from
/// name-based substitution.
#[test]
fn residue_parent_standard_all_rows_and_kind_product() {
    let mut calls = 0usize;
    for (index, name, kind, one_letter, _, expected, _) in ANNEX {
        let info = residue_info(index);
        let label = format!("{index}/{name}");
        // Frozen identity preconditions before every invocation.
        assert_eq!(info.name, name, "{label}: annex name");
        assert_eq!(info.kind, kind, "{label}: annex kind");
        assert_eq!(info.one_letter_code, one_letter, "{label}: annex letter");
        let before = info;
        assert_eq!(info.parent_standard_code(), expected, "{label}: parent");
        calls += 1;
        assert_eq!(info, before, "{label}: whole input preserved");
    }
    for (kind, expected_row) in PARENT_KINDS {
        for &(character, _) in &CHARS {
            let expected = expected_row[CHARS
                .iter()
                .position(|&(candidate, _)| candidate == character)
                .expect("frozen character grid")];
            let label = format!("{kind:?}/{character:?}");
            let info = synthetic(kind, character);
            let before = info;
            assert_eq!(info.parent_standard_code(), expected, "{label}: parent");
            calls += 1;
            assert_eq!(info, before, "{label}: whole input preserved");
        }
    }
    assert_eq!(calls, 464, "exact 464-invocation census");

    // Explicit frozen controls (annex-derived; synthetic fields never
    // consulted): MSE/HYP/SEP modified->parents, PRO self-parent,
    // 3FG modified-but-unmappable, HOH non-amino.
    assert_eq!(
        residue_info(17).parent_standard_code(),
        Some(ResidueCode::MET),
        "MSE -> MET"
    );
    assert_eq!(
        residue_info(45).parent_standard_code(),
        Some(ResidueCode::PRO),
        "HYP -> PRO"
    );
    assert_eq!(
        residue_info(29).parent_standard_code(),
        Some(ResidueCode::SER),
        "SEP -> SER"
    );
    assert_eq!(
        residue_info(20).parent_standard_code(),
        Some(ResidueCode::PRO),
        "PRO -> PRO (self)"
    );
    assert_eq!(
        residue_info(97).parent_standard_code(),
        None,
        "3FG -> None (modified but unmappable)"
    );
    assert_eq!(
        residue_info(154).parent_standard_code(),
        None,
        "HOH -> None (non-amino)"
    );
}

/// Step-18 modified regressions: the same immutable 368 annex rows plus
/// the frozen 96-call kind/character product = exactly 464 invocations
/// with literal booleans and per-call whole-input snapshots; the
/// modified-but-unmappable 3FG row is true while non-amino rows are
/// false, proving modification status is never inferred from a
/// successful parent mapping.
#[test]
fn residue_parent_modified_all_rows_and_kind_product() {
    let mut calls = 0usize;
    for (index, name, kind, one_letter, _, _, expected) in ANNEX {
        let info = residue_info(index);
        let label = format!("{index}/{name}");
        // Frozen identity preconditions before every invocation.
        assert_eq!(info.name, name, "{label}: annex name");
        assert_eq!(info.kind, kind, "{label}: annex kind");
        assert_eq!(info.one_letter_code, one_letter, "{label}: annex letter");
        let before = info;
        assert_eq!(info.is_modified_amino_acid(), expected, "{label}");
        calls += 1;
        assert_eq!(info, before, "{label}: whole input preserved");
    }
    for (kind, expected_row) in MODIFIED_KINDS {
        for &(character, _) in &CHARS {
            let expected = expected_row[CHARS
                .iter()
                .position(|&(candidate, _)| candidate == character)
                .expect("frozen character grid")];
            let label = format!("{kind:?}/{character:?}");
            let info = synthetic(kind, character);
            let before = info;
            assert_eq!(info.is_modified_amino_acid(), expected, "{label}");
            calls += 1;
            assert_eq!(info, before, "{label}: whole input preserved");
        }
    }
    assert_eq!(calls, 464, "exact 464-invocation census");

    // Modified-but-unmappable vs non-amino distinctions (annex-derived).
    assert!(
        residue_info(97).is_modified_amino_acid(),
        "3FG modified but unmappable -> still true"
    );
    assert!(
        residue_info(97).parent_standard_code().is_none(),
        "3FG has no parent: modification does not imply mapping"
    );
    assert!(
        !residue_info(154).is_modified_amino_acid(),
        "HOH non-amino -> false"
    );
    assert!(
        !residue_info(327).is_modified_amino_acid(),
        "RNA 'A' row -> false"
    );
}
