//! BIO-SERDE1-28: frozen Serde wire-contract regressions for ResidueCode.
//!
//! The `ANNEX` table below is ROOT-frozen immutable expected data
//! (independently derived from the pinned Gemmi `get_residue_info`
//! initializer at `third_party/gemmi/src/resinfo.cpp:404-844`), copied from
//! the packet's annex — never parsed from upstream, never regenerated and
//! never derived from the implementation under test.

use cosmolkit_bio::ResidueCode;
use serde::{Deserialize, Serialize};

/// (variant, discriminant, wire string) for all 368 codes, in table order.
const ANNEX: [(&str, u16, &str); 368] = [
    ("ALA", 0, "ALA"),
    ("ARG", 1, "ARG"),
    ("ASN", 2, "ASN"),
    ("ABA", 3, "ABA"),
    ("ASP", 4, "ASP"),
    ("ASX", 5, "ASX"),
    ("CYS", 6, "CYS"),
    ("CSH", 7, "CSH"),
    ("GLN", 8, "GLN"),
    ("GLU", 9, "GLU"),
    ("GLX", 10, "GLX"),
    ("GLY", 11, "GLY"),
    ("HIS", 12, "HIS"),
    ("ILE", 13, "ILE"),
    ("LEU", 14, "LEU"),
    ("LYS", 15, "LYS"),
    ("MET", 16, "MET"),
    ("MSE", 17, "MSE"),
    ("ORN", 18, "ORN"),
    ("PHE", 19, "PHE"),
    ("PRO", 20, "PRO"),
    ("SER", 21, "SER"),
    ("THR", 22, "THR"),
    ("TRP", 23, "TRP"),
    ("TYR", 24, "TYR"),
    ("UNK", 25, "UNK"),
    ("VAL", 26, "VAL"),
    ("SEC", 27, "SEC"),
    ("PYL", 28, "PYL"),
    ("SEP", 29, "SEP"),
    ("TPO", 30, "TPO"),
    ("PCA", 31, "PCA"),
    ("CSO", 32, "CSO"),
    ("PTR", 33, "PTR"),
    ("KCX", 34, "KCX"),
    ("CSD", 35, "CSD"),
    ("LLP", 36, "LLP"),
    ("CME", 37, "CME"),
    ("MLY", 38, "MLY"),
    ("DAL", 39, "DAL"),
    ("TYS", 40, "TYS"),
    ("OCS", 41, "OCS"),
    ("M3L", 42, "M3L"),
    ("FME", 43, "FME"),
    ("ALY", 44, "ALY"),
    ("HYP", 45, "HYP"),
    ("CAS", 46, "CAS"),
    ("CRO", 47, "CRO"),
    ("CSX", 48, "CSX"),
    ("DPR", 49, "DPR"),
    ("DGL", 50, "DGL"),
    ("DVA", 51, "DVA"),
    ("CSS", 52, "CSS"),
    ("DPN", 53, "DPN"),
    ("DSN", 54, "DSN"),
    ("DLE", 55, "DLE"),
    ("HIC", 56, "HIC"),
    ("NLE", 57, "NLE"),
    ("MVA", 58, "MVA"),
    ("MLZ", 59, "MLZ"),
    ("CR2", 60, "CR2"),
    ("SAR", 61, "SAR"),
    ("DAR", 62, "DAR"),
    ("DLY", 63, "DLY"),
    ("YCM", 64, "YCM"),
    ("NRQ", 65, "NRQ"),
    ("CGU", 66, "CGU"),
    ("R0TD", 67, "0TD"),
    ("MLE", 68, "MLE"),
    ("DAS", 69, "DAS"),
    ("DTR", 70, "DTR"),
    ("CXM", 71, "CXM"),
    ("TPQ", 72, "TPQ"),
    ("DCY", 73, "DCY"),
    ("DSG", 74, "DSG"),
    ("DTY", 75, "DTY"),
    ("DHI", 76, "DHI"),
    ("MEN", 77, "MEN"),
    ("DTH", 78, "DTH"),
    ("SAC", 79, "SAC"),
    ("DGN", 80, "DGN"),
    ("AIB", 81, "AIB"),
    ("SMC", 82, "SMC"),
    ("IAS", 83, "IAS"),
    ("CIR", 84, "CIR"),
    ("BMT", 85, "BMT"),
    ("DIL", 86, "DIL"),
    ("FGA", 87, "FGA"),
    ("PHI", 88, "PHI"),
    ("CRQ", 89, "CRQ"),
    ("SME", 90, "SME"),
    ("GHP", 91, "GHP"),
    ("MHO", 92, "MHO"),
    ("NEP", 93, "NEP"),
    ("TRQ", 94, "TRQ"),
    ("TOX", 95, "TOX"),
    ("ALC", 96, "ALC"),
    ("R3FG", 97, "3FG"),
    ("SCH", 98, "SCH"),
    ("MDO", 99, "MDO"),
    ("MAA", 100, "MAA"),
    ("GYS", 101, "GYS"),
    ("MK8", 102, "MK8"),
    ("CR8", 103, "CR8"),
    ("KPI", 104, "KPI"),
    ("SCY", 105, "SCY"),
    ("DHA", 106, "DHA"),
    ("OMY", 107, "OMY"),
    ("CAF", 108, "CAF"),
    ("R0AF", 109, "0AF"),
    ("SNN", 110, "SNN"),
    ("MHS", 111, "MHS"),
    ("MLU", 112, "MLU"),
    ("SNC", 113, "SNC"),
    ("PHD", 114, "PHD"),
    ("B3E", 115, "B3E"),
    ("MEA", 116, "MEA"),
    ("MED", 117, "MED"),
    ("OAS", 118, "OAS"),
    ("GL3", 119, "GL3"),
    ("FVA", 120, "FVA"),
    ("PHL", 121, "PHL"),
    ("CRF", 122, "CRF"),
    ("OMZ", 123, "OMZ"),
    ("BFD", 124, "BFD"),
    ("MEQ", 125, "MEQ"),
    ("DAB", 126, "DAB"),
    ("AGM", 127, "AGM"),
    ("PSU", 128, "PSU"),
    ("R5MU", 129, "5MU"),
    ("R7MG", 130, "7MG"),
    ("OMG", 131, "OMG"),
    ("UR3", 132, "UR3"),
    ("OMC", 133, "OMC"),
    ("R2MG", 134, "2MG"),
    ("H2U", 135, "H2U"),
    ("R4SU", 136, "4SU"),
    ("OMU", 137, "OMU"),
    ("R4OC", 138, "4OC"),
    ("MA6", 139, "MA6"),
    ("M2G", 140, "M2G"),
    ("R1MA", 141, "1MA"),
    ("R6MZ", 142, "6MZ"),
    ("CCC", 143, "CCC"),
    ("R2MA", 144, "2MA"),
    ("R1MG", 145, "1MG"),
    ("R5BU", 146, "5BU"),
    ("MIA", 147, "MIA"),
    ("DOC", 148, "DOC"),
    ("R8OG", 149, "8OG"),
    ("R5CM", 150, "5CM"),
    ("R3DR", 151, "3DR"),
    ("BRU", 152, "BRU"),
    ("CBR", 153, "CBR"),
    ("HOH", 154, "HOH"),
    ("DOD", 155, "DOD"),
    ("HEM", 156, "HEM"),
    ("SO4", 157, "SO4"),
    ("GOL", 158, "GOL"),
    ("EDO", 159, "EDO"),
    ("NAG", 160, "NAG"),
    ("PO4", 161, "PO4"),
    ("ACT", 162, "ACT"),
    ("PEG", 163, "PEG"),
    ("MAN", 164, "MAN"),
    ("FAD", 165, "FAD"),
    ("BMA", 166, "BMA"),
    ("ADP", 167, "ADP"),
    ("DMS", 168, "DMS"),
    ("ACE", 169, "ACE"),
    ("NH2", 170, "NH2"),
    ("MPD", 171, "MPD"),
    ("MES", 172, "MES"),
    ("NAD", 173, "NAD"),
    ("NAP", 174, "NAP"),
    ("TRS", 175, "TRS"),
    ("ATP", 176, "ATP"),
    ("PG4", 177, "PG4"),
    ("GDP", 178, "GDP"),
    ("FUC", 179, "FUC"),
    ("FMT", 180, "FMT"),
    ("GAL", 181, "GAL"),
    ("PGE", 182, "PGE"),
    ("FMN", 183, "FMN"),
    ("PLP", 184, "PLP"),
    ("EPE", 185, "EPE"),
    ("SF4", 186, "SF4"),
    ("BME", 187, "BME"),
    ("CIT", 188, "CIT"),
    ("BE7", 189, "BE7"),
    ("MRD", 190, "MRD"),
    ("MHA", 191, "MHA"),
    ("BU3", 192, "BU3"),
    ("PGO", 193, "PGO"),
    ("BU2", 194, "BU2"),
    ("PDO", 195, "PDO"),
    ("BU1", 196, "BU1"),
    ("PG6", 197, "PG6"),
    ("R1BO", 198, "1BO"),
    ("PE7", 199, "PE7"),
    ("PG5", 200, "PG5"),
    ("TFP", 201, "TFP"),
    ("DHD", 202, "DHD"),
    ("PEU", 203, "PEU"),
    ("TAU", 204, "TAU"),
    ("SBT", 205, "SBT"),
    ("SAL", 206, "SAL"),
    ("IOH", 207, "IOH"),
    ("IPA", 208, "IPA"),
    ("PIG", 209, "PIG"),
    ("B3P", 210, "B3P"),
    ("BTB", 211, "BTB"),
    ("NHE", 212, "NHE"),
    ("C8E", 213, "C8E"),
    ("OTE", 214, "OTE"),
    ("PE4", 215, "PE4"),
    ("XPE", 216, "XPE"),
    ("PE8", 217, "PE8"),
    ("P33", 218, "P33"),
    ("N8E", 219, "N8E"),
    ("R2OS", 220, "2OS"),
    ("R1PS", 221, "1PS"),
    ("CPS", 222, "CPS"),
    ("DMX", 223, "DMX"),
    ("MPO", 224, "MPO"),
    ("GCD", 225, "GCD"),
    ("DXG", 226, "DXG"),
    ("CM5", 227, "CM5"),
    ("ACA", 228, "ACA"),
    ("ACN", 229, "ACN"),
    ("CCN", 230, "CCN"),
    ("GLC", 231, "GLC"),
    ("DR6", 232, "DR6"),
    ("NH4", 233, "NH4"),
    ("AZI", 234, "AZI"),
    ("BNG", 235, "BNG"),
    ("BOG", 236, "BOG"),
    ("BGC", 237, "BGC"),
    ("BCN", 238, "BCN"),
    ("BRO", 239, "BRO"),
    ("CAC", 240, "CAC"),
    ("CBX", 241, "CBX"),
    ("ACY", 242, "ACY"),
    ("CBM", 243, "CBM"),
    ("CLO", 244, "CLO"),
    ("R3CO", 245, "3CO"),
    ("NCO", 246, "NCO"),
    ("CU1", 247, "CU1"),
    ("CYN", 248, "CYN"),
    ("MA4", 249, "MA4"),
    ("TAR", 250, "TAR"),
    ("GLO", 251, "GLO"),
    ("MTL", 252, "MTL"),
    ("SOR", 253, "SOR"),
    ("DMU", 254, "DMU"),
    ("DDQ", 255, "DDQ"),
    ("DMF", 256, "DMF"),
    ("DIO", 257, "DIO"),
    ("DOX", 258, "DOX"),
    ("R12P", 259, "12P"),
    ("SDS", 260, "SDS"),
    ("LMT", 261, "LMT"),
    ("EOH", 262, "EOH"),
    ("EEE", 263, "EEE"),
    ("EGL", 264, "EGL"),
    ("FLO", 265, "FLO"),
    ("TRT", 266, "TRT"),
    ("FCY", 267, "FCY"),
    ("FRU", 268, "FRU"),
    ("GBL", 269, "GBL"),
    ("GPX", 270, "GPX"),
    ("HTO", 271, "HTO"),
    ("HTG", 272, "HTG"),
    ("B7G", 273, "B7G"),
    ("C10", 274, "C10"),
    ("R16D", 275, "16D"),
    ("HEZ", 276, "HEZ"),
    ("IOD", 277, "IOD"),
    ("IDO", 278, "IDO"),
    ("ICI", 279, "ICI"),
    ("ICT", 280, "ICT"),
    ("TLA", 281, "TLA"),
    ("LAT", 282, "LAT"),
    ("LBT", 283, "LBT"),
    ("LDA", 284, "LDA"),
    ("MN3", 285, "MN3"),
    ("MRY", 286, "MRY"),
    ("MOH", 287, "MOH"),
    ("BEQ", 288, "BEQ"),
    ("C15", 289, "C15"),
    ("MG8", 290, "MG8"),
    ("POL", 291, "POL"),
    ("NO3", 292, "NO3"),
    ("JEF", 293, "JEF"),
    ("P4C", 294, "P4C"),
    ("CE1", 295, "CE1"),
    ("DIA", 296, "DIA"),
    ("CXE", 297, "CXE"),
    ("IPH", 298, "IPH"),
    ("PIN", 299, "PIN"),
    ("R15P", 300, "15P"),
    ("CRY", 301, "CRY"),
    ("PGR", 302, "PGR"),
    ("PGQ", 303, "PGQ"),
    ("SPD", 304, "SPD"),
    ("SPK", 305, "SPK"),
    ("SPM", 306, "SPM"),
    ("SUC", 307, "SUC"),
    ("TBU", 308, "TBU"),
    ("TMA", 309, "TMA"),
    ("TEP", 310, "TEP"),
    ("SCN", 311, "SCN"),
    ("TRE", 312, "TRE"),
    ("ETF", 313, "ETF"),
    ("R144", 314, "144"),
    ("UMQ", 315, "UMQ"),
    ("URE", 316, "URE"),
    ("YT3", 317, "YT3"),
    ("ZN2", 318, "ZN2"),
    ("FE2", 319, "FE2"),
    ("R3NI", 320, "3NI"),
    ("SIA", 321, "SIA"),
    ("XYP", 322, "XYP"),
    ("A2G", 323, "A2G"),
    ("GLA", 324, "GLA"),
    ("NDG", 325, "NDG"),
    ("NGA", 326, "NGA"),
    ("A", 327, "A"),
    ("C", 328, "C"),
    ("G", 329, "G"),
    ("I", 330, "I"),
    ("U", 331, "U"),
    ("N", 332, "N"),
    ("F", 333, "F"),
    ("K", 334, "K"),
    ("DA", 335, "DA"),
    ("DC", 336, "DC"),
    ("DG", 337, "DG"),
    ("DI", 338, "DI"),
    ("DT", 339, "DT"),
    ("DU", 340, "DU"),
    ("DN", 341, "DN"),
    ("AG", 342, "AG"),
    ("AL", 343, "AL"),
    ("BA", 344, "BA"),
    ("BR", 345, "BR"),
    ("CA", 346, "CA"),
    ("CD", 347, "CD"),
    ("CL", 348, "CL"),
    ("CM", 349, "CM"),
    ("CN", 350, "CN"),
    ("CO", 351, "CO"),
    ("CS", 352, "CS"),
    ("CU", 353, "CU"),
    ("FE", 354, "FE"),
    ("HG", 355, "HG"),
    ("LI", 356, "LI"),
    ("MG", 357, "MG"),
    ("MN", 358, "MN"),
    ("NA", 359, "NA"),
    ("NI", 360, "NI"),
    ("NO", 361, "NO"),
    ("PB", 362, "PB"),
    ("RB", 363, "RB"),
    ("SR", 364, "SR"),
    ("Y1", 365, "Y1"),
    ("ZN", 366, "ZN"),
    ("UNKNOWN", 367, "UNKNOWN"),
];

fn code_for(variant: &str) -> ResidueCode {
    // Test-only variant lookup by name through the same public enum; the
    // mapping is the frozen annex order, not an implementation behavior.
    ANNEX
        .iter()
        .find(|(v, _, _)| *v == variant)
        .map(|(_, index, _)| by_discriminant(*index))
        .unwrap_or_else(|| panic!("annex lookup failed for {variant:?}"))
}

fn by_discriminant(index: u16) -> ResidueCode {
    // A frozen variant-by-discriminant table local to this test.
    const VARIANTS: [(&str, u16); 368] = [
        ("ALA", 0),
        ("ARG", 1),
        ("ASN", 2),
        ("ABA", 3),
        ("ASP", 4),
        ("ASX", 5),
        ("CYS", 6),
        ("CSH", 7),
        ("GLN", 8),
        ("GLU", 9),
        ("GLX", 10),
        ("GLY", 11),
        ("HIS", 12),
        ("ILE", 13),
        ("LEU", 14),
        ("LYS", 15),
        ("MET", 16),
        ("MSE", 17),
        ("ORN", 18),
        ("PHE", 19),
        ("PRO", 20),
        ("SER", 21),
        ("THR", 22),
        ("TRP", 23),
        ("TYR", 24),
        ("UNK", 25),
        ("VAL", 26),
        ("SEC", 27),
        ("PYL", 28),
        ("SEP", 29),
        ("TPO", 30),
        ("PCA", 31),
        ("CSO", 32),
        ("PTR", 33),
        ("KCX", 34),
        ("CSD", 35),
        ("LLP", 36),
        ("CME", 37),
        ("MLY", 38),
        ("DAL", 39),
        ("TYS", 40),
        ("OCS", 41),
        ("M3L", 42),
        ("FME", 43),
        ("ALY", 44),
        ("HYP", 45),
        ("CAS", 46),
        ("CRO", 47),
        ("CSX", 48),
        ("DPR", 49),
        ("DGL", 50),
        ("DVA", 51),
        ("CSS", 52),
        ("DPN", 53),
        ("DSN", 54),
        ("DLE", 55),
        ("HIC", 56),
        ("NLE", 57),
        ("MVA", 58),
        ("MLZ", 59),
        ("CR2", 60),
        ("SAR", 61),
        ("DAR", 62),
        ("DLY", 63),
        ("YCM", 64),
        ("NRQ", 65),
        ("CGU", 66),
        ("R0TD", 67),
        ("MLE", 68),
        ("DAS", 69),
        ("DTR", 70),
        ("CXM", 71),
        ("TPQ", 72),
        ("DCY", 73),
        ("DSG", 74),
        ("DTY", 75),
        ("DHI", 76),
        ("MEN", 77),
        ("DTH", 78),
        ("SAC", 79),
        ("DGN", 80),
        ("AIB", 81),
        ("SMC", 82),
        ("IAS", 83),
        ("CIR", 84),
        ("BMT", 85),
        ("DIL", 86),
        ("FGA", 87),
        ("PHI", 88),
        ("CRQ", 89),
        ("SME", 90),
        ("GHP", 91),
        ("MHO", 92),
        ("NEP", 93),
        ("TRQ", 94),
        ("TOX", 95),
        ("ALC", 96),
        ("R3FG", 97),
        ("SCH", 98),
        ("MDO", 99),
        ("MAA", 100),
        ("GYS", 101),
        ("MK8", 102),
        ("CR8", 103),
        ("KPI", 104),
        ("SCY", 105),
        ("DHA", 106),
        ("OMY", 107),
        ("CAF", 108),
        ("R0AF", 109),
        ("SNN", 110),
        ("MHS", 111),
        ("MLU", 112),
        ("SNC", 113),
        ("PHD", 114),
        ("B3E", 115),
        ("MEA", 116),
        ("MED", 117),
        ("OAS", 118),
        ("GL3", 119),
        ("FVA", 120),
        ("PHL", 121),
        ("CRF", 122),
        ("OMZ", 123),
        ("BFD", 124),
        ("MEQ", 125),
        ("DAB", 126),
        ("AGM", 127),
        ("PSU", 128),
        ("R5MU", 129),
        ("R7MG", 130),
        ("OMG", 131),
        ("UR3", 132),
        ("OMC", 133),
        ("R2MG", 134),
        ("H2U", 135),
        ("R4SU", 136),
        ("OMU", 137),
        ("R4OC", 138),
        ("MA6", 139),
        ("M2G", 140),
        ("R1MA", 141),
        ("R6MZ", 142),
        ("CCC", 143),
        ("R2MA", 144),
        ("R1MG", 145),
        ("R5BU", 146),
        ("MIA", 147),
        ("DOC", 148),
        ("R8OG", 149),
        ("R5CM", 150),
        ("R3DR", 151),
        ("BRU", 152),
        ("CBR", 153),
        ("HOH", 154),
        ("DOD", 155),
        ("HEM", 156),
        ("SO4", 157),
        ("GOL", 158),
        ("EDO", 159),
        ("NAG", 160),
        ("PO4", 161),
        ("ACT", 162),
        ("PEG", 163),
        ("MAN", 164),
        ("FAD", 165),
        ("BMA", 166),
        ("ADP", 167),
        ("DMS", 168),
        ("ACE", 169),
        ("NH2", 170),
        ("MPD", 171),
        ("MES", 172),
        ("NAD", 173),
        ("NAP", 174),
        ("TRS", 175),
        ("ATP", 176),
        ("PG4", 177),
        ("GDP", 178),
        ("FUC", 179),
        ("FMT", 180),
        ("GAL", 181),
        ("PGE", 182),
        ("FMN", 183),
        ("PLP", 184),
        ("EPE", 185),
        ("SF4", 186),
        ("BME", 187),
        ("CIT", 188),
        ("BE7", 189),
        ("MRD", 190),
        ("MHA", 191),
        ("BU3", 192),
        ("PGO", 193),
        ("BU2", 194),
        ("PDO", 195),
        ("BU1", 196),
        ("PG6", 197),
        ("R1BO", 198),
        ("PE7", 199),
        ("PG5", 200),
        ("TFP", 201),
        ("DHD", 202),
        ("PEU", 203),
        ("TAU", 204),
        ("SBT", 205),
        ("SAL", 206),
        ("IOH", 207),
        ("IPA", 208),
        ("PIG", 209),
        ("B3P", 210),
        ("BTB", 211),
        ("NHE", 212),
        ("C8E", 213),
        ("OTE", 214),
        ("PE4", 215),
        ("XPE", 216),
        ("PE8", 217),
        ("P33", 218),
        ("N8E", 219),
        ("R2OS", 220),
        ("R1PS", 221),
        ("CPS", 222),
        ("DMX", 223),
        ("MPO", 224),
        ("GCD", 225),
        ("DXG", 226),
        ("CM5", 227),
        ("ACA", 228),
        ("ACN", 229),
        ("CCN", 230),
        ("GLC", 231),
        ("DR6", 232),
        ("NH4", 233),
        ("AZI", 234),
        ("BNG", 235),
        ("BOG", 236),
        ("BGC", 237),
        ("BCN", 238),
        ("BRO", 239),
        ("CAC", 240),
        ("CBX", 241),
        ("ACY", 242),
        ("CBM", 243),
        ("CLO", 244),
        ("R3CO", 245),
        ("NCO", 246),
        ("CU1", 247),
        ("CYN", 248),
        ("MA4", 249),
        ("TAR", 250),
        ("GLO", 251),
        ("MTL", 252),
        ("SOR", 253),
        ("DMU", 254),
        ("DDQ", 255),
        ("DMF", 256),
        ("DIO", 257),
        ("DOX", 258),
        ("R12P", 259),
        ("SDS", 260),
        ("LMT", 261),
        ("EOH", 262),
        ("EEE", 263),
        ("EGL", 264),
        ("FLO", 265),
        ("TRT", 266),
        ("FCY", 267),
        ("FRU", 268),
        ("GBL", 269),
        ("GPX", 270),
        ("HTO", 271),
        ("HTG", 272),
        ("B7G", 273),
        ("C10", 274),
        ("R16D", 275),
        ("HEZ", 276),
        ("IOD", 277),
        ("IDO", 278),
        ("ICI", 279),
        ("ICT", 280),
        ("TLA", 281),
        ("LAT", 282),
        ("LBT", 283),
        ("LDA", 284),
        ("MN3", 285),
        ("MRY", 286),
        ("MOH", 287),
        ("BEQ", 288),
        ("C15", 289),
        ("MG8", 290),
        ("POL", 291),
        ("NO3", 292),
        ("JEF", 293),
        ("P4C", 294),
        ("CE1", 295),
        ("DIA", 296),
        ("CXE", 297),
        ("IPH", 298),
        ("PIN", 299),
        ("R15P", 300),
        ("CRY", 301),
        ("PGR", 302),
        ("PGQ", 303),
        ("SPD", 304),
        ("SPK", 305),
        ("SPM", 306),
        ("SUC", 307),
        ("TBU", 308),
        ("TMA", 309),
        ("TEP", 310),
        ("SCN", 311),
        ("TRE", 312),
        ("ETF", 313),
        ("R144", 314),
        ("UMQ", 315),
        ("URE", 316),
        ("YT3", 317),
        ("ZN2", 318),
        ("FE2", 319),
        ("R3NI", 320),
        ("SIA", 321),
        ("XYP", 322),
        ("A2G", 323),
        ("GLA", 324),
        ("NDG", 325),
        ("NGA", 326),
        ("A", 327),
        ("C", 328),
        ("G", 329),
        ("I", 330),
        ("U", 331),
        ("N", 332),
        ("F", 333),
        ("K", 334),
        ("DA", 335),
        ("DC", 336),
        ("DG", 337),
        ("DI", 338),
        ("DT", 339),
        ("DU", 340),
        ("DN", 341),
        ("AG", 342),
        ("AL", 343),
        ("BA", 344),
        ("BR", 345),
        ("CA", 346),
        ("CD", 347),
        ("CL", 348),
        ("CM", 349),
        ("CN", 350),
        ("CO", 351),
        ("CS", 352),
        ("CU", 353),
        ("FE", 354),
        ("HG", 355),
        ("LI", 356),
        ("MG", 357),
        ("MN", 358),
        ("NA", 359),
        ("NI", 360),
        ("NO", 361),
        ("PB", 362),
        ("RB", 363),
        ("SR", 364),
        ("Y1", 365),
        ("ZN", 366),
        ("UNKNOWN", 367),
    ];
    let code = match index {
        0 => ResidueCode::ALA,
        1 => ResidueCode::ARG,
        2 => ResidueCode::ASN,
        3 => ResidueCode::ABA,
        4 => ResidueCode::ASP,
        5 => ResidueCode::ASX,
        6 => ResidueCode::CYS,
        7 => ResidueCode::CSH,
        8 => ResidueCode::GLN,
        9 => ResidueCode::GLU,
        10 => ResidueCode::GLX,
        11 => ResidueCode::GLY,
        12 => ResidueCode::HIS,
        13 => ResidueCode::ILE,
        14 => ResidueCode::LEU,
        15 => ResidueCode::LYS,
        16 => ResidueCode::MET,
        17 => ResidueCode::MSE,
        18 => ResidueCode::ORN,
        19 => ResidueCode::PHE,
        20 => ResidueCode::PRO,
        21 => ResidueCode::SER,
        22 => ResidueCode::THR,
        23 => ResidueCode::TRP,
        24 => ResidueCode::TYR,
        25 => ResidueCode::UNK,
        26 => ResidueCode::VAL,
        27 => ResidueCode::SEC,
        28 => ResidueCode::PYL,
        29 => ResidueCode::SEP,
        30 => ResidueCode::TPO,
        31 => ResidueCode::PCA,
        32 => ResidueCode::CSO,
        33 => ResidueCode::PTR,
        34 => ResidueCode::KCX,
        35 => ResidueCode::CSD,
        36 => ResidueCode::LLP,
        37 => ResidueCode::CME,
        38 => ResidueCode::MLY,
        39 => ResidueCode::DAL,
        40 => ResidueCode::TYS,
        41 => ResidueCode::OCS,
        42 => ResidueCode::M3L,
        43 => ResidueCode::FME,
        44 => ResidueCode::ALY,
        45 => ResidueCode::HYP,
        46 => ResidueCode::CAS,
        47 => ResidueCode::CRO,
        48 => ResidueCode::CSX,
        49 => ResidueCode::DPR,
        50 => ResidueCode::DGL,
        51 => ResidueCode::DVA,
        52 => ResidueCode::CSS,
        53 => ResidueCode::DPN,
        54 => ResidueCode::DSN,
        55 => ResidueCode::DLE,
        56 => ResidueCode::HIC,
        57 => ResidueCode::NLE,
        58 => ResidueCode::MVA,
        59 => ResidueCode::MLZ,
        60 => ResidueCode::CR2,
        61 => ResidueCode::SAR,
        62 => ResidueCode::DAR,
        63 => ResidueCode::DLY,
        64 => ResidueCode::YCM,
        65 => ResidueCode::NRQ,
        66 => ResidueCode::CGU,
        67 => ResidueCode::R0TD,
        68 => ResidueCode::MLE,
        69 => ResidueCode::DAS,
        70 => ResidueCode::DTR,
        71 => ResidueCode::CXM,
        72 => ResidueCode::TPQ,
        73 => ResidueCode::DCY,
        74 => ResidueCode::DSG,
        75 => ResidueCode::DTY,
        76 => ResidueCode::DHI,
        77 => ResidueCode::MEN,
        78 => ResidueCode::DTH,
        79 => ResidueCode::SAC,
        80 => ResidueCode::DGN,
        81 => ResidueCode::AIB,
        82 => ResidueCode::SMC,
        83 => ResidueCode::IAS,
        84 => ResidueCode::CIR,
        85 => ResidueCode::BMT,
        86 => ResidueCode::DIL,
        87 => ResidueCode::FGA,
        88 => ResidueCode::PHI,
        89 => ResidueCode::CRQ,
        90 => ResidueCode::SME,
        91 => ResidueCode::GHP,
        92 => ResidueCode::MHO,
        93 => ResidueCode::NEP,
        94 => ResidueCode::TRQ,
        95 => ResidueCode::TOX,
        96 => ResidueCode::ALC,
        97 => ResidueCode::R3FG,
        98 => ResidueCode::SCH,
        99 => ResidueCode::MDO,
        100 => ResidueCode::MAA,
        101 => ResidueCode::GYS,
        102 => ResidueCode::MK8,
        103 => ResidueCode::CR8,
        104 => ResidueCode::KPI,
        105 => ResidueCode::SCY,
        106 => ResidueCode::DHA,
        107 => ResidueCode::OMY,
        108 => ResidueCode::CAF,
        109 => ResidueCode::R0AF,
        110 => ResidueCode::SNN,
        111 => ResidueCode::MHS,
        112 => ResidueCode::MLU,
        113 => ResidueCode::SNC,
        114 => ResidueCode::PHD,
        115 => ResidueCode::B3E,
        116 => ResidueCode::MEA,
        117 => ResidueCode::MED,
        118 => ResidueCode::OAS,
        119 => ResidueCode::GL3,
        120 => ResidueCode::FVA,
        121 => ResidueCode::PHL,
        122 => ResidueCode::CRF,
        123 => ResidueCode::OMZ,
        124 => ResidueCode::BFD,
        125 => ResidueCode::MEQ,
        126 => ResidueCode::DAB,
        127 => ResidueCode::AGM,
        128 => ResidueCode::PSU,
        129 => ResidueCode::R5MU,
        130 => ResidueCode::R7MG,
        131 => ResidueCode::OMG,
        132 => ResidueCode::UR3,
        133 => ResidueCode::OMC,
        134 => ResidueCode::R2MG,
        135 => ResidueCode::H2U,
        136 => ResidueCode::R4SU,
        137 => ResidueCode::OMU,
        138 => ResidueCode::R4OC,
        139 => ResidueCode::MA6,
        140 => ResidueCode::M2G,
        141 => ResidueCode::R1MA,
        142 => ResidueCode::R6MZ,
        143 => ResidueCode::CCC,
        144 => ResidueCode::R2MA,
        145 => ResidueCode::R1MG,
        146 => ResidueCode::R5BU,
        147 => ResidueCode::MIA,
        148 => ResidueCode::DOC,
        149 => ResidueCode::R8OG,
        150 => ResidueCode::R5CM,
        151 => ResidueCode::R3DR,
        152 => ResidueCode::BRU,
        153 => ResidueCode::CBR,
        154 => ResidueCode::HOH,
        155 => ResidueCode::DOD,
        156 => ResidueCode::HEM,
        157 => ResidueCode::SO4,
        158 => ResidueCode::GOL,
        159 => ResidueCode::EDO,
        160 => ResidueCode::NAG,
        161 => ResidueCode::PO4,
        162 => ResidueCode::ACT,
        163 => ResidueCode::PEG,
        164 => ResidueCode::MAN,
        165 => ResidueCode::FAD,
        166 => ResidueCode::BMA,
        167 => ResidueCode::ADP,
        168 => ResidueCode::DMS,
        169 => ResidueCode::ACE,
        170 => ResidueCode::NH2,
        171 => ResidueCode::MPD,
        172 => ResidueCode::MES,
        173 => ResidueCode::NAD,
        174 => ResidueCode::NAP,
        175 => ResidueCode::TRS,
        176 => ResidueCode::ATP,
        177 => ResidueCode::PG4,
        178 => ResidueCode::GDP,
        179 => ResidueCode::FUC,
        180 => ResidueCode::FMT,
        181 => ResidueCode::GAL,
        182 => ResidueCode::PGE,
        183 => ResidueCode::FMN,
        184 => ResidueCode::PLP,
        185 => ResidueCode::EPE,
        186 => ResidueCode::SF4,
        187 => ResidueCode::BME,
        188 => ResidueCode::CIT,
        189 => ResidueCode::BE7,
        190 => ResidueCode::MRD,
        191 => ResidueCode::MHA,
        192 => ResidueCode::BU3,
        193 => ResidueCode::PGO,
        194 => ResidueCode::BU2,
        195 => ResidueCode::PDO,
        196 => ResidueCode::BU1,
        197 => ResidueCode::PG6,
        198 => ResidueCode::R1BO,
        199 => ResidueCode::PE7,
        200 => ResidueCode::PG5,
        201 => ResidueCode::TFP,
        202 => ResidueCode::DHD,
        203 => ResidueCode::PEU,
        204 => ResidueCode::TAU,
        205 => ResidueCode::SBT,
        206 => ResidueCode::SAL,
        207 => ResidueCode::IOH,
        208 => ResidueCode::IPA,
        209 => ResidueCode::PIG,
        210 => ResidueCode::B3P,
        211 => ResidueCode::BTB,
        212 => ResidueCode::NHE,
        213 => ResidueCode::C8E,
        214 => ResidueCode::OTE,
        215 => ResidueCode::PE4,
        216 => ResidueCode::XPE,
        217 => ResidueCode::PE8,
        218 => ResidueCode::P33,
        219 => ResidueCode::N8E,
        220 => ResidueCode::R2OS,
        221 => ResidueCode::R1PS,
        222 => ResidueCode::CPS,
        223 => ResidueCode::DMX,
        224 => ResidueCode::MPO,
        225 => ResidueCode::GCD,
        226 => ResidueCode::DXG,
        227 => ResidueCode::CM5,
        228 => ResidueCode::ACA,
        229 => ResidueCode::ACN,
        230 => ResidueCode::CCN,
        231 => ResidueCode::GLC,
        232 => ResidueCode::DR6,
        233 => ResidueCode::NH4,
        234 => ResidueCode::AZI,
        235 => ResidueCode::BNG,
        236 => ResidueCode::BOG,
        237 => ResidueCode::BGC,
        238 => ResidueCode::BCN,
        239 => ResidueCode::BRO,
        240 => ResidueCode::CAC,
        241 => ResidueCode::CBX,
        242 => ResidueCode::ACY,
        243 => ResidueCode::CBM,
        244 => ResidueCode::CLO,
        245 => ResidueCode::R3CO,
        246 => ResidueCode::NCO,
        247 => ResidueCode::CU1,
        248 => ResidueCode::CYN,
        249 => ResidueCode::MA4,
        250 => ResidueCode::TAR,
        251 => ResidueCode::GLO,
        252 => ResidueCode::MTL,
        253 => ResidueCode::SOR,
        254 => ResidueCode::DMU,
        255 => ResidueCode::DDQ,
        256 => ResidueCode::DMF,
        257 => ResidueCode::DIO,
        258 => ResidueCode::DOX,
        259 => ResidueCode::R12P,
        260 => ResidueCode::SDS,
        261 => ResidueCode::LMT,
        262 => ResidueCode::EOH,
        263 => ResidueCode::EEE,
        264 => ResidueCode::EGL,
        265 => ResidueCode::FLO,
        266 => ResidueCode::TRT,
        267 => ResidueCode::FCY,
        268 => ResidueCode::FRU,
        269 => ResidueCode::GBL,
        270 => ResidueCode::GPX,
        271 => ResidueCode::HTO,
        272 => ResidueCode::HTG,
        273 => ResidueCode::B7G,
        274 => ResidueCode::C10,
        275 => ResidueCode::R16D,
        276 => ResidueCode::HEZ,
        277 => ResidueCode::IOD,
        278 => ResidueCode::IDO,
        279 => ResidueCode::ICI,
        280 => ResidueCode::ICT,
        281 => ResidueCode::TLA,
        282 => ResidueCode::LAT,
        283 => ResidueCode::LBT,
        284 => ResidueCode::LDA,
        285 => ResidueCode::MN3,
        286 => ResidueCode::MRY,
        287 => ResidueCode::MOH,
        288 => ResidueCode::BEQ,
        289 => ResidueCode::C15,
        290 => ResidueCode::MG8,
        291 => ResidueCode::POL,
        292 => ResidueCode::NO3,
        293 => ResidueCode::JEF,
        294 => ResidueCode::P4C,
        295 => ResidueCode::CE1,
        296 => ResidueCode::DIA,
        297 => ResidueCode::CXE,
        298 => ResidueCode::IPH,
        299 => ResidueCode::PIN,
        300 => ResidueCode::R15P,
        301 => ResidueCode::CRY,
        302 => ResidueCode::PGR,
        303 => ResidueCode::PGQ,
        304 => ResidueCode::SPD,
        305 => ResidueCode::SPK,
        306 => ResidueCode::SPM,
        307 => ResidueCode::SUC,
        308 => ResidueCode::TBU,
        309 => ResidueCode::TMA,
        310 => ResidueCode::TEP,
        311 => ResidueCode::SCN,
        312 => ResidueCode::TRE,
        313 => ResidueCode::ETF,
        314 => ResidueCode::R144,
        315 => ResidueCode::UMQ,
        316 => ResidueCode::URE,
        317 => ResidueCode::YT3,
        318 => ResidueCode::ZN2,
        319 => ResidueCode::FE2,
        320 => ResidueCode::R3NI,
        321 => ResidueCode::SIA,
        322 => ResidueCode::XYP,
        323 => ResidueCode::A2G,
        324 => ResidueCode::GLA,
        325 => ResidueCode::NDG,
        326 => ResidueCode::NGA,
        327 => ResidueCode::A,
        328 => ResidueCode::C,
        329 => ResidueCode::G,
        330 => ResidueCode::I,
        331 => ResidueCode::U,
        332 => ResidueCode::N,
        333 => ResidueCode::F,
        334 => ResidueCode::K,
        335 => ResidueCode::DA,
        336 => ResidueCode::DC,
        337 => ResidueCode::DG,
        338 => ResidueCode::DI,
        339 => ResidueCode::DT,
        340 => ResidueCode::DU,
        341 => ResidueCode::DN,
        342 => ResidueCode::AG,
        343 => ResidueCode::AL,
        344 => ResidueCode::BA,
        345 => ResidueCode::BR,
        346 => ResidueCode::CA,
        347 => ResidueCode::CD,
        348 => ResidueCode::CL,
        349 => ResidueCode::CM,
        350 => ResidueCode::CN,
        351 => ResidueCode::CO,
        352 => ResidueCode::CS,
        353 => ResidueCode::CU,
        354 => ResidueCode::FE,
        355 => ResidueCode::HG,
        356 => ResidueCode::LI,
        357 => ResidueCode::MG,
        358 => ResidueCode::MN,
        359 => ResidueCode::NA,
        360 => ResidueCode::NI,
        361 => ResidueCode::NO,
        362 => ResidueCode::PB,
        363 => ResidueCode::RB,
        364 => ResidueCode::SR,
        365 => ResidueCode::Y1,
        366 => ResidueCode::ZN,
        367 => ResidueCode::UNKNOWN,
        _ => unreachable!("frozen annex discriminants end at 367"),
    };
    code.tap_variants(&VARIANTS);
    code
}

/// No-op witness so the (variant, discriminant) witness table above is
/// referenced by the lookup path and stays compile-checked.
trait TapVariants {
    fn tap_variants(&self, _: &[(&'static str, u16)]);
}
impl TapVariants for ResidueCode {
    fn tap_variants(&self, _: &[(&'static str, u16)]) {}
}

/// Frozen all-codes product: for ALL 368 annex tuples assert the
/// discriminant, the exact quoted canonical JSON, literal-JSON
/// deserialization to the named enum value and a full roundtrip; exact 368
/// census. The 25 digit-start wire names appear verbatim (no R prefix);
/// UNKNOWN is distinct from UNK.
#[test]
fn residue_serde_all_codes() {
    let mut checked = 0usize;
    let mut digit_start = 0usize;
    for (variant, discriminant, wire) in ANNEX {
        let code = code_for(variant);
        assert_eq!(code as u16, discriminant, "{variant}: discriminant");
        let expected_json = format!("\"{wire}\"");
        let json = serde_json::to_string(&code).unwrap_or_else(|e| panic!("{variant}: {e}"));
        assert_eq!(
            json, expected_json,
            "{variant}: exact quoted canonical JSON"
        );
        let literal = format!("\"{wire}\"");
        let parsed: ResidueCode =
            serde_json::from_str(&literal).unwrap_or_else(|e| panic!("{variant} ({wire}): {e}"));
        assert_eq!(parsed, code, "{variant}: literal JSON deserializes");
        let round: ResidueCode = serde_json::from_str(&json).unwrap();
        assert_eq!(round, code, "{variant}: roundtrip");
        if wire.starts_with(|c: char| c.is_ascii_digit()) {
            digit_start += 1;
        }
        checked += 1;
    }
    assert_eq!(checked, 368, "exact 368 census");
    assert_eq!(
        digit_start, 25,
        "all 25 digit-start names included, no R prefix"
    );
    // UNKNOWN is distinct from UNK on the wire and as values.
    assert_ne!(ResidueCode::UNKNOWN, ResidueCode::UNK);
    assert_eq!(
        serde_json::to_string(&ResidueCode::UNKNOWN).unwrap(),
        "\"UNKNOWN\""
    );
    assert_eq!(serde_json::to_string(&ResidueCode::UNK).unwrap(), "\"UNK\"");
}

/// Frozen invalid-input regressions: every literal string below must ERROR,
/// and the JSON scalars/containers must ERROR with type/shape errors. None
/// of these 18 inputs may be treated as an UNKNOWN success. Stable
/// error-message wording is NOT a promised contract (only failure itself).
#[test]
fn residue_serde_invalid_input() {
    const INVALID_STRINGS: [&str; 12] = [
        "", "???", "R0TD", "ala", "unknown", "UNKNOWNx", "0td", "H2O", "TRY", "+A", " ALA", "ALA ",
    ];
    let mut rejected = 0usize;
    for input in INVALID_STRINGS {
        let json = serde_json::to_string(input).unwrap();
        assert!(
            serde_json::from_str::<ResidueCode>(&json).is_err(),
            "{input:?} must error"
        );
        rejected += 1;
    }
    const INVALID_JSON: [&str; 6] = ["null", "0", "-1", "true", "[]", "{}"];
    for input in INVALID_JSON {
        assert!(
            serde_json::from_str::<ResidueCode>(input).is_err(),
            "{input} must error"
        );
        rejected += 1;
    }
    assert_eq!(rejected, 18, "exact 18 invalid inputs rejected");
}

/// External derive-consumer proof: a downstream struct deriving
/// Serialize/Deserialize with a ResidueCode field round-trips the literal
/// documents exactly. This proves derive compatibility; it is not a wrapper
/// users are required to write.
#[test]
fn residue_serde_derived_consumer() {
    #[derive(Debug, Serialize, Deserialize, PartialEq)]
    struct Consumer {
        code: ResidueCode,
    }

    for (literal, code) in [
        ("{\"code\":\"0TD\"}", ResidueCode::R0TD),
        ("{\"code\":\"UNK\"}", ResidueCode::UNK),
        ("{\"code\":\"UNKNOWN\"}", ResidueCode::UNKNOWN),
    ] {
        let parsed: Consumer = serde_json::from_str(literal).unwrap();
        assert_eq!(parsed.code, code, "{literal}");
        let serialized = serde_json::to_string(&parsed).unwrap();
        assert_eq!(serialized, literal, "{literal}: exact both directions");
    }
}
