[package]
name = "cosmolkit-py"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
publish = false

[lib]
name = "cosmolkit"
crate-type = ["cdylib", "rlib"]
doc = false

[dependencies]
cosmolkit-core = { version = "0.2.13", path = "../crates/cosmolkit-core" }
pyo3-stub-gen = { version = "0.23.0", default-features = false, optional = true }
pyo3-stub-gen-derive = "0.23.0"
pyo3 = { version = "0.29.0", default-features = false }
numpy = "0.29.0"
glam = "0.33.5"
serde_json = "1"

[features]
default = ["release-abi3-py39"]
extension-module = ["pyo3/macros", "pyo3/extension-module"]
release-abi3-py39 = ["extension-module", "pyo3/abi3-py39"]
dev-abi3-py310 = ["extension-module", "pyo3/abi3-py310"]
stubgen = ["dep:pyo3-stub-gen"]
dev-stub = ["dev-abi3-py310", "stubgen"]

[[bin]]
name = "stub_gen"
path = "src/bin/stub_gen.rs"
required-features = ["stubgen"]
