from __future__ import annotations
# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import enum
import typing
import types
__all__ = [
    "DescriptorError",
    "DescriptorReadError",
    "FingerprintError",
    "MorganReadError",
    "SmilesWriteError",
    "SmilesError",
    "DrawingError",
    "OperationError",
    "__version__",
    "_binding_profile",
    "AdditionalOutput",
    "Coordinate2DParams",
    "CrippenTotals",
    "Element",
    "ElementInfo",
    "Fingerprint",
    "LabuteAsaContributions",
    "Molecule",
    "MorganParams",
    "RotatableBondsOptions",
    "SmilesParseParams",
    "SmilesWriteParams",
    "SparseBitFingerprint",
    "SparseCountFingerprint",
    "SparseCountFingerprint32",
    "element_info",
    "version",
]

@typing.final
class AdditionalOutput:
    r"""
    One uniquely owned canonical metadata value, with detached read results.
    """
    @staticmethod
    def default() -> AdditionalOutput: ...
    def allocate_atom_counts(self) -> None: ...
    def allocate_atom_to_bits(self) -> None: ...
    def allocate_bit_info_map(self) -> None: ...
    def allocate_bit_paths(self) -> None: ...
    def allocate_atoms_per_bit(self) -> None: ...
    def atom_counts(self) -> typing.Optional[builtins.list[builtins.int]]: ...
    def atom_to_bits(self) -> typing.Optional[builtins.list[builtins.list[builtins.int]]]: ...
    def bit_info_map(self) -> typing.Optional[builtins.dict[builtins.int, builtins.list[tuple[builtins.int, builtins.int]]]]: ...
    def bit_paths(self) -> typing.Optional[builtins.dict[builtins.int, builtins.list[builtins.list[builtins.int]]]]: ...
    def atoms_per_bit(self) -> typing.Optional[builtins.dict[builtins.int, builtins.list[builtins.list[builtins.int]]]]: ...

@typing.final
class Coordinate2DParams:
    r"""
    Immutable detached parameters projected from the public facade.
    """
    @property
    def coordinate_map(self) -> builtins.dict[builtins.int, builtins.list[builtins.float]]: ...
    @property
    def canonical_orientation(self) -> builtins.bool: ...
    @property
    def clear_existing_2d(self) -> builtins.bool: ...
    @property
    def flips_per_sample(self) -> builtins.int: ...
    @property
    def samples(self) -> builtins.int: ...
    @property
    def sample_seed(self) -> builtins.int: ...
    @property
    def permute_degree_four(self) -> builtins.bool: ...
    @property
    def force_rdkit(self) -> builtins.bool: ...
    @property
    def use_ring_templates(self) -> builtins.bool: ...
    def __new__(cls, coordinate_map: typing.Optional[typing.Mapping[builtins.int, typing.Sequence[builtins.float]]] = None, *, canonical_orientation: builtins.bool = False, clear_existing_2d: builtins.bool = True, flips_per_sample: builtins.int = 0, samples: builtins.int = 0, sample_seed: builtins.int = 0, permute_degree_four: builtins.bool = False, force_rdkit: builtins.bool = False, use_ring_templates: builtins.bool = False) -> Coordinate2DParams: ...

@typing.final
class CrippenTotals:
    @property
    def logp(self) -> builtins.float: ...
    @property
    def molar_refractivity(self) -> builtins.float: ...

@typing.final
class Element:
    DUMMY: typing.ClassVar[Element]
    H: typing.ClassVar[Element]
    HE: typing.ClassVar[Element]
    LI: typing.ClassVar[Element]
    BE: typing.ClassVar[Element]
    B: typing.ClassVar[Element]
    C: typing.ClassVar[Element]
    N: typing.ClassVar[Element]
    O: typing.ClassVar[Element]
    F: typing.ClassVar[Element]
    NE: typing.ClassVar[Element]
    NA: typing.ClassVar[Element]
    MG: typing.ClassVar[Element]
    AL: typing.ClassVar[Element]
    SI: typing.ClassVar[Element]
    P: typing.ClassVar[Element]
    S: typing.ClassVar[Element]
    CL: typing.ClassVar[Element]
    AR: typing.ClassVar[Element]
    K: typing.ClassVar[Element]
    CA: typing.ClassVar[Element]
    SC: typing.ClassVar[Element]
    TI: typing.ClassVar[Element]
    V: typing.ClassVar[Element]
    CR: typing.ClassVar[Element]
    MN: typing.ClassVar[Element]
    FE: typing.ClassVar[Element]
    CO: typing.ClassVar[Element]
    NI: typing.ClassVar[Element]
    CU: typing.ClassVar[Element]
    ZN: typing.ClassVar[Element]
    GA: typing.ClassVar[Element]
    GE: typing.ClassVar[Element]
    AS: typing.ClassVar[Element]
    SE: typing.ClassVar[Element]
    BR: typing.ClassVar[Element]
    KR: typing.ClassVar[Element]
    RB: typing.ClassVar[Element]
    SR: typing.ClassVar[Element]
    Y: typing.ClassVar[Element]
    ZR: typing.ClassVar[Element]
    NB: typing.ClassVar[Element]
    MO: typing.ClassVar[Element]
    TC: typing.ClassVar[Element]
    RU: typing.ClassVar[Element]
    RH: typing.ClassVar[Element]
    PD: typing.ClassVar[Element]
    AG: typing.ClassVar[Element]
    CD: typing.ClassVar[Element]
    IN: typing.ClassVar[Element]
    SN: typing.ClassVar[Element]
    SB: typing.ClassVar[Element]
    TE: typing.ClassVar[Element]
    I: typing.ClassVar[Element]
    XE: typing.ClassVar[Element]
    CS: typing.ClassVar[Element]
    BA: typing.ClassVar[Element]
    LA: typing.ClassVar[Element]
    CE: typing.ClassVar[Element]
    PR: typing.ClassVar[Element]
    ND: typing.ClassVar[Element]
    PM: typing.ClassVar[Element]
    SM: typing.ClassVar[Element]
    EU: typing.ClassVar[Element]
    GD: typing.ClassVar[Element]
    TB: typing.ClassVar[Element]
    DY: typing.ClassVar[Element]
    HO: typing.ClassVar[Element]
    ER: typing.ClassVar[Element]
    TM: typing.ClassVar[Element]
    YB: typing.ClassVar[Element]
    LU: typing.ClassVar[Element]
    HF: typing.ClassVar[Element]
    TA: typing.ClassVar[Element]
    W: typing.ClassVar[Element]
    RE: typing.ClassVar[Element]
    OS: typing.ClassVar[Element]
    IR: typing.ClassVar[Element]
    PT: typing.ClassVar[Element]
    AU: typing.ClassVar[Element]
    HG: typing.ClassVar[Element]
    TL: typing.ClassVar[Element]
    PB: typing.ClassVar[Element]
    BI: typing.ClassVar[Element]
    PO: typing.ClassVar[Element]
    AT: typing.ClassVar[Element]
    RN: typing.ClassVar[Element]
    FR: typing.ClassVar[Element]
    RA: typing.ClassVar[Element]
    AC: typing.ClassVar[Element]
    TH: typing.ClassVar[Element]
    PA: typing.ClassVar[Element]
    U: typing.ClassVar[Element]
    NP: typing.ClassVar[Element]
    PU: typing.ClassVar[Element]
    AM: typing.ClassVar[Element]
    CM: typing.ClassVar[Element]
    BK: typing.ClassVar[Element]
    CF: typing.ClassVar[Element]
    ES: typing.ClassVar[Element]
    FM: typing.ClassVar[Element]
    MD: typing.ClassVar[Element]
    NO: typing.ClassVar[Element]
    LR: typing.ClassVar[Element]
    RF: typing.ClassVar[Element]
    DB: typing.ClassVar[Element]
    SG: typing.ClassVar[Element]
    BH: typing.ClassVar[Element]
    HS: typing.ClassVar[Element]
    MT: typing.ClassVar[Element]
    DS: typing.ClassVar[Element]
    RG: typing.ClassVar[Element]
    CN: typing.ClassVar[Element]
    NH: typing.ClassVar[Element]
    FL: typing.ClassVar[Element]
    MC: typing.ClassVar[Element]
    LV: typing.ClassVar[Element]
    TS: typing.ClassVar[Element]
    OG: typing.ClassVar[Element]
    def __eq__(self, value: builtins.object, /) -> builtins.bool | types.NotImplementedType: ...
    def __ne__(self, value: builtins.object, /) -> builtins.bool | types.NotImplementedType: ...
    def __hash__(self) -> builtins.int: ...
    @staticmethod
    def from_atomic_number(atomic_number: builtins.int) -> typing.Optional[Element]: ...
    @staticmethod
    def from_symbol(symbol: builtins.str) -> typing.Optional[Element]: ...
    def atomic_number(self) -> builtins.int: ...
    def symbol(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class ElementInfo:
    def element(self) -> Element: ...
    def symbol(self) -> builtins.str: ...
    def atomic_number(self) -> builtins.int: ...
    def period(self) -> builtins.int: ...
    def outer_electrons(self) -> builtins.int: ...
    def valences(self) -> builtins.list[builtins.int]: ...
    def rb0(self) -> builtins.float: ...
    def atomic_weight(self) -> builtins.float: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class Fingerprint:
    def n_bits(self) -> builtins.int: ...
    def on_bits(self) -> builtins.list[builtins.int]: ...
    def __len__(self) -> builtins.int: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class LabuteAsaContributions:
    @property
    def asa(self) -> builtins.float: ...
    @property
    def atom_contributions(self) -> builtins.list[builtins.float]: ...
    @property
    def hydrogen_contribution(self) -> builtins.float: ...

@typing.final
class Molecule:
    r"""
    Python ownership wraps the ONE live runtime value, not detached chemistry.
    """
    def num_amide_bonds(self) -> builtins.int:
        r"""
        Descriptor query through the canonical public Rust method.
        """
    def num_spiro_atoms(self) -> builtins.int:
        r"""
        Descriptor query through the canonical public Rust method.
        """
    def num_bridgehead_atoms(self) -> builtins.int:
        r"""
        Descriptor query through the canonical public Rust method.
        """
    def num_atom_stereo_centers(self) -> builtins.int:
        r"""
        Descriptor query through the canonical public Rust method.
        """
    def num_unspecified_atom_stereo_centers(self) -> builtins.int:
        r"""
        Descriptor query through the canonical public Rust method.
        """
    def num_rotatable_bonds(self) -> builtins.int:
        r"""
        Descriptor query through the canonical public Rust method.
        """
    def num_rotatable_bonds_with_params(self, params: RotatableBondsOptions) -> builtins.int:
        r"""
        Descriptor query through the canonical public Rust method.
        """
    def molecular_weight_with_params(self, only_heavy: builtins.bool) -> builtins.float:
        r"""
        Descriptor query through the canonical public Rust method.
        """
    def exact_molecular_weight_with_params(self, only_heavy: builtins.bool) -> builtins.float:
        r"""
        Descriptor query through the canonical public Rust method.
        """
    def molecular_formula_with_params(self, separate_isotopes: builtins.bool, abbreviate_h_isotopes: builtins.bool) -> builtins.str:
        r"""
        Descriptor query through the canonical public Rust method.
        """
    def molecular_weight(self) -> builtins.float:
        r"""
        Descriptor query through the canonical public Rust method.
        """
    def exact_molecular_weight(self) -> builtins.float:
        r"""
        Descriptor query through the canonical public Rust method.
        """
    def molecular_formula(self) -> builtins.str:
        r"""
        Descriptor query through the canonical public Rust method.
        """
    def num_heavy_atoms(self) -> builtins.int:
        r"""
        Experimental read-only query using the canonical public facade.
        Read-only descriptor through the canonical public Rust method.
        """
    def total_atom_count(self) -> builtins.int:
        r"""
        Read-only descriptor through the canonical public Rust method.
        """
    def lipinski_hba(self) -> builtins.int:
        r"""
        Read-only descriptor through the canonical public Rust method.
        """
    def lipinski_hbd(self) -> builtins.int:
        r"""
        Read-only descriptor through the canonical public Rust method.
        """
    def fraction_csp3(self) -> builtins.float:
        r"""
        Read-only descriptor through the canonical public Rust method.
        """
    def num_heteroatoms(self) -> builtins.int:
        r"""
        Read-only descriptor through the canonical public Rust method.
        """
    def num_hba(self) -> builtins.int:
        r"""
        Read-only descriptor through the canonical public Rust method.
        """
    def num_hbd(self) -> builtins.int:
        r"""
        Read-only descriptor through the canonical public Rust method.
        """
    def num_rings(self) -> builtins.int:
        r"""
        Read-only descriptor through the canonical public Rust method.
        """
    def num_heterocycles(self) -> builtins.int:
        r"""
        Read-only descriptor through the canonical public Rust method.
        """
    def num_aromatic_rings(self) -> builtins.int:
        r"""
        Read-only descriptor through the canonical public Rust method.
        """
    def num_saturated_rings(self) -> builtins.int:
        r"""
        Read-only descriptor through the canonical public Rust method.
        """
    def num_aliphatic_rings(self) -> builtins.int:
        r"""
        Read-only descriptor through the canonical public Rust method.
        """
    def num_aromatic_heterocycles(self) -> builtins.int:
        r"""
        Read-only descriptor through the canonical public Rust method.
        """
    def num_aromatic_carbocycles(self) -> builtins.int:
        r"""
        Read-only descriptor through the canonical public Rust method.
        """
    def num_aliphatic_heterocycles(self) -> builtins.int:
        r"""
        Read-only descriptor through the canonical public Rust method.
        """
    def num_aliphatic_carbocycles(self) -> builtins.int:
        r"""
        Read-only descriptor through the canonical public Rust method.
        """
    def num_saturated_heterocycles(self) -> builtins.int:
        r"""
        Read-only descriptor through the canonical public Rust method.
        """
    def num_saturated_carbocycles(self) -> builtins.int:
        r"""
        Read-only descriptor through the canonical public Rust method.
        """
    def chi_0(self) -> builtins.float:
        r"""
        Degree-based Chi0 through the canonical public Rust method.
        """
    def chi_1(self) -> builtins.float:
        r"""
        Degree-based Chi1 through the canonical public Rust method.
        """
    def hall_kier_alpha(self) -> builtins.float: ...
    def hall_kier_alpha_with_contributions(self) -> tuple[builtins.float, builtins.list[builtins.float]]:
        r"""
        Experimental read-only query using the canonical public facade.
        """
    def kappa_1(self) -> builtins.float:
        r"""
        Experimental read-only query using the canonical public facade.
        """
    def kappa_2(self) -> builtins.float:
        r"""
        Experimental read-only query using the canonical public facade.
        """
    def kappa_3(self) -> builtins.float:
        r"""
        Experimental read-only query using the canonical public facade.
        """
    def phi(self) -> builtins.float:
        r"""
        Experimental read-only query using the canonical public facade.
        """
    def mqns(self, force: builtins.bool = False) -> builtins.list[builtins.int]:
        r"""
        Experimental read-only query using the canonical public facade.
        All 42 components; the source ignores force and performs no cache write.
        """
    def chi_0_v(self) -> builtins.float:
        r"""
        Experimental read-only query using the canonical public facade.
        Recomputes only; no vector-property caching or force parameter.
        Requires existing prepared valence only; missing/reset rings succeed.
        """
    def chi_1_v(self) -> builtins.float:
        r"""
        Experimental read-only query using the canonical public facade.
        Recomputes only; no vector-property caching or force parameter.
        Requires existing prepared valence only; missing/reset rings succeed.
        """
    def chi_2_v(self) -> builtins.float:
        r"""
        Experimental read-only query using the canonical public facade.
        Recomputes only; no vector-property caching or force parameter.
        Requires existing prepared valence only; missing/reset rings succeed.
        """
    def chi_3_v(self) -> builtins.float:
        r"""
        Experimental read-only query using the canonical public facade.
        Recomputes only; no vector-property caching or force parameter.
        Requires existing prepared valence only; missing/reset rings succeed.
        """
    def chi_4_v(self) -> builtins.float:
        r"""
        Experimental read-only query using the canonical public facade.
        Recomputes only; no vector-property caching or force parameter.
        Requires existing prepared valence only; missing/reset rings succeed.
        """
    def chi_n_v(self, order: builtins.int) -> builtins.float:
        r"""
        Experimental read-only query using the canonical public facade.
        Recomputes only; no vector-property caching or force parameter.
        Requires existing prepared valence only; missing/reset rings succeed.
        """
    def chi_0_n(self) -> builtins.float:
        r"""
        Experimental read-only query using the canonical public facade.
        Recomputes only; no vector-property caching or force parameter.
        Requires existing prepared valence only; missing/reset rings succeed.
        """
    def chi_1_n(self) -> builtins.float:
        r"""
        Experimental read-only query using the canonical public facade.
        Recomputes only; no vector-property caching or force parameter.
        Requires existing prepared valence only; missing/reset rings succeed.
        """
    def chi_2_n(self) -> builtins.float:
        r"""
        Experimental read-only query using the canonical public facade.
        Recomputes only; no vector-property caching or force parameter.
        Requires existing prepared valence only; missing/reset rings succeed.
        """
    def chi_3_n(self) -> builtins.float:
        r"""
        Experimental read-only query using the canonical public facade.
        Recomputes only; no vector-property caching or force parameter.
        Requires existing prepared valence only; missing/reset rings succeed.
        """
    def chi_4_n(self) -> builtins.float:
        r"""
        Experimental read-only query using the canonical public facade.
        Recomputes only; no vector-property caching or force parameter.
        Requires existing prepared valence only; missing/reset rings succeed.
        """
    def chi_n_n(self, order: builtins.int) -> builtins.float:
        r"""
        Experimental read-only query using the canonical public facade.
        Recomputes only; no vector-property caching or force parameter.
        Requires existing prepared valence only; missing/reset rings succeed.
        """
    @staticmethod
    def new() -> Molecule: ...
    @staticmethod
    def from_smiles(smiles: builtins.str) -> Molecule: ...
    @staticmethod
    def from_smiles_with_params(input: builtins.str, params: SmilesParseParams) -> Molecule: ...
    def num_atoms(self) -> builtins.int: ...
    def num_bonds(self) -> builtins.int: ...
    def to_smiles(self) -> builtins.str: ...
    def to_smiles_with_params(self, params: SmilesWriteParams) -> builtins.str: ...
    def morgan_fingerprint(self) -> Fingerprint: ...
    def morgan_sparse_fingerprint(self) -> SparseBitFingerprint: ...
    def morgan_sparse_count_fingerprint(self) -> SparseCountFingerprint: ...
    def morgan_count_fingerprint(self) -> SparseCountFingerprint32: ...
    def coordinates_2d(self) -> typing.Optional[builtins.list[builtins.list[builtins.float]]]: ...
    def with_2d_coordinates(self) -> Molecule: ...
    def with_2d_coordinates_with_params(self, params: Coordinate2DParams) -> Molecule: ...
    def to_svg(self, width: builtins.int, height: builtins.int) -> builtins.str:
        r"""
        Experimental SVG; required dimensions follow the current registry.
        """
    def to_png(self, width: builtins.int, height: builtins.int) -> builtins.bytes:
        r"""
        Experimental PNG bytes from the same public drawing owner.
        """
    def write_svg(self, path: builtins.str, width: builtins.int, height: builtins.int) -> None: ...
    def write_png(self, path: builtins.str, width: builtins.int, height: builtins.int) -> None: ...
    def crippen_descriptors(self) -> CrippenTotals: ...
    def labute_asa(self) -> builtins.float: ...
    def labute_asa_contributions(self) -> LabuteAsaContributions: ...
    def tpsa(self) -> builtins.float: ...
    def slogp_vsa(self) -> builtins.list[builtins.float]: ...
    def smr_vsa(self) -> builtins.list[builtins.float]: ...
    def slogp_vsa_1(self) -> builtins.float: ...
    def slogp_vsa_2(self) -> builtins.float: ...
    def slogp_vsa_3(self) -> builtins.float: ...
    def slogp_vsa_4(self) -> builtins.float: ...
    def slogp_vsa_5(self) -> builtins.float: ...
    def slogp_vsa_6(self) -> builtins.float: ...
    def slogp_vsa_7(self) -> builtins.float: ...
    def slogp_vsa_8(self) -> builtins.float: ...
    def slogp_vsa_9(self) -> builtins.float: ...
    def slogp_vsa_10(self) -> builtins.float: ...
    def slogp_vsa_11(self) -> builtins.float: ...
    def slogp_vsa_12(self) -> builtins.float: ...
    def smr_vsa_1(self) -> builtins.float: ...
    def smr_vsa_2(self) -> builtins.float: ...
    def smr_vsa_3(self) -> builtins.float: ...
    def smr_vsa_4(self) -> builtins.float: ...
    def smr_vsa_5(self) -> builtins.float: ...
    def smr_vsa_6(self) -> builtins.float: ...
    def smr_vsa_7(self) -> builtins.float: ...
    def smr_vsa_8(self) -> builtins.float: ...
    def smr_vsa_9(self) -> builtins.float: ...
    def smr_vsa_10(self) -> builtins.float: ...
    def crippen_descriptors_with_params(self, include_hydrogens: builtins.bool, force: builtins.bool) -> CrippenTotals: ...
    def labute_asa_with_params(self, include_hydrogens: builtins.bool, force: builtins.bool) -> builtins.float: ...
    def labute_asa_contributions_with_params(self, include_hydrogens: builtins.bool, force: builtins.bool) -> LabuteAsaContributions: ...
    def tpsa_with_params(self, include_sulfur_phosphorus: builtins.bool, force: builtins.bool) -> builtins.float: ...
    def slogp_vsa_with_params(self, bins: typing.Optional[typing.Sequence[builtins.float]], force: builtins.bool) -> builtins.list[builtins.float]: ...
    def smr_vsa_with_params(self, bins: typing.Optional[typing.Sequence[builtins.float]], force: builtins.bool) -> builtins.list[builtins.float]: ...
    def qed(self) -> builtins.float: ...
    def chi_0_v_with_params(self, force: builtins.bool) -> builtins.float: ...
    def chi_1_v_with_params(self, force: builtins.bool) -> builtins.float: ...
    def chi_2_v_with_params(self, force: builtins.bool) -> builtins.float: ...
    def chi_3_v_with_params(self, force: builtins.bool) -> builtins.float: ...
    def chi_4_v_with_params(self, force: builtins.bool) -> builtins.float: ...
    def chi_n_v_with_params(self, order: builtins.int, force: builtins.bool) -> builtins.float: ...
    def chi_0_n_with_params(self, force: builtins.bool) -> builtins.float: ...
    def chi_1_n_with_params(self, force: builtins.bool) -> builtins.float: ...
    def chi_2_n_with_params(self, force: builtins.bool) -> builtins.float: ...
    def chi_3_n_with_params(self, force: builtins.bool) -> builtins.float: ...
    def chi_4_n_with_params(self, force: builtins.bool) -> builtins.float: ...
    def chi_n_n_with_params(self, order: builtins.int, force: builtins.bool) -> builtins.float: ...

@typing.final
class MorganParams:
    @property
    def radius(self) -> builtins.int: ...
    @property
    def include_chirality(self) -> builtins.bool: ...
    @property
    def use_bond_types(self) -> builtins.bool: ...
    @property
    def include_ring_membership(self) -> builtins.bool: ...
    @property
    def only_nonzero_invariants(self) -> builtins.bool: ...
    @property
    def include_redundant_environments(self) -> builtins.bool: ...
    @property
    def fp_size(self) -> builtins.int: ...
    @property
    def count_simulation(self) -> builtins.bool: ...
    @property
    def count_bounds(self) -> builtins.list[builtins.int]: ...
    @property
    def bits_per_feature(self) -> builtins.int: ...
    def __new__(cls, *, radius: builtins.int = 3, include_chirality: builtins.bool = False, use_bond_types: builtins.bool = True, include_ring_membership: builtins.bool = True, only_nonzero_invariants: builtins.bool = False, include_redundant_environments: builtins.bool = False, fp_size: builtins.int = 2048, count_simulation: builtins.bool = False, count_bounds: typing.Optional[typing.Sequence[builtins.int]] = None, bits_per_feature: builtins.int = 1) -> MorganParams: ...

@typing.final
class SmilesParseParams:
    @property
    def sanitize(self) -> builtins.bool: ...
    @property
    def allow_cxsmiles(self) -> builtins.bool: ...
    @property
    def strict_cxsmiles(self) -> builtins.bool: ...
    @property
    def parse_name(self) -> builtins.bool: ...
    @property
    def remove_hydrogens(self) -> builtins.bool: ...
    @property
    def skip_cleanup(self) -> builtins.bool: ...
    @property
    def debug_parse(self) -> builtins.bool: ...
    @property
    def replacements(self) -> builtins.dict[builtins.str, builtins.str]: ...
    def __new__(cls, *, sanitize: builtins.bool = True, allow_cxsmiles: builtins.bool = True, strict_cxsmiles: builtins.bool = True, parse_name: builtins.bool = True, remove_hydrogens: builtins.bool = True, skip_cleanup: builtins.bool = False, debug_parse: builtins.bool = False, replacements: typing.Optional[typing.Mapping[builtins.str, builtins.str]] = None) -> SmilesParseParams: ...

@typing.final
class SmilesWriteParams:
    @property
    def do_isomeric_smiles(self) -> builtins.bool: ...
    @property
    def do_kekule(self) -> builtins.bool: ...
    @property
    def canonical(self) -> builtins.bool: ...
    @property
    def clean_stereo(self) -> builtins.bool: ...
    @property
    def all_bonds_explicit(self) -> builtins.bool: ...
    @property
    def all_hydrogens_explicit(self) -> builtins.bool: ...
    @property
    def include_dative_bonds(self) -> builtins.bool: ...
    @property
    def ignore_atom_map_numbers(self) -> builtins.bool: ...
    @property
    def rooted_at_atom(self) -> typing.Optional[builtins.int]: ...
    def __new__(cls, *, do_isomeric_smiles: builtins.bool = True, do_kekule: builtins.bool = False, canonical: builtins.bool = True, clean_stereo: builtins.bool = True, rooted_at_atom: typing.Optional[builtins.int] = None, all_bonds_explicit: builtins.bool = False, all_hydrogens_explicit: builtins.bool = False, include_dative_bonds: builtins.bool = True, ignore_atom_map_numbers: builtins.bool = False) -> SmilesWriteParams: ...

@typing.final
class SparseBitFingerprint:
    def n_bits(self) -> builtins.int: ...
    def on_bits(self) -> builtins.list[builtins.int]: ...
    def __len__(self) -> builtins.int: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class SparseCountFingerprint:
    @staticmethod
    def new(length: builtins.int) -> SparseCountFingerprint: ...
    def length(self) -> builtins.int: ...
    def value(self, index: builtins.int) -> builtins.int: ...
    def set_value(self, index: builtins.int, value: builtins.int) -> None: ...
    def nonzero_elements(self) -> builtins.dict[builtins.int, builtins.int]: ...
    def total_value(self, use_abs: builtins.bool = False) -> builtins.int: ...
    def fuzzy_and(self, other: SparseCountFingerprint) -> SparseCountFingerprint: ...
    def fuzzy_or(self, other: SparseCountFingerprint) -> SparseCountFingerprint: ...
    def with_added(self, other: SparseCountFingerprint) -> SparseCountFingerprint: ...
    def with_subtracted(self, other: SparseCountFingerprint) -> SparseCountFingerprint: ...
    def with_added_scalar(self, value: builtins.int) -> SparseCountFingerprint: ...
    def with_subtracted_scalar(self, value: builtins.int) -> SparseCountFingerprint: ...
    def with_multiplied_scalar(self, value: builtins.int) -> SparseCountFingerprint: ...
    def with_divided_scalar(self, value: builtins.int) -> SparseCountFingerprint: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class SparseCountFingerprint32:
    @staticmethod
    def new(length: builtins.int) -> SparseCountFingerprint32: ...
    def length(self) -> builtins.int: ...
    def value(self, index: builtins.int) -> builtins.int: ...
    def set_value(self, index: builtins.int, value: builtins.int) -> None: ...
    def nonzero_elements(self) -> builtins.dict[builtins.int, builtins.int]: ...
    def total_value(self, use_abs: builtins.bool = False) -> builtins.int: ...
    def fuzzy_and(self, other: SparseCountFingerprint32) -> SparseCountFingerprint32: ...
    def fuzzy_or(self, other: SparseCountFingerprint32) -> SparseCountFingerprint32: ...
    def with_added(self, other: SparseCountFingerprint32) -> SparseCountFingerprint32: ...
    def with_subtracted(self, other: SparseCountFingerprint32) -> SparseCountFingerprint32: ...
    def with_added_scalar(self, value: builtins.int) -> SparseCountFingerprint32: ...
    def with_subtracted_scalar(self, value: builtins.int) -> SparseCountFingerprint32: ...
    def with_multiplied_scalar(self, value: builtins.int) -> SparseCountFingerprint32: ...
    def with_divided_scalar(self, value: builtins.int) -> SparseCountFingerprint32: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class RotatableBondsOptions(enum.Enum):
    r"""
    Immutable source definition selector, projected from the public facade.
    """
    Default = ...
    NonStrict = ...
    Strict = ...
    StrictLinkages = ...

def element_info(element: Element) -> ElementInfo: ...

def version() -> builtins.str: ...


class DrawingError(builtins.ValueError):
    domain: builtins.str
    kind: builtins.str
    # Context attributes exist only for applicable Rust variants.
    width: builtins.int
    height: builtins.int
    field: builtins.str
    actual: builtins.int
    expected: builtins.int
    row: typing.Optional[builtins.int]
    reason: builtins.str

class OperationError(builtins.ValueError):
    domain: builtins.str
    kind: builtins.str

__version__: builtins.str
_binding_profile: builtins.str

class SmilesError(builtins.ValueError):
    domain: builtins.str
    kind: builtins.str

class SmilesWriteError(builtins.ValueError):
    domain: builtins.str
    kind: builtins.str

class MorganReadError(builtins.ValueError):
    domain: builtins.str
    kind: builtins.str

class FingerprintError(builtins.ValueError):
    domain: builtins.str
    kind: builtins.str
    # Context fields exist only on applicable variants.
    index: builtins.int
    size: builtins.int
    left: builtins.int
    right: builtins.int
    factor: builtins.int
    n_bits: builtins.int
    value: builtins.float
    site: builtins.str
    what: builtins.str
    reason: builtins.str

class DescriptorReadError(builtins.ValueError):
    domain: builtins.str
    kind: builtins.str

class DescriptorError(builtins.ValueError):
    domain: builtins.str
    kind: builtins.str
    # Context fields exist only for applicable Rust variants.
    function: builtins.str
    field: builtins.str
    actual: builtins.int
    expected: builtins.int
    minimum: builtins.int
    expected_rows: builtins.int
    actual_rows: typing.Optional[builtins.int]
    include_sulfur_phosphorus: builtins.bool
    contribs_len: builtins.int
    bin_prop_len: builtins.int
    bins_len: builtins.int
    cell: builtins.str
    row: builtins.int
    detail: builtins.str
