//! Canonical cross-language naming registry.

use cosmolkit_macros::binding_contract;

binding_contract! {
    pub static BINDING_CONTRACT = [
        // RUN-state owns exactly this public value entry. Its Arc-backed
        // MoleculeState and derived-cache authority stay private; construction
        // and read callables are registered by RUN-builder and RUN-read.
        {
            semantic_id: "types.Molecule",
            item: type,
            owner: type_,
            rust: crate::Molecule,
            python: "Molecule",
            javascript: "Molecule",
            feature: "runtime",
            exposure: public,
            support: supported,
            parity: not_applicable,
            role: value,
        },
        {
            semantic_id: "types.MoleculeBuilder",
            item: type,
            owner: type_,
            rust: crate::MoleculeBuilder,
            python: "MoleculeBuilder",
            javascript: "MoleculeBuilder",
            feature: "runtime",
            exposure: public,
            support: supported,
            parity: not_applicable,
            role: value,
        },
        {
            semantic_id: "Molecule.new",
            item: callable,
            owner: molecule,
            rust: crate::Molecule::new,
            python: "new",
            javascript: "new",
            feature: "runtime",
            exposure: public,
            support: supported,
            parity: not_applicable,
            kind: static_,
            parameters: [],
            output: crate::Molecule,
            error: none,
            state: value_returning,
            operation: none,
            signature: fn() -> crate::Molecule,
        },
        {
            semantic_id: "Molecule.from_parts",
            item: callable,
            owner: molecule,
            rust: crate::Molecule::from_parts,
            python: "from_parts",
            javascript: "fromParts",
            feature: "runtime",
            exposure: public,
            support: supported,
            parity: not_applicable,
            kind: static_,
            parameters: [
                { name: topology, type: crate::TopologyBlock, default: required },
                { name: coordinates, type: crate::CoordinateBlock, default: required },
                { name: properties, type: crate::MoleculeProperties, default: required },
            ],
            output: crate::Molecule,
            error: crate::OperationError,
            state: value_returning,
            operation: none,
            signature: fn(crate::TopologyBlock, crate::CoordinateBlock, crate::MoleculeProperties)
                -> Result<crate::Molecule, crate::OperationError>,
        },
        {
            semantic_id: "Molecule.to_builder",
            item: callable,
            owner: molecule,
            rust: crate::Molecule::to_builder,
            python: "to_builder",
            javascript: "toBuilder",
            feature: "runtime",
            exposure: public,
            support: supported,
            parity: not_applicable,
            kind: instance,
            parameters: [],
            output: crate::MoleculeBuilder,
            error: none,
            state: read_only,
            operation: none,
            signature: fn(&crate::Molecule) -> crate::MoleculeBuilder,
        },
        {
            semantic_id: "Molecule.num_atoms",
            item: callable,
            owner: molecule,
            rust: crate::Molecule::num_atoms,
            python: "num_atoms",
            javascript: "numAtoms",
            feature: "runtime",
            exposure: public,
            support: supported,
            parity: not_applicable,
            kind: instance,
            parameters: [],
            output: usize,
            error: none,
            state: read_only,
            operation: none,
            signature: fn(&crate::Molecule) -> usize,
        },
        {
            semantic_id: "Molecule.num_bonds",
            item: callable,
            owner: molecule,
            rust: crate::Molecule::num_bonds,
            python: "num_bonds",
            javascript: "numBonds",
            feature: "runtime",
            exposure: public,
            support: supported,
            parity: not_applicable,
            kind: instance,
            parameters: [],
            output: usize,
            error: none,
            state: read_only,
            operation: none,
            signature: fn(&crate::Molecule) -> usize,
        },
        {
            semantic_id: "Molecule.atoms",
            item: callable,
            owner: molecule,
            rust: crate::Molecule::atoms,
            python: "atoms",
            javascript: "atoms",
            feature: "runtime",
            exposure: public,
            support: supported,
            parity: not_applicable,
            kind: instance,
            parameters: [],
            output: &[crate::Atom],
            error: none,
            state: read_only,
            operation: none,
            signature: fn(&crate::Molecule) -> &[crate::Atom],
        },
        {
            semantic_id: "Molecule.bonds",
            item: callable,
            owner: molecule,
            rust: crate::Molecule::bonds,
            python: "bonds",
            javascript: "bonds",
            feature: "runtime",
            exposure: public,
            support: supported,
            parity: not_applicable,
            kind: instance,
            parameters: [],
            output: &[crate::Bond],
            error: none,
            state: read_only,
            operation: none,
            signature: fn(&crate::Molecule) -> &[crate::Bond],
        },
        {
            semantic_id: "Molecule.atom",
            item: callable,
            owner: molecule,
            rust: crate::Molecule::atom,
            python: "atom",
            javascript: "atom",
            feature: "runtime",
            exposure: public,
            support: supported,
            parity: not_applicable,
            kind: instance,
            parameters: [{ name: atom_id, type: crate::AtomId, default: required }],
            output: Option<&crate::Atom>,
            error: none,
            state: read_only,
            operation: none,
            signature: fn(&crate::Molecule, crate::AtomId) -> Option<&crate::Atom>,
        },
        {
            semantic_id: "Molecule.bond",
            item: callable,
            owner: molecule,
            rust: crate::Molecule::bond,
            python: "bond",
            javascript: "bond",
            feature: "runtime",
            exposure: public,
            support: supported,
            parity: not_applicable,
            kind: instance,
            parameters: [{ name: bond_id, type: crate::BondId, default: required }],
            output: Option<&crate::Bond>,
            error: none,
            state: read_only,
            operation: none,
            signature: fn(&crate::Molecule, crate::BondId) -> Option<&crate::Bond>,
        },
        {
            semantic_id: "Molecule.topology",
            item: callable,
            owner: molecule,
            rust: crate::Molecule::topology,
            python: "topology",
            javascript: "topology",
            feature: "runtime",
            exposure: public,
            support: supported,
            parity: not_applicable,
            kind: instance,
            parameters: [],
            output: &crate::TopologyBlock,
            error: none,
            state: read_only,
            operation: none,
            signature: fn(&crate::Molecule) -> &crate::TopologyBlock,
        },
        {
            semantic_id: "Molecule.coordinates",
            item: callable,
            owner: molecule,
            rust: crate::Molecule::coordinates,
            python: "coordinates",
            javascript: "coordinates",
            feature: "runtime",
            exposure: public,
            support: supported,
            parity: not_applicable,
            kind: instance,
            parameters: [],
            output: &crate::CoordinateBlock,
            error: none,
            state: read_only,
            operation: none,
            signature: fn(&crate::Molecule) -> &crate::CoordinateBlock,
        },
        {
            semantic_id: "Molecule.conformers",
            item: callable,
            owner: molecule,
            rust: crate::Molecule::conformers,
            python: "conformers",
            javascript: "conformers",
            feature: "runtime",
            exposure: public,
            support: supported,
            parity: not_applicable,
            kind: instance,
            parameters: [],
            output: (&[crate::Conformer2D], &[crate::Conformer3D]),
            error: none,
            state: read_only,
            operation: none,
            signature: fn(&crate::Molecule) -> (&[crate::Conformer2D], &[crate::Conformer3D]),
        },
        {
            semantic_id: "Molecule.properties",
            item: callable,
            owner: molecule,
            rust: crate::Molecule::properties,
            python: "properties",
            javascript: "properties",
            feature: "runtime",
            exposure: public,
            support: supported,
            parity: not_applicable,
            kind: instance,
            parameters: [],
            output: &crate::MoleculeProperties,
            error: none,
            state: read_only,
            operation: none,
            signature: fn(&crate::Molecule) -> &crate::MoleculeProperties,
        },
        {
            semantic_id: "Molecule.property",
            item: callable,
            owner: molecule,
            rust: crate::Molecule::property,
            python: "property",
            javascript: "property",
            feature: "runtime",
            exposure: public,
            support: supported,
            parity: not_applicable,
            kind: instance,
            parameters: [{ name: key, type: &str, default: required }],
            output: Option<&str>,
            error: none,
            state: read_only,
            operation: none,
            signature: for<'a, 'b> fn(&'a crate::Molecule, &'b str) -> Option<&'a str>,
        },
        {
            semantic_id: "MoleculeBuilder.new",
            item: callable,
            owner: type_,
            rust: crate::MoleculeBuilder::new,
            python: "new",
            javascript: "new",
            feature: "runtime",
            exposure: public,
            support: supported,
            parity: not_applicable,
            kind: static_,
            parameters: [],
            output: crate::MoleculeBuilder,
            error: none,
            state: value_returning,
            operation: none,
            signature: fn() -> crate::MoleculeBuilder,
        },
        {
            semantic_id: "MoleculeBuilder.from_parts",
            item: callable,
            owner: type_,
            rust: crate::MoleculeBuilder::from_parts,
            python: "from_parts",
            javascript: "fromParts",
            feature: "runtime",
            exposure: public,
            support: supported,
            parity: not_applicable,
            kind: static_,
            parameters: [
                { name: topology, type: crate::TopologyBlock, default: required },
                { name: coordinates, type: crate::CoordinateBlock, default: required },
                { name: properties, type: crate::MoleculeProperties, default: required },
            ],
            output: crate::MoleculeBuilder,
            error: none,
            state: value_returning,
            operation: none,
            signature: fn(crate::TopologyBlock, crate::CoordinateBlock, crate::MoleculeProperties)
                -> crate::MoleculeBuilder,
        },
        {
            semantic_id: "MoleculeBuilder.build",
            item: callable,
            owner: type_,
            rust: crate::MoleculeBuilder::build,
            python: "build",
            javascript: "build",
            feature: "runtime",
            exposure: public,
            support: supported,
            parity: not_applicable,
            kind: instance,
            parameters: [],
            output: crate::Molecule,
            error: crate::OperationError,
            state: value_returning,
            operation: none,
            signature: fn(crate::MoleculeBuilder) -> Result<crate::Molecule, crate::OperationError>,
        },
        {
            semantic_id: "MoleculeBuilder.add_atom",
            item: callable,
            owner: type_,
            rust: crate::MoleculeBuilder::add_atom,
            python: "add_atom",
            javascript: "addAtom",
            feature: "runtime",
            exposure: public,
            support: supported,
            parity: not_applicable,
            kind: instance,
            parameters: [{ name: atom, type: crate::AtomSpec, default: required }],
            output: crate::AtomId,
            error: none,
            state: in_place,
            operation: none,
            signature: fn(&mut crate::MoleculeBuilder, crate::AtomSpec) -> crate::AtomId,
        },
        {
            semantic_id: "MoleculeBuilder.add_bond",
            item: callable,
            owner: type_,
            rust: crate::MoleculeBuilder::add_bond,
            python: "add_bond",
            javascript: "addBond",
            feature: "runtime",
            exposure: public,
            support: supported,
            parity: not_applicable,
            kind: instance,
            parameters: [{ name: bond, type: crate::BondSpec, default: required }],
            output: crate::BondId,
            error: crate::OperationError,
            state: in_place,
            operation: none,
            signature: fn(&mut crate::MoleculeBuilder, crate::BondSpec)
                -> Result<crate::BondId, crate::OperationError>,
        },
        {
            semantic_id: "MoleculeBuilder.set_atom_formal_charge",
            item: callable,
            owner: type_,
            rust: crate::MoleculeBuilder::set_atom_formal_charge,
            python: "set_atom_formal_charge",
            javascript: "setAtomFormalCharge",
            feature: "runtime",
            exposure: public,
            support: supported,
            parity: not_applicable,
            kind: instance,
            parameters: [
                { name: atom_id, type: crate::AtomId, default: required },
                { name: formal_charge, type: i8, default: required },
            ],
            output: (),
            error: crate::OperationError,
            state: in_place,
            operation: none,
            signature: fn(&mut crate::MoleculeBuilder, crate::AtomId, i8)
                -> Result<(), crate::OperationError>,
        },
        {
            semantic_id: "MoleculeBuilder.set_bond_order",
            item: callable,
            owner: type_,
            rust: crate::MoleculeBuilder::set_bond_order,
            python: "set_bond_order",
            javascript: "setBondOrder",
            feature: "runtime",
            exposure: public,
            support: supported,
            parity: not_applicable,
            kind: instance,
            parameters: [
                { name: bond_id, type: crate::BondId, default: required },
                { name: order, type: crate::BondOrder, default: required },
            ],
            output: (),
            error: crate::OperationError,
            state: in_place,
            operation: none,
            signature: fn(&mut crate::MoleculeBuilder, crate::BondId, crate::BondOrder)
                -> Result<(), crate::OperationError>,
        },
        {
            semantic_id: "MoleculeBuilder.remove_bond_between_atoms",
            item: callable,
            owner: type_,
            rust: crate::MoleculeBuilder::remove_bond_between_atoms,
            python: "remove_bond_between_atoms",
            javascript: "removeBondBetweenAtoms",
            feature: "runtime",
            exposure: public,
            support: supported,
            parity: not_applicable,
            kind: instance,
            parameters: [
                { name: begin_atom, type: crate::AtomId, default: required },
                { name: end_atom, type: crate::AtomId, default: required },
            ],
            output: bool,
            error: crate::OperationError,
            state: in_place,
            operation: none,
            signature: fn(&mut crate::MoleculeBuilder, crate::AtomId, crate::AtomId)
                -> Result<bool, crate::OperationError>,
        },
        {
            semantic_id: "MoleculeBuilder.degree",
            item: callable,
            owner: type_,
            rust: crate::MoleculeBuilder::degree,
            python: "degree",
            javascript: "degree",
            feature: "runtime",
            exposure: public,
            support: supported,
            parity: not_applicable,
            kind: instance,
            parameters: [{ name: atom_id, type: crate::AtomId, default: required }],
            output: usize,
            error: crate::OperationError,
            state: read_only,
            operation: none,
            signature: fn(&crate::MoleculeBuilder, crate::AtomId)
                -> Result<usize, crate::OperationError>,
        },
        {
            semantic_id: "MoleculeBuilder.neighbor_bonds",
            item: callable,
            owner: type_,
            rust: crate::MoleculeBuilder::neighbor_bonds,
            python: "neighbor_bonds",
            javascript: "neighborBonds",
            feature: "runtime",
            exposure: public,
            support: supported,
            parity: not_applicable,
            kind: instance,
            parameters: [{ name: atom_id, type: crate::AtomId, default: required }],
            output: Vec<crate::BondId>,
            error: crate::OperationError,
            state: read_only,
            operation: none,
            signature: fn(&crate::MoleculeBuilder, crate::AtomId)
                -> Result<Vec<crate::BondId>, crate::OperationError>,
        },
        {
            semantic_id: "MoleculeBuilder.bond_between_atoms",
            item: callable,
            owner: type_,
            rust: crate::MoleculeBuilder::bond_between_atoms,
            python: "bond_between_atoms",
            javascript: "bondBetweenAtoms",
            feature: "runtime",
            exposure: public,
            support: supported,
            parity: not_applicable,
            kind: instance,
            parameters: [
                { name: begin_atom, type: crate::AtomId, default: required },
                { name: end_atom, type: crate::AtomId, default: required },
            ],
            output: Option<crate::BondId>,
            error: crate::OperationError,
            state: read_only,
            operation: none,
            signature: fn(&crate::MoleculeBuilder, crate::AtomId, crate::AtomId)
                -> Result<Option<crate::BondId>, crate::OperationError>,
        },
        {
            semantic_id: "MoleculeBuilder.atoms",
            item: callable,
            owner: type_,
            rust: crate::MoleculeBuilder::atoms,
            python: "atoms",
            javascript: "atoms",
            feature: "runtime",
            exposure: public,
            support: supported,
            parity: not_applicable,
            kind: instance,
            parameters: [],
            output: &[crate::Atom],
            error: none,
            state: read_only,
            operation: none,
            signature: fn(&crate::MoleculeBuilder) -> &[crate::Atom],
        },
        {
            semantic_id: "MoleculeBuilder.bonds",
            item: callable,
            owner: type_,
            rust: crate::MoleculeBuilder::bonds,
            python: "bonds",
            javascript: "bonds",
            feature: "runtime",
            exposure: public,
            support: supported,
            parity: not_applicable,
            kind: instance,
            parameters: [],
            output: &[crate::Bond],
            error: none,
            state: read_only,
            operation: none,
            signature: fn(&crate::MoleculeBuilder) -> &[crate::Bond],
        },
        {
            semantic_id: "MoleculeBuilder.substance_groups",
            item: callable,
            owner: type_,
            rust: crate::MoleculeBuilder::substance_groups,
            python: "substance_groups",
            javascript: "substanceGroups",
            feature: "runtime",
            exposure: public,
            support: supported,
            parity: not_applicable,
            kind: instance,
            parameters: [],
            output: &[crate::SubstanceGroup],
            error: none,
            state: read_only,
            operation: none,
            signature: fn(&crate::MoleculeBuilder) -> &[crate::SubstanceGroup],
        },
        {
            semantic_id: "MoleculeBuilder.stereo_groups",
            item: callable,
            owner: type_,
            rust: crate::MoleculeBuilder::stereo_groups,
            python: "stereo_groups",
            javascript: "stereoGroups",
            feature: "runtime",
            exposure: public,
            support: supported,
            parity: not_applicable,
            kind: instance,
            parameters: [],
            output: &[crate::StereoGroup],
            error: none,
            state: read_only,
            operation: none,
            signature: fn(&crate::MoleculeBuilder) -> &[crate::StereoGroup],
        },
        {
            semantic_id: "MoleculeBuilder.coordinates",
            item: callable,
            owner: type_,
            rust: crate::MoleculeBuilder::coordinates,
            python: "coordinates",
            javascript: "coordinates",
            feature: "runtime",
            exposure: public,
            support: supported,
            parity: not_applicable,
            kind: instance,
            parameters: [],
            output: &crate::CoordinateBlock,
            error: none,
            state: read_only,
            operation: none,
            signature: fn(&crate::MoleculeBuilder) -> &crate::CoordinateBlock,
        },
        {
            semantic_id: "MoleculeBuilder.properties",
            item: callable,
            owner: type_,
            rust: crate::MoleculeBuilder::properties,
            python: "properties",
            javascript: "properties",
            feature: "runtime",
            exposure: public,
            support: supported,
            parity: not_applicable,
            kind: instance,
            parameters: [],
            output: &crate::MoleculeProperties,
            error: none,
            state: read_only,
            operation: none,
            signature: fn(&crate::MoleculeBuilder) -> &crate::MoleculeProperties,
        },
        {
            semantic_id: "MoleculeBuilder.set_2d_coordinates",
            item: callable,
            owner: type_,
            rust: crate::MoleculeBuilder::set_2d_coordinates,
            python: "set_2d_coordinates",
            javascript: "set2dCoordinates",
            feature: "runtime",
            exposure: public,
            support: supported,
            parity: not_applicable,
            kind: instance,
            parameters: [{ name: coordinates, type: Vec<[f64; 2]>, default: required }],
            output: (),
            error: crate::OperationError,
            state: in_place,
            operation: none,
            signature: fn(&mut crate::MoleculeBuilder, Vec<[f64; 2]>)
                -> Result<(), crate::OperationError>,
        },
        {
            semantic_id: "MoleculeBuilder.add_2d_conformer",
            item: callable,
            owner: type_,
            rust: crate::MoleculeBuilder::add_2d_conformer,
            python: "add_2d_conformer",
            javascript: "add2dConformer",
            feature: "runtime",
            exposure: public,
            support: supported,
            parity: not_applicable,
            kind: instance,
            parameters: [{ name: coordinates, type: Vec<[f64; 2]>, default: required }],
            output: usize,
            error: crate::OperationError,
            state: in_place,
            operation: none,
            signature: fn(&mut crate::MoleculeBuilder, Vec<[f64; 2]>)
                -> Result<usize, crate::OperationError>,
        },
        {
            semantic_id: "MoleculeBuilder.add_3d_conformer",
            item: callable,
            owner: type_,
            rust: crate::MoleculeBuilder::add_3d_conformer,
            python: "add_3d_conformer",
            javascript: "add3dConformer",
            feature: "runtime",
            exposure: public,
            support: supported,
            parity: not_applicable,
            kind: instance,
            parameters: [{ name: coordinates, type: Vec<[f64; 3]>, default: required }],
            output: usize,
            error: crate::OperationError,
            state: in_place,
            operation: none,
            signature: fn(&mut crate::MoleculeBuilder, Vec<[f64; 3]>)
                -> Result<usize, crate::OperationError>,
        },
        {
            semantic_id: "MoleculeBuilder.add_substance_group",
            item: callable,
            owner: type_,
            rust: crate::MoleculeBuilder::add_substance_group,
            python: "add_substance_group",
            javascript: "addSubstanceGroup",
            feature: "runtime",
            exposure: public,
            support: supported,
            parity: not_applicable,
            kind: instance,
            parameters: [{ name: group, type: crate::SubstanceGroup, default: required }],
            output: crate::SubstanceGroupId,
            error: crate::OperationError,
            state: in_place,
            operation: none,
            signature: fn(&mut crate::MoleculeBuilder, crate::SubstanceGroup)
                -> Result<crate::SubstanceGroupId, crate::OperationError>,
        },
        {
            semantic_id: "MoleculeBuilder.add_stereo_group",
            item: callable,
            owner: type_,
            rust: crate::MoleculeBuilder::add_stereo_group,
            python: "add_stereo_group",
            javascript: "addStereoGroup",
            feature: "runtime",
            exposure: public,
            support: supported,
            parity: not_applicable,
            kind: instance,
            parameters: [{ name: group, type: crate::StereoGroup, default: required }],
            output: usize,
            error: crate::OperationError,
            state: in_place,
            operation: none,
            signature: fn(&mut crate::MoleculeBuilder, crate::StereoGroup)
                -> Result<usize, crate::OperationError>,
        },
        {
            semantic_id: "MoleculeBuilder.with_name",
            item: callable,
            owner: type_,
            rust: crate::MoleculeBuilder::with_name,
            python: "with_name",
            javascript: "withName",
            feature: "runtime",
            exposure: public,
            support: supported,
            parity: not_applicable,
            kind: instance,
            parameters: [{ name: name, type: String, default: required }],
            output: crate::MoleculeBuilder,
            error: none,
            state: value_returning,
            operation: none,
            signature: fn(crate::MoleculeBuilder, String) -> crate::MoleculeBuilder,
        },
        {
            semantic_id: "MoleculeBuilder.with_property",
            item: callable,
            owner: type_,
            rust: crate::MoleculeBuilder::with_property,
            python: "with_property",
            javascript: "withProperty",
            feature: "runtime",
            exposure: public,
            support: supported,
            parity: not_applicable,
            kind: instance,
            parameters: [
                { name: key, type: String, default: required },
                { name: value, type: String, default: required },
            ],
            output: crate::MoleculeBuilder,
            error: crate::OperationError,
            state: value_returning,
            operation: none,
            signature: fn(crate::MoleculeBuilder, String, String)
                -> Result<crate::MoleculeBuilder, crate::OperationError>,
        },
        {
            semantic_id: "MoleculeBuilder.with_sdf_data_field",
            item: callable,
            owner: type_,
            rust: crate::MoleculeBuilder::with_sdf_data_field,
            python: "with_sdf_data_field",
            javascript: "withSdfDataField",
            feature: "runtime",
            exposure: public,
            support: supported,
            parity: not_applicable,
            kind: instance,
            parameters: [
                { name: key, type: String, default: required },
                { name: value, type: String, default: required },
            ],
            output: crate::MoleculeBuilder,
            error: none,
            state: value_returning,
            operation: none,
            signature: fn(crate::MoleculeBuilder, String, String) -> crate::MoleculeBuilder,
        },
        {
            semantic_id: "MoleculeBuilder.with_properties",
            item: callable,
            owner: type_,
            rust: crate::MoleculeBuilder::with_properties,
            python: "with_properties",
            javascript: "withProperties",
            feature: "runtime",
            exposure: public,
            support: supported,
            parity: not_applicable,
            kind: instance,
            parameters: [{ name: properties, type: crate::MoleculeProperties, default: required }],
            output: crate::MoleculeBuilder,
            error: none,
            state: value_returning,
            operation: none,
            signature: fn(crate::MoleculeBuilder, crate::MoleculeProperties)
                -> crate::MoleculeBuilder,
        },
        {
            semantic_id: "types.OperationError",
            item: type,
            owner: type_,
            rust: crate::OperationError,
            python: "OperationError",
            javascript: "OperationError",
            feature: "runtime",
            exposure: public,
            support: supported,
            parity: not_applicable,
            role: error,
        },
        {
            semantic_id: "types.SupportStatus",
            item: type,
            owner: type_,
            rust: crate::SupportStatus,
            python: "SupportStatus",
            javascript: "SupportStatus",
            feature: "metadata",
            exposure: public,
            support: supported,
            parity: not_applicable,
            role: value,
        },
        {
            semantic_id: "types.ParityPolicy",
            item: type,
            owner: type_,
            rust: crate::ParityPolicy,
            python: "ParityPolicy",
            javascript: "ParityPolicy",
            feature: "metadata",
            exposure: public,
            support: supported,
            parity: not_applicable,
            role: value,
        },
        {
            semantic_id: "types.FeatureSpec",
            item: type,
            owner: type_,
            rust: crate::FeatureSpec,
            python: "FeatureSpec",
            javascript: "FeatureSpec",
            feature: "metadata",
            exposure: public,
            support: supported,
            parity: not_applicable,
            role: value,
        },
        {
            semantic_id: "types.MoleculeOpSpec",
            item: type,
            owner: type_,
            rust: crate::MoleculeOpSpec,
            python: "MoleculeOpSpec",
            javascript: "MoleculeOpSpec",
            feature: "metadata",
            exposure: public,
            support: supported,
            parity: not_applicable,
            role: result,
        },
        {
            semantic_id: "types.SupportMatrixEntry",
            item: type,
            owner: type_,
            rust: crate::SupportMatrixEntry,
            python: "SupportMatrixEntry",
            javascript: "SupportMatrixEntry",
            feature: "metadata",
            exposure: public,
            support: supported,
            parity: not_applicable,
            role: result,
        },
        {
            semantic_id: "types.OperationInvariantEntry",
            item: type,
            owner: type_,
            rust: crate::OperationInvariantEntry,
            python: "OperationInvariantEntry",
            javascript: "OperationInvariantEntry",
            feature: "metadata",
            exposure: public,
            support: supported,
            parity: not_applicable,
            role: result,
        },
        {
            semantic_id: "types.ParityMatrixEntry",
            item: type,
            owner: type_,
            rust: crate::ParityMatrixEntry,
            python: "ParityMatrixEntry",
            javascript: "ParityMatrixEntry",
            feature: "metadata",
            exposure: public,
            support: supported,
            parity: not_applicable,
            role: result,
        },
        {
            semantic_id: "types.FeatureSpecIter",
            item: type,
            owner: type_,
            rust: crate::FeatureSpecIter,
            python: "FeatureSpecIter",
            javascript: "FeatureSpecIter",
            feature: "metadata",
            exposure: registered,
            support: supported,
            parity: not_applicable,
            role: result,
        },
        {
            semantic_id: "module.feature_specs",
            item: callable,
            owner: module,
            rust: crate::feature_specs,
            python: "feature_specs",
            javascript: "featureSpecs",
            feature: "metadata",
            exposure: registered,
            support: supported,
            parity: not_applicable,
            kind: module,
            parameters: [],
            output: crate::FeatureSpecIter,
            error: none,
            state: read_only,
            operation: none,
            signature: fn() -> crate::FeatureSpecIter,
        },
        {
            semantic_id: "module.feature_spec",
            item: callable,
            owner: module,
            rust: crate::feature_spec,
            python: "feature_spec",
            javascript: "featureSpec",
            feature: "metadata",
            exposure: registered,
            support: supported,
            parity: not_applicable,
            kind: module,
            parameters: [{ name: name, type: &str, default: required }],
            output: Option<&'static crate::FeatureSpec>,
            error: none,
            state: read_only,
            operation: none,
            signature: fn(&str) -> Option<&'static crate::FeatureSpec>,
        },
        {
            semantic_id: "module.operation_specs",
            item: callable,
            owner: module,
            rust: crate::operation_specs,
            python: "operation_specs",
            javascript: "operationSpecs",
            feature: "metadata",
            exposure: registered,
            support: supported,
            parity: not_applicable,
            kind: module,
            parameters: [],
            output: &'static [&'static crate::MoleculeOpSpec],
            error: none,
            state: read_only,
            operation: none,
            signature: fn() -> &'static [&'static crate::MoleculeOpSpec],
        },
        {
            semantic_id: "module.operation_spec",
            item: callable,
            owner: module,
            rust: crate::operation_spec,
            python: "operation_spec",
            javascript: "operationSpec",
            feature: "metadata",
            exposure: registered,
            support: supported,
            parity: not_applicable,
            kind: module,
            parameters: [{ name: method, type: &str, default: required }],
            output: Option<&'static crate::MoleculeOpSpec>,
            error: none,
            state: read_only,
            operation: none,
            signature: fn(&str) -> Option<&'static crate::MoleculeOpSpec>,
        },
        {
            semantic_id: "module.support_matrix",
            item: callable,
            owner: module,
            rust: crate::support_matrix,
            python: "support_matrix",
            javascript: "supportMatrix",
            feature: "metadata",
            exposure: registered,
            support: supported,
            parity: not_applicable,
            kind: module,
            parameters: [],
            output: &'static [crate::SupportMatrixEntry],
            error: none,
            state: read_only,
            operation: none,
            signature: fn() -> &'static [crate::SupportMatrixEntry],
        },
        {
            semantic_id: "module.operation_invariant_matrix",
            item: callable,
            owner: module,
            rust: crate::operation_invariant_matrix,
            python: "operation_invariant_matrix",
            javascript: "operationInvariantMatrix",
            feature: "metadata",
            exposure: registered,
            support: supported,
            parity: not_applicable,
            kind: module,
            parameters: [],
            output: &'static [crate::OperationInvariantEntry],
            error: none,
            state: read_only,
            operation: none,
            signature: fn() -> &'static [crate::OperationInvariantEntry],
        },
        {
            semantic_id: "module.parity_matrix",
            item: callable,
            owner: module,
            rust: crate::parity_matrix,
            python: "parity_matrix",
            javascript: "parityMatrix",
            feature: "metadata",
            exposure: registered,
            support: supported,
            parity: not_applicable,
            kind: module,
            parameters: [],
            output: &'static [crate::ParityMatrixEntry],
            error: none,
            state: read_only,
            operation: none,
            signature: fn() -> &'static [crate::ParityMatrixEntry],
        },
        {
            semantic_id: "module.operation_invariant",
            item: callable,
            owner: module,
            rust: crate::operation_invariant,
            python: "operation_invariant",
            javascript: "operationInvariant",
            feature: "metadata",
            exposure: registered,
            support: supported,
            parity: not_applicable,
            kind: module,
            parameters: [{ name: method, type: &str, default: required }],
            output: Option<&'static crate::OperationInvariantEntry>,
            error: none,
            state: read_only,
            operation: none,
            signature: fn(&str) -> Option<&'static crate::OperationInvariantEntry>,
        },
        {
            semantic_id: "module.operation_parity",
            item: callable,
            owner: module,
            rust: crate::operation_parity,
            python: "operation_parity",
            javascript: "operationParity",
            feature: "metadata",
            exposure: registered,
            support: supported,
            parity: not_applicable,
            kind: module,
            parameters: [{ name: method, type: &str, default: required }],
            output: Option<&'static crate::ParityMatrixEntry>,
            error: none,
            state: read_only,
            operation: none,
            signature: fn(&str) -> Option<&'static crate::ParityMatrixEntry>,
        },
        {
            semantic_id: "module.version",
            item: callable,
            owner: module,
            rust: crate::version,
            python: "version",
            javascript: "version",
            feature: "metadata",
            exposure: public,
            support: supported,
            parity: not_applicable,
            kind: module,
            parameters: [],
            output: &'static str,
            error: none,
            state: read_only,
            operation: none,
            signature: fn() -> &'static str,
        },
        #[cfg(feature = "matrices")]
        {
            semantic_id: "types.DenseMatrix",
            item: type,
            owner: type_,
            rust: crate::DenseMatrix,
            python: "DenseMatrix",
            javascript: "DenseMatrix",
            feature: "matrices",
            exposure: registered,
            support: unsupported,
            parity: required_when_supported,
            role: result,
        },
        #[cfg(feature = "matrices")]
        {
            semantic_id: "types.DistanceMatrixParams",
            item: type,
            owner: type_,
            rust: crate::DistanceMatrixParams,
            python: "DistanceMatrixParams",
            javascript: "DistanceMatrixParams",
            feature: "matrices",
            exposure: registered,
            support: unsupported,
            parity: required_when_supported,
            role: parameter,
        },
        #[cfg(feature = "matrices")]
        {
            semantic_id: "types.DistanceMatrix3dParams",
            item: type,
            owner: type_,
            rust: crate::DistanceMatrix3dParams,
            python: "DistanceMatrix3dParams",
            javascript: "DistanceMatrix3dParams",
            feature: "matrices",
            exposure: registered,
            support: unsupported,
            parity: required_when_supported,
            role: parameter,
        },
        #[cfg(feature = "matrices")]
        {
            semantic_id: "types.MatrixError",
            item: type,
            owner: type_,
            rust: crate::MatrixError,
            python: "MatrixError",
            javascript: "MatrixError",
            feature: "matrices",
            exposure: registered,
            support: unsupported,
            parity: required_when_supported,
            role: error,
        },
        #[cfg(feature = "matrices")]
        {
            semantic_id: "Molecule.distance_matrix",
            item: callable,
            owner: molecule,
            rust: crate::Molecule::distance_matrix,
            python: "distance_matrix",
            javascript: "distanceMatrix",
            feature: "matrices",
            exposure: registered,
            support: unsupported,
            parity: required_when_supported,
            kind: instance,
            parameters: [],
            output: crate::DenseMatrix,
            error: crate::MatrixError,
            state: read_only,
            operation: none,
            signature: fn(&crate::Molecule) -> Result<crate::DenseMatrix, crate::MatrixError>,
        },
        #[cfg(feature = "matrices")]
        {
            semantic_id: "Molecule.distance_matrix_with_params",
            item: callable,
            owner: molecule,
            rust: crate::Molecule::distance_matrix_with_params,
            python: "distance_matrix_with_params",
            javascript: "distanceMatrixWithParams",
            feature: "matrices",
            exposure: registered,
            support: unsupported,
            parity: required_when_supported,
            kind: instance,
            parameters: [
                { name: params, type: &crate::DistanceMatrixParams, default: required },
            ],
            output: crate::DenseMatrix,
            error: crate::MatrixError,
            state: read_only,
            operation: none,
            signature: for<'a, 'b> fn(
                &'a crate::Molecule,
                &'b crate::DistanceMatrixParams,
            ) -> Result<crate::DenseMatrix, crate::MatrixError>,
        },
        #[cfg(feature = "matrices")]
        {
            semantic_id: "Molecule.distance_matrix_3d",
            item: callable,
            owner: molecule,
            rust: crate::Molecule::distance_matrix_3d,
            python: "distance_matrix_3d",
            javascript: "distanceMatrix3d",
            feature: "matrices",
            exposure: registered,
            support: unsupported,
            parity: required_when_supported,
            kind: instance,
            parameters: [],
            output: crate::DenseMatrix,
            error: crate::MatrixError,
            state: read_only,
            operation: none,
            signature: fn(&crate::Molecule) -> Result<crate::DenseMatrix, crate::MatrixError>,
        },
        #[cfg(feature = "matrices")]
        {
            semantic_id: "Molecule.distance_matrix_3d_with_params",
            item: callable,
            owner: molecule,
            rust: crate::Molecule::distance_matrix_3d_with_params,
            python: "distance_matrix_3d_with_params",
            javascript: "distanceMatrix3dWithParams",
            feature: "matrices",
            exposure: registered,
            support: unsupported,
            parity: required_when_supported,
            kind: instance,
            parameters: [
                { name: params, type: &crate::DistanceMatrix3dParams, default: required },
            ],
            output: crate::DenseMatrix,
            error: crate::MatrixError,
            state: read_only,
            operation: none,
            signature: for<'a, 'b> fn(
                &'a crate::Molecule,
                &'b crate::DistanceMatrix3dParams,
            ) -> Result<crate::DenseMatrix, crate::MatrixError>,
        },
        // CORE-transforms is staged here before the live wrapper is enabled.
        // The detached implementation remains uniquely owned by
        // `cosmolkit-core`; these entries freeze only the canonical facade and
        // cross-language names for the later runtime integration slice.
        #[cfg(feature = "transforms")]
        {
            semantic_id: "types.AtomPositionParams",
            item: type,
            owner: type_,
            rust: crate::AtomPositionParams,
            python: "AtomPositionParams",
            javascript: "AtomPositionParams",
            feature: "transforms",
            exposure: registered,
            support: unsupported,
            parity: required_when_supported,
            role: parameter,
        },
        #[cfg(feature = "transforms")]
        {
            semantic_id: "types.TransformError",
            item: type,
            owner: type_,
            rust: crate::TransformError,
            python: "TransformError",
            javascript: "TransformError",
            feature: "transforms",
            exposure: registered,
            support: unsupported,
            parity: required_when_supported,
            role: error,
        },
        #[cfg(feature = "transforms")]
        {
            semantic_id: "Molecule.with_atom_position",
            item: callable,
            owner: molecule,
            rust: crate::Molecule::with_atom_position,
            python: "with_atom_position",
            javascript: "withAtomPosition",
            feature: "transforms",
            exposure: registered,
            support: unsupported,
            parity: required_when_supported,
            kind: instance,
            parameters: [
                { name: atom, type: crate::AtomId, default: required },
                { name: position, type: [f64; 3], default: required },
            ],
            output: crate::Molecule,
            error: crate::OperationError,
            state: value_returning,
            operation: "with_atom_position",
            signature: fn(
                &crate::Molecule,
                crate::AtomId,
                [f64; 3],
            ) -> Result<crate::Molecule, crate::OperationError>,
        },
        #[cfg(feature = "transforms")]
        {
            semantic_id: "Molecule.with_atom_position_with_params",
            item: callable,
            owner: molecule,
            rust: crate::Molecule::with_atom_position_with_params,
            python: "with_atom_position_with_params",
            javascript: "withAtomPositionWithParams",
            feature: "transforms",
            exposure: registered,
            support: unsupported,
            parity: required_when_supported,
            kind: instance,
            parameters: [
                { name: atom, type: crate::AtomId, default: required },
                { name: position, type: [f64; 3], default: required },
                { name: params, type: &crate::AtomPositionParams, default: required },
            ],
            output: crate::Molecule,
            error: crate::OperationError,
            state: value_returning,
            operation: "with_atom_position_with_params",
            signature: for<'a, 'b> fn(
                &'a crate::Molecule,
                crate::AtomId,
                [f64; 3],
                &'b crate::AtomPositionParams,
            ) -> Result<crate::Molecule, crate::OperationError>,
        },
        #[cfg(feature = "transforms")]
        {
            semantic_id: "Molecule.set_atom_position_",
            item: callable,
            owner: molecule,
            rust: crate::Molecule::set_atom_position_,
            python: "set_atom_position_",
            javascript: "setAtomPosition",
            feature: "transforms",
            exposure: registered,
            support: unsupported,
            parity: required_when_supported,
            kind: instance,
            parameters: [
                { name: atom, type: crate::AtomId, default: required },
                { name: position, type: [f64; 3], default: required },
            ],
            output: (),
            error: crate::OperationError,
            state: in_place,
            operation: "set_atom_position_",
            signature: fn(
                &mut crate::Molecule,
                crate::AtomId,
                [f64; 3],
            ) -> Result<(), crate::OperationError>,
        },
        #[cfg(feature = "transforms")]
        {
            semantic_id: "Molecule.set_atom_position_with_params_",
            item: callable,
            owner: molecule,
            rust: crate::Molecule::set_atom_position_with_params_,
            python: "set_atom_position_with_params_",
            javascript: "setAtomPositionWithParams",
            feature: "transforms",
            exposure: registered,
            support: unsupported,
            parity: required_when_supported,
            kind: instance,
            parameters: [
                { name: atom, type: crate::AtomId, default: required },
                { name: position, type: [f64; 3], default: required },
                { name: params, type: &crate::AtomPositionParams, default: required },
            ],
            output: (),
            error: crate::OperationError,
            state: in_place,
            operation: "set_atom_position_with_params_",
            signature: for<'a, 'b> fn(
                &'a mut crate::Molecule,
                crate::AtomId,
                [f64; 3],
                &'b crate::AtomPositionParams,
            ) -> Result<(), crate::OperationError>,
        },
        #[cfg(feature = "valence")]
        {
            semantic_id: "types.ValenceModel",
            item: type,
            owner: type_,
            rust: crate::ValenceModel,
            python: "ValenceModel",
            javascript: "ValenceModel",
            feature: "valence",
            exposure: registered,
            support: unsupported,
            parity: not_applicable,
            role: parameter,
        },
        #[cfg(feature = "valence")]
        {
            semantic_id: "types.ValenceParams",
            item: type,
            owner: type_,
            rust: crate::ValenceParams,
            python: "ValenceParams",
            javascript: "ValenceParams",
            feature: "valence",
            exposure: registered,
            support: unsupported,
            parity: not_applicable,
            role: parameter,
        },
        #[cfg(feature = "valence")]
        {
            semantic_id: "types.ValenceError",
            item: type,
            owner: type_,
            rust: crate::ValenceError,
            python: "ValenceError",
            javascript: "ValenceError",
            feature: "valence",
            exposure: registered,
            support: unsupported,
            parity: not_applicable,
            role: error,
        },
        #[cfg(feature = "valence")]
        {
            semantic_id: "Molecule.with_assigned_valence",
            item: callable,
            owner: molecule,
            rust: crate::Molecule::with_assigned_valence,
            python: "with_assigned_valence",
            javascript: "withAssignedValence",
            feature: "valence",
            exposure: registered,
            support: unsupported,
            parity: required_when_supported,
            kind: instance,
            parameters: [],
            output: crate::Molecule,
            error: crate::OperationError,
            state: value_returning,
            operation: "with_assigned_valence",
            signature: fn(&crate::Molecule) -> Result<crate::Molecule, crate::OperationError>,
        },
        #[cfg(feature = "valence")]
        {
            semantic_id: "Molecule.with_assigned_valence_with_params",
            item: callable,
            owner: molecule,
            rust: crate::Molecule::with_assigned_valence_with_params,
            python: "with_assigned_valence_with_params",
            javascript: "withAssignedValenceWithParams",
            feature: "valence",
            exposure: registered,
            support: unsupported,
            parity: required_when_supported,
            kind: instance,
            parameters: [{ name: params, type: &crate::ValenceParams, default: required }],
            output: crate::Molecule,
            error: crate::OperationError,
            state: value_returning,
            operation: "with_assigned_valence_with_params",
            signature: for<'a, 'b> fn(&'a crate::Molecule, &'b crate::ValenceParams)
                -> Result<crate::Molecule, crate::OperationError>,
        },
        #[cfg(feature = "valence")]
        {
            semantic_id: "Molecule.assign_valence_",
            item: callable,
            owner: molecule,
            rust: crate::Molecule::assign_valence_,
            python: "assign_valence_",
            javascript: "assignValence",
            feature: "valence",
            exposure: registered,
            support: unsupported,
            parity: required_when_supported,
            kind: instance,
            parameters: [],
            output: (),
            error: crate::OperationError,
            state: in_place,
            operation: "assign_valence_",
            signature: fn(&mut crate::Molecule) -> Result<(), crate::OperationError>,
        },
        #[cfg(feature = "valence")]
        {
            semantic_id: "Molecule.assign_valence_with_params_",
            item: callable,
            owner: molecule,
            rust: crate::Molecule::assign_valence_with_params_,
            python: "assign_valence_with_params_",
            javascript: "assignValenceWithParams",
            feature: "valence",
            exposure: registered,
            support: unsupported,
            parity: required_when_supported,
            kind: instance,
            parameters: [{ name: params, type: &crate::ValenceParams, default: required }],
            output: (),
            error: crate::OperationError,
            state: in_place,
            operation: "assign_valence_with_params_",
            signature: for<'a, 'b> fn(&'a mut crate::Molecule, &'b crate::ValenceParams)
                -> Result<(), crate::OperationError>,
        },
        #[cfg(feature = "valence")]
        {
            semantic_id: "Molecule.has_valence_violation",
            item: callable,
            owner: molecule,
            rust: crate::Molecule::has_valence_violation,
            python: "has_valence_violation",
            javascript: "hasValenceViolation",
            feature: "valence",
            exposure: registered,
            support: unsupported,
            parity: required_when_supported,
            kind: instance,
            parameters: [{ name: atom_id, type: crate::AtomId, default: required }],
            output: bool,
            error: crate::ValenceError,
            state: read_only,
            operation: none,
            signature: fn(&crate::Molecule, crate::AtomId)
                -> Result<bool, crate::ValenceError>,
        },
        #[cfg(feature = "radicals")]
        {
            semantic_id: "Molecule.with_assigned_radicals",
            item: callable,
            owner: molecule,
            rust: crate::Molecule::with_assigned_radicals,
            python: "with_assigned_radicals",
            javascript: "withAssignedRadicals",
            feature: "radicals",
            exposure: registered,
            support: unsupported,
            parity: required_when_supported,
            kind: instance,
            parameters: [],
            output: crate::Molecule,
            error: crate::OperationError,
            state: value_returning,
            operation: "with_assigned_radicals",
            signature: fn(&crate::Molecule) -> Result<crate::Molecule, crate::OperationError>,
        },
        #[cfg(feature = "radicals")]
        {
            semantic_id: "Molecule.assign_radicals_",
            item: callable,
            owner: molecule,
            rust: crate::Molecule::assign_radicals_,
            python: "assign_radicals_",
            javascript: "assignRadicals",
            feature: "radicals",
            exposure: registered,
            support: unsupported,
            parity: required_when_supported,
            kind: instance,
            parameters: [],
            output: (),
            error: crate::OperationError,
            state: in_place,
            operation: "assign_radicals_",
            signature: fn(&mut crate::Molecule) -> Result<(), crate::OperationError>,
        },
        #[cfg(feature = "rings")]
        {
            semantic_id: "types.RingSearchParams",
            item: type,
            owner: type_,
            rust: crate::RingSearchParams,
            python: "RingSearchParams",
            javascript: "RingSearchParams",
            feature: "rings",
            exposure: registered,
            support: unsupported,
            parity: not_applicable,
            role: parameter,
        },
        #[cfg(feature = "rings")]
        {
            semantic_id: "Molecule.with_assigned_rings",
            item: callable,
            owner: molecule,
            rust: crate::Molecule::with_assigned_rings,
            python: "with_assigned_rings",
            javascript: "withAssignedRings",
            feature: "rings",
            exposure: registered,
            support: unsupported,
            parity: required_when_supported,
            kind: instance,
            parameters: [],
            output: crate::Molecule,
            error: crate::OperationError,
            state: value_returning,
            operation: "with_assigned_rings",
            signature: fn(&crate::Molecule) -> Result<crate::Molecule, crate::OperationError>,
        },
        #[cfg(feature = "rings")]
        {
            semantic_id: "Molecule.assign_rings_",
            item: callable,
            owner: molecule,
            rust: crate::Molecule::assign_rings_,
            python: "assign_rings_",
            javascript: "assignRings",
            feature: "rings",
            exposure: registered,
            support: unsupported,
            parity: required_when_supported,
            kind: instance,
            parameters: [],
            output: (),
            error: crate::OperationError,
            state: in_place,
            operation: "assign_rings_",
            signature: fn(&mut crate::Molecule) -> Result<(), crate::OperationError>,
        },
        #[cfg(feature = "rings")]
        {
            semantic_id: "Molecule.with_assigned_ring_families",
            item: callable,
            owner: molecule,
            rust: crate::Molecule::with_assigned_ring_families,
            python: "with_assigned_ring_families",
            javascript: "withAssignedRingFamilies",
            feature: "rings",
            exposure: registered,
            support: unsupported,
            parity: required_when_supported,
            kind: instance,
            parameters: [],
            output: crate::Molecule,
            error: crate::OperationError,
            state: value_returning,
            operation: "with_assigned_ring_families",
            signature: fn(&crate::Molecule) -> Result<crate::Molecule, crate::OperationError>,
        },
        #[cfg(feature = "rings")]
        {
            semantic_id: "Molecule.with_assigned_ring_families_with_params",
            item: callable,
            owner: molecule,
            rust: crate::Molecule::with_assigned_ring_families_with_params,
            python: "with_assigned_ring_families_with_params",
            javascript: "withAssignedRingFamiliesWithParams",
            feature: "rings",
            exposure: registered,
            support: unsupported,
            parity: required_when_supported,
            kind: instance,
            parameters: [{ name: params, type: &crate::RingSearchParams, default: required }],
            output: crate::Molecule,
            error: crate::OperationError,
            state: value_returning,
            operation: "with_assigned_ring_families_with_params",
            signature: for<'a, 'b> fn(&'a crate::Molecule, &'b crate::RingSearchParams)
                -> Result<crate::Molecule, crate::OperationError>,
        },
        #[cfg(feature = "rings")]
        {
            semantic_id: "Molecule.assign_ring_families_",
            item: callable,
            owner: molecule,
            rust: crate::Molecule::assign_ring_families_,
            python: "assign_ring_families_",
            javascript: "assignRingFamilies",
            feature: "rings",
            exposure: registered,
            support: unsupported,
            parity: required_when_supported,
            kind: instance,
            parameters: [],
            output: (),
            error: crate::OperationError,
            state: in_place,
            operation: "assign_ring_families_",
            signature: fn(&mut crate::Molecule) -> Result<(), crate::OperationError>,
        },
        #[cfg(feature = "rings")]
        {
            semantic_id: "Molecule.assign_ring_families_with_params_",
            item: callable,
            owner: molecule,
            rust: crate::Molecule::assign_ring_families_with_params_,
            python: "assign_ring_families_with_params_",
            javascript: "assignRingFamiliesWithParams",
            feature: "rings",
            exposure: registered,
            support: unsupported,
            parity: required_when_supported,
            kind: instance,
            parameters: [{ name: params, type: &crate::RingSearchParams, default: required }],
            output: (),
            error: crate::OperationError,
            state: in_place,
            operation: "assign_ring_families_with_params_",
            signature: for<'a, 'b> fn(&'a mut crate::Molecule, &'b crate::RingSearchParams)
                -> Result<(), crate::OperationError>,
        },
        // CORE-structure_tags is registered before its detached implementation
        // and live wrappers are enabled. The short variants select the source
        // defaults (`conformer_id = -1`, `replace_existing_tags = true`); the
        // `_with_params` variants expose exactly those two fields through one
        // immutable parameter value. The public result is the canonical
        // Molecule/() operation result, never the detached assignment block.
        #[cfg(feature = "stereo")]
        {
            semantic_id: "types.StructureTagParams",
            item: type,
            owner: type_,
            rust: crate::StructureTagParams,
            python: "StructureTagParams",
            javascript: "StructureTagParams",
            feature: "stereo",
            exposure: registered,
            support: unsupported,
            parity: required_when_supported,
            role: parameter,
        },
        #[cfg(feature = "stereo")]
        {
            semantic_id: "types.StereoError",
            item: type,
            owner: type_,
            rust: crate::StereoError,
            python: "StereoError",
            javascript: "StereoError",
            feature: "stereo",
            exposure: registered,
            support: unsupported,
            parity: not_applicable,
            role: error,
        },
        #[cfg(feature = "stereo")]
        {
            semantic_id: "Molecule.with_chiral_tags_from_structure",
            item: callable,
            owner: molecule,
            rust: crate::Molecule::with_chiral_tags_from_structure,
            python: "with_chiral_tags_from_structure",
            javascript: "withChiralTagsFromStructure",
            feature: "stereo",
            exposure: registered,
            support: unsupported,
            parity: required_when_supported,
            kind: instance,
            parameters: [],
            output: crate::Molecule,
            error: crate::OperationError,
            state: value_returning,
            operation: "with_chiral_tags_from_structure",
            signature: fn(&crate::Molecule) -> Result<crate::Molecule, crate::OperationError>,
        },
        #[cfg(feature = "stereo")]
        {
            semantic_id: "Molecule.with_chiral_tags_from_structure_with_params",
            item: callable,
            owner: molecule,
            rust: crate::Molecule::with_chiral_tags_from_structure_with_params,
            python: "with_chiral_tags_from_structure_with_params",
            javascript: "withChiralTagsFromStructureWithParams",
            feature: "stereo",
            exposure: registered,
            support: unsupported,
            parity: required_when_supported,
            kind: instance,
            parameters: [
                { name: params, type: &crate::StructureTagParams, default: required },
            ],
            output: crate::Molecule,
            error: crate::OperationError,
            state: value_returning,
            operation: "with_chiral_tags_from_structure_with_params",
            signature: for<'a, 'b> fn(
                &'a crate::Molecule,
                &'b crate::StructureTagParams,
            ) -> Result<crate::Molecule, crate::OperationError>,
        },
        #[cfg(feature = "stereo")]
        {
            semantic_id: "Molecule.assign_chiral_tags_from_structure_",
            item: callable,
            owner: molecule,
            rust: crate::Molecule::assign_chiral_tags_from_structure_,
            python: "assign_chiral_tags_from_structure_",
            javascript: "assignChiralTagsFromStructure",
            feature: "stereo",
            exposure: registered,
            support: unsupported,
            parity: required_when_supported,
            kind: instance,
            parameters: [],
            output: (),
            error: crate::OperationError,
            state: in_place,
            operation: "assign_chiral_tags_from_structure_",
            signature: fn(&mut crate::Molecule) -> Result<(), crate::OperationError>,
        },
        #[cfg(feature = "stereo")]
        {
            semantic_id: "Molecule.assign_chiral_tags_from_structure_with_params_",
            item: callable,
            owner: molecule,
            rust: crate::Molecule::assign_chiral_tags_from_structure_with_params_,
            python: "assign_chiral_tags_from_structure_with_params_",
            javascript: "assignChiralTagsFromStructureWithParams",
            feature: "stereo",
            exposure: registered,
            support: unsupported,
            parity: required_when_supported,
            kind: instance,
            parameters: [
                { name: params, type: &crate::StructureTagParams, default: required },
            ],
            output: (),
            error: crate::OperationError,
            state: in_place,
            operation: "assign_chiral_tags_from_structure_with_params_",
            signature: for<'a, 'b> fn(
                &'a mut crate::Molecule,
                &'b crate::StructureTagParams,
            ) -> Result<(), crate::OperationError>,
        },
        // CORE-potential is registered before its live wrapper is enabled.
        // These rows freeze the canonical public spelling and typed result
        // surface; the source-backed perception algorithm remains uniquely
        // owned by `cosmolkit-core`.
        #[cfg(feature = "stereo")]
        {
            semantic_id: "types.PotentialStereoParams",
            item: type,
            owner: type_,
            rust: crate::PotentialStereoParams,
            python: "PotentialStereoParams",
            javascript: "PotentialStereoParams",
            feature: "stereo",
            exposure: registered,
            support: unsupported,
            parity: required_when_supported,
            role: parameter,
        },
        #[cfg(feature = "stereo")]
        {
            semantic_id: "types.PotentialStereoType",
            item: type,
            owner: type_,
            rust: crate::PotentialStereoType,
            python: "PotentialStereoType",
            javascript: "PotentialStereoType",
            feature: "stereo",
            exposure: registered,
            support: unsupported,
            parity: required_when_supported,
            role: value,
        },
        #[cfg(feature = "stereo")]
        {
            semantic_id: "types.PotentialStereoSpecified",
            item: type,
            owner: type_,
            rust: crate::PotentialStereoSpecified,
            python: "PotentialStereoSpecified",
            javascript: "PotentialStereoSpecified",
            feature: "stereo",
            exposure: registered,
            support: unsupported,
            parity: required_when_supported,
            role: value,
        },
        #[cfg(feature = "stereo")]
        {
            semantic_id: "types.PotentialStereoDescriptor",
            item: type,
            owner: type_,
            rust: crate::PotentialStereoDescriptor,
            python: "PotentialStereoDescriptor",
            javascript: "PotentialStereoDescriptor",
            feature: "stereo",
            exposure: registered,
            support: unsupported,
            parity: required_when_supported,
            role: value,
        },
        #[cfg(feature = "stereo")]
        {
            semantic_id: "types.PotentialStereoCenter",
            item: type,
            owner: type_,
            rust: crate::PotentialStereoCenter,
            python: "PotentialStereoCenter",
            javascript: "PotentialStereoCenter",
            feature: "stereo",
            exposure: registered,
            support: unsupported,
            parity: required_when_supported,
            role: value,
        },
        #[cfg(feature = "stereo")]
        {
            semantic_id: "types.PotentialStereoInfo",
            item: type,
            owner: type_,
            rust: crate::PotentialStereoInfo,
            python: "PotentialStereoInfo",
            javascript: "PotentialStereoInfo",
            feature: "stereo",
            exposure: registered,
            support: unsupported,
            parity: required_when_supported,
            role: value,
        },
        #[cfg(feature = "stereo")]
        {
            semantic_id: "types.RingStereoRelation",
            item: type,
            owner: type_,
            rust: crate::RingStereoRelation,
            python: "RingStereoRelation",
            javascript: "RingStereoRelation",
            feature: "stereo",
            exposure: registered,
            support: unsupported,
            parity: required_when_supported,
            role: value,
        },
        #[cfg(feature = "stereo")]
        {
            semantic_id: "types.PotentialStereoResult",
            item: type,
            owner: type_,
            rust: crate::PotentialStereoResult,
            python: "PotentialStereoResult",
            javascript: "PotentialStereoResult",
            feature: "stereo",
            exposure: registered,
            support: unsupported,
            parity: required_when_supported,
            role: result,
        },
        #[cfg(feature = "stereo")]
        {
            semantic_id: "types.PotentialStereoError",
            item: type,
            owner: type_,
            rust: crate::PotentialStereoError,
            python: "PotentialStereoError",
            javascript: "PotentialStereoError",
            feature: "stereo",
            exposure: registered,
            support: unsupported,
            parity: not_applicable,
            role: error,
        },
        #[cfg(feature = "stereo")]
        {
            semantic_id: "Molecule.potential_stereo",
            item: callable,
            owner: molecule,
            rust: crate::Molecule::potential_stereo,
            python: "potential_stereo",
            javascript: "potentialStereo",
            feature: "stereo",
            exposure: registered,
            support: unsupported,
            parity: required_when_supported,
            kind: instance,
            parameters: [],
            output: crate::PotentialStereoResult,
            error: crate::OperationError,
            state: read_only,
            operation: "potential_stereo",
            signature: fn(&crate::Molecule)
                -> Result<crate::PotentialStereoResult, crate::OperationError>,
        },
        #[cfg(feature = "stereo")]
        {
            semantic_id: "Molecule.potential_stereo_with_params",
            item: callable,
            owner: molecule,
            rust: crate::Molecule::potential_stereo_with_params,
            python: "potential_stereo_with_params",
            javascript: "potentialStereoWithParams",
            feature: "stereo",
            exposure: registered,
            support: unsupported,
            parity: required_when_supported,
            kind: instance,
            parameters: [
                { name: params, type: &crate::PotentialStereoParams, default: required },
            ],
            output: crate::PotentialStereoResult,
            error: crate::OperationError,
            state: value_returning,
            operation: "potential_stereo_with_params",
            signature: for<'a, 'b> fn(
                &'a crate::Molecule,
                &'b crate::PotentialStereoParams,
            ) -> Result<crate::PotentialStereoResult, crate::OperationError>,
        },
        #[cfg(feature = "descriptors")]
        {
            semantic_id: "Molecule.molecular_weight",
            item: callable,
            owner: molecule,
            rust: crate::Molecule::molecular_weight,
            python: "molecular_weight",
            javascript: "molecularWeight",
            feature: "descriptors",
            exposure: public,
            support: experimental,
            parity: required_when_supported,
            kind: instance,
            parameters: [],
            output: f64,
            error: crate::OperationError,
            state: read_only,
            operation: none,
            signature: fn(&crate::Molecule) -> Result<f64, crate::OperationError>,
        },
        #[cfg(feature = "descriptors")]
        {
            semantic_id: "Molecule.exact_molecular_weight",
            item: callable,
            owner: molecule,
            rust: crate::Molecule::exact_molecular_weight,
            python: "exact_molecular_weight",
            javascript: "exactMolecularWeight",
            feature: "descriptors",
            exposure: public,
            support: experimental,
            parity: required_when_supported,
            kind: instance,
            parameters: [],
            output: f64,
            error: crate::OperationError,
            state: read_only,
            operation: none,
            signature: fn(&crate::Molecule) -> Result<f64, crate::OperationError>,
        },
        #[cfg(feature = "descriptors")]
        {
            semantic_id: "Molecule.molecular_formula",
            item: callable,
            owner: molecule,
            rust: crate::Molecule::molecular_formula,
            python: "molecular_formula",
            javascript: "molecularFormula",
            feature: "descriptors",
            exposure: public,
            support: experimental,
            parity: required_when_supported,
            kind: instance,
            parameters: [],
            output: String,
            error: crate::OperationError,
            state: read_only,
            operation: none,
            signature: fn(&crate::Molecule) -> Result<String, crate::OperationError>,
        },
        #[cfg(feature = "hydrogens")]
        {
            semantic_id: "Molecule.with_hydrogens",
            item: callable,
            owner: molecule,
            rust: crate::Molecule::with_hydrogens,
            python: "with_hydrogens",
            javascript: "withHydrogens",
            feature: "hydrogens",
            exposure: public,
            support: unsupported,
            parity: required_when_supported,
            kind: instance,
            parameters: [],
            output: crate::Molecule,
            error: crate::OperationError,
            state: value_returning,
            operation: "with_hydrogens",
            signature: fn(&crate::Molecule) -> Result<crate::Molecule, crate::OperationError>,
        },
        #[cfg(feature = "hydrogens")]
        {
            semantic_id: "Molecule.add_hydrogens_",
            item: callable,
            owner: molecule,
            rust: crate::Molecule::add_hydrogens_,
            python: "add_hydrogens_",
            javascript: "addHydrogens",
            feature: "hydrogens",
            exposure: public,
            support: unsupported,
            parity: required_when_supported,
            kind: instance,
            parameters: [],
            output: (),
            error: crate::OperationError,
            state: in_place,
            operation: "add_hydrogens_",
            signature: fn(&mut crate::Molecule) -> Result<(), crate::OperationError>,
        },
        #[cfg(feature = "hydrogens")]
        {
            semantic_id: "Molecule.without_hydrogens",
            item: callable,
            owner: molecule,
            rust: crate::Molecule::without_hydrogens,
            python: "without_hydrogens",
            javascript: "withoutHydrogens",
            feature: "hydrogens",
            exposure: public,
            support: unsupported,
            parity: required_when_supported,
            kind: instance,
            parameters: [],
            output: crate::Molecule,
            error: crate::OperationError,
            state: value_returning,
            operation: "without_hydrogens",
            signature: fn(&crate::Molecule) -> Result<crate::Molecule, crate::OperationError>,
        },
        #[cfg(feature = "hydrogens")]
        {
            semantic_id: "Molecule.remove_hydrogens_",
            item: callable,
            owner: molecule,
            rust: crate::Molecule::remove_hydrogens_,
            python: "remove_hydrogens_",
            javascript: "removeHydrogens",
            feature: "hydrogens",
            exposure: public,
            support: unsupported,
            parity: required_when_supported,
            kind: instance,
            parameters: [],
            output: (),
            error: crate::OperationError,
            state: in_place,
            operation: "remove_hydrogens_",
            signature: fn(&mut crate::Molecule) -> Result<(), crate::OperationError>,
        },
    ];
}
